// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package startup

import (
	"context"
	"os"
	"strings"

	"github.com/alchemillahq/sylve/pkg/utils"
)

func (s *Service) InitISCSI(_ context.Context) error {
	const marker = "# === This file is automatically generated by Sylve, don't edit! ==="

	backupFile := func(path, backupPath string) error {
		data, err := os.ReadFile(path)
		if err != nil {
			if !os.IsNotExist(err) {
				return err
			}
			return nil
		}
		if !strings.Contains(string(data), marker) {
			exists, err := utils.FileExists(backupPath)
			if err != nil {
				return err
			}
			if !exists {
				if err := utils.CopyFile(path, backupPath); err != nil {
					return err
				}
			}
		}
		return nil
	}

	if err := backupFile("/etc/iscsi.conf", "/etc/iscsi.conf.pre-sylve"); err != nil {
		return err
	}

	if err := backupFile("/etc/ctl.conf", "/etc/ctl.conf.pre-sylve"); err != nil {
		return err
	}

	if err := s.ISCSI.WriteConfig(false); err != nil {
		return err
	}

	return s.ISCSI.WriteTargetConfig(false)
}
