// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package startup

import (
	"context"
	"os"
	"strings"

	"github.com/alchemillahq/sylve/pkg/utils"
)

func (s *Service) InitISCSI(_ context.Context) error {
	const marker = "# === This file is automatically generated by Sylve, don't edit! ==="
	cfgPath := "/etc/iscsi.conf"
	backupPath := "/etc/iscsi.conf.pre-sylve"

	data, err := os.ReadFile(cfgPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
	} else {
		if !strings.Contains(string(data), marker) {
			exists, err := utils.FileExists(backupPath)
			if err != nil {
				return err
			}
			if !exists {
				if err := utils.CopyFile(cfgPath, backupPath); err != nil {
					return err
				}
			}
		}
	}

	return s.ISCSI.WriteConfig(false)
}
