// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package startup

import (
	"context"
	"errors"
	"os"
	"strings"
	"time"

	"github.com/alchemillahq/sylve/pkg/utils"
)

const iscsiConfigMarker = "# === This file is automatically generated by Sylve, don't edit! ==="

func ensureISCSIInitiatorDaemon(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if _, err := utils.RunCommandWithInputContext(ctx, "", "/usr/sbin/service", "iscsid", "onestatus"); err == nil {
		return nil
	}
	if _, err := utils.RunCommandWithInputContext(ctx, "", "/usr/sbin/service", "iscsid", "onestart"); err != nil {
		return errors.New("failed_to_start_initiator_service")
	}
	return nil
}

func backupUnmanagedISCSIConfig(path, backupPath string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	if strings.HasPrefix(string(data), iscsiConfigMarker+"\n") {
		return nil
	}

	exists, err := utils.FileExists(backupPath)
	if err != nil {
		return err
	}
	if exists {
		return os.Chmod(backupPath, 0600)
	}

	return utils.AtomicWriteFile(backupPath, data, 0600)
}

func (s *Service) InitISCSI(_ context.Context) error {
	if err := backupUnmanagedISCSIConfig("/etc/iscsi.conf", "/etc/iscsi.conf.pre-sylve"); err != nil {
		return err
	}

	if err := backupUnmanagedISCSIConfig("/etc/ctl.conf", "/etc/ctl.conf.pre-sylve"); err != nil {
		return err
	}

	return nil
}
