// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package startup

import (
	"context"
	"fmt"
	"os"
	"strings"

	sambaModels "github.com/alchemillahq/sylve/internal/db/models/samba"
	"github.com/alchemillahq/sylve/pkg/utils"
)

func (s *Service) InitSamba(ctx context.Context) error {
	const marker = "# === This file is automatically generated by Sylve, don't edit! ==="
	cfgPath := "/usr/local/etc/smb4.conf"
	backupPath := "/usr/local/etc/smb4.conf.pre-sylve"

	data, err := os.ReadFile(cfgPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
	} else {
		if !strings.Contains(string(data), marker) {
			exists, err := utils.FileExists(backupPath)
			if err != nil {
				return err
			}
			if !exists {
				if err := utils.CopyFile(cfgPath, backupPath); err != nil {
					return err
				}
			}
		}
	}

	var count int64
	if err := s.DB.Model(&sambaModels.SambaSettings{}).Count(&count).Error; err != nil {
		return err
	}
	if count == 0 {
		defaultSettings := sambaModels.SambaSettings{
			UnixCharset:        "UTF-8",
			Workgroup:          "WORKGROUP",
			BindInterfacesOnly: true,
		}
		if err := s.DB.Create(&defaultSettings).Error; err != nil {
			return err
		}
	}

	if err := s.Samba.DisableMissingShares(ctx); err != nil {
		return fmt.Errorf("failed to reconcile Samba shares: %w", err)
	}

	if err := s.Samba.WriteConfig(ctx, false); err != nil {
		return err
	}

	return nil
}
