// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package network

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/alchemillahq/sylve/internal/db/models"
	networkModels "github.com/alchemillahq/sylve/internal/db/models/network"
	networkServiceInterfaces "github.com/alchemillahq/sylve/internal/interfaces/services/network"
	"github.com/alchemillahq/sylve/internal/logger"
	"github.com/alchemillahq/sylve/pkg/system"
	"github.com/alchemillahq/sylve/pkg/utils"
	"gorm.io/gorm"
)

const (
	pfMainConfPath          = "/etc/pf.conf"
	pfBackupConfPath        = "/etc/pf.conf.pre-sylve"
	pfSylveDir              = "/etc/pf.sylve"
	pfObjectTablesPath      = "/etc/pf.sylve/object-tables.conf"
	pfNatRulesPath          = "/etc/pf.sylve/nat-rules.conf"
	pfTrafficRulesPath      = "/etc/pf.sylve/traffic-rules.conf"
	pfManagedHeader         = "# === This file is automatically generated by Sylve, don't edit! ==="
	defaultFirewallPriority = 1
	defaultAllowRuleInName  = "Allow Inbound All"
	defaultAllowRuleOutName = "Allow Outbound All"
)

const errHiddenFirewallRuleMutation = "hidden_firewall_rule_managed_by_wireguard"

var firewallRCConfPath = "/etc/rc.conf"
var firewallRunCommand = utils.RunCommand
var pfValidationLinePattern = regexp.MustCompile(`^(.+?):([0-9]+):\s*(.+)$`)
var pfTrafficRuleLabelPattern = regexp.MustCompile(`label\s+"sylve_trf_([0-9]+)"`)
var pfNATRuleLabelPattern = regexp.MustCompile(`(?:label\s+"sylve_nat_([0-9]+)"|tag\s+"?sylve_nat_([0-9]+)"?)`)
var pfTrafficRuleCounterPattern = regexp.MustCompile(`Packets:\s*([0-9]+)\s+Bytes:\s*([0-9]+)`)

func buildPFDisabledConfig() string {
	var b strings.Builder
	b.WriteString(pfManagedHeader)
	b.WriteString("\n\n")
	b.WriteString("# firewall disabled in Sylve; keep default network access open\n")
	b.WriteString("pass all\n")
	return b.String()
}

func parseRCConfAssignment(line string) (string, string, bool) {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, ";") {
		return "", "", false
	}

	index := strings.Index(trimmed, "=")
	if index < 0 {
		return "", "", false
	}

	key := strings.TrimSpace(trimmed[:index])
	if key == "" {
		return "", "", false
	}

	rawValue := strings.TrimSpace(trimmed[index+1:])
	rawValue = strings.Trim(rawValue, `"'`)
	rawValue = strings.TrimSpace(rawValue)
	return key, rawValue, true
}

func (s *Service) ensurePFAutostartDisabledInRCConf() error {
	data, err := os.ReadFile(firewallRCConfPath)
	if err != nil && !strings.Contains(strings.ToLower(err.Error()), "no such file") {
		return err
	}

	lines := []string{}
	if len(data) > 0 {
		lines = strings.Split(strings.TrimSuffix(string(data), "\n"), "\n")
	}

	updated := make([]string, 0, len(lines)+1)
	seenPFEnable := false
	changed := false

	for _, line := range lines {
		key, value, ok := parseRCConfAssignment(line)
		if !ok || key != "pf_enable" {
			updated = append(updated, line)
			continue
		}

		if seenPFEnable {
			changed = true
			continue
		}

		seenPFEnable = true
		if strings.EqualFold(value, "no") {
			updated = append(updated, `pf_enable="NO"`)
			if line != `pf_enable="NO"` {
				changed = true
			}
			continue
		}

		updated = append(updated, `pf_enable="NO"`)
		changed = true
	}

	if !seenPFEnable {
		updated = append(updated, `pf_enable="NO"`)
		changed = true
	}

	if !changed {
		return nil
	}

	perm := os.FileMode(0644)
	if info, statErr := os.Stat(firewallRCConfPath); statErr == nil {
		perm = info.Mode().Perm()
	}

	content := ""
	if len(updated) > 0 {
		content = strings.Join(updated, "\n") + "\n"
	}

	return atomicWriteFile(firewallRCConfPath, []byte(content), perm)
}

func (s *Service) isSylveManagedPFConfig() (bool, error) {
	data, err := os.ReadFile(pfMainConfPath)
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "no such file") {
			return false, nil
		}
		return false, err
	}

	content := string(data)
	return strings.Contains(content, pfManagedHeader), nil
}

func (s *Service) IsFirewallServiceEnabled() bool {
	var basicSettings models.BasicSettings
	if err := s.DB.First(&basicSettings).Error; err != nil {
		return false
	}

	return slices.Contains(basicSettings.Services, models.Firewall)
}

func (s *Service) ApplyFirewallIfEnabled() error {
	if !s.IsFirewallServiceEnabled() {
		return nil
	}

	return s.ApplyFirewallConfig()
}

func (s *Service) SyncFirewallRuntimeState() error {
	if err := s.ensurePFAutostartDisabledInRCConf(); err != nil {
		return err
	}

	if s.IsFirewallServiceEnabled() {
		return s.ApplyFirewallConfig()
	}

	if !s.isPFEnabled() {
		return nil
	}

	managed, err := s.isSylveManagedPFConfig()
	if err != nil {
		return err
	}
	if !managed {
		return nil
	}

	return s.DisableFirewall()
}

func (s *Service) DisableFirewall() error {
	if err := s.ensurePFAutostartDisabledInRCConf(); err != nil {
		return err
	}

	if err := atomicWriteFile(pfMainConfPath, []byte(buildPFDisabledConfig()), 0644); err != nil {
		return err
	}

	err := system.ServiceAction("pf", "onestop")
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "not running") {
			return nil
		}
		return err
	}

	return nil
}

func (s *Service) GetFirewallTrafficRules() ([]networkModels.FirewallTrafficRule, error) {
	var rules []networkModels.FirewallTrafficRule
	if err := s.DB.
		Where("visible = ?", true).
		Order("priority ASC, id ASC").
		Find(&rules).Error; err != nil {
		return nil, err
	}

	for i := range rules {
		if rules[i].IngressInterfaces == nil {
			rules[i].IngressInterfaces = []string{}
		}
		if rules[i].EgressInterfaces == nil {
			rules[i].EgressInterfaces = []string{}
		}
	}

	return rules, nil
}

func (s *Service) getFirewallTrafficRulesForApply() ([]networkModels.FirewallTrafficRule, error) {
	var rules []networkModels.FirewallTrafficRule
	if err := s.DB.
		Preload("SourceObj.Entries").
		Preload("DestObj.Entries").
		Preload("SrcPortObj.Entries").
		Preload("DstPortObj.Entries").
		Order("priority ASC, id ASC").
		Find(&rules).Error; err != nil {
		return nil, err
	}

	for i := range rules {
		if rules[i].IngressInterfaces == nil {
			rules[i].IngressInterfaces = []string{}
		}
		if rules[i].EgressInterfaces == nil {
			rules[i].EgressInterfaces = []string{}
		}
	}

	return rules, nil
}

type trafficRuleCounterTotals struct {
	Packets uint64
	Bytes   uint64
}

func trafficRuleLabel(ruleID uint) string {
	return fmt.Sprintf("sylve_trf_%d", ruleID)
}

func natRuleLabel(ruleID uint) string {
	return fmt.Sprintf("sylve_nat_%d", ruleID)
}

func natPolicyRuleLabel(ruleID uint, direction string) string {
	dir := strings.TrimSpace(strings.ToLower(direction))
	if dir == "in" || dir == "out" {
		return fmt.Sprintf("sylve_nat_policy_%d_%s", ruleID, dir)
	}
	return fmt.Sprintf("sylve_nat_policy_%d", ruleID)
}

func parseTrafficRuleCountersFromPF(output string) map[uint]trafficRuleCounterTotals {
	counters, _ := parseLabeledRuleCounters(output, pfTrafficRuleLabelPattern)
	return counters
}

func (s *Service) GetFirewallTrafficRuleCounters() ([]networkServiceInterfaces.FirewallTrafficRuleCounter, error) {
	rules, err := s.GetFirewallTrafficRules()
	if err != nil {
		return nil, err
	}

	if len(rules) == 0 {
		return []networkServiceInterfaces.FirewallTrafficRuleCounter{}, nil
	}

	updatedAt := time.Now().UTC()
	totalsByRuleID := make(map[uint]trafficRuleCounterTotals)

	if s.isPFEnabled() {
		if totals, _, pfErr := s.collectTrafficCountersFromPF(); pfErr == nil {
			totalsByRuleID = totals
		}
	}

	counters := make([]networkServiceInterfaces.FirewallTrafficRuleCounter, 0, len(rules))
	for _, rule := range rules {
		totals := totalsByRuleID[rule.ID]
		counters = append(counters, networkServiceInterfaces.FirewallTrafficRuleCounter{
			ID:        rule.ID,
			Packets:   totals.Packets,
			Bytes:     totals.Bytes,
			UpdatedAt: updatedAt,
		})
	}

	return counters, nil
}

func (s *Service) ensureDefaultAllowTrafficRules() error {
	var count int64
	if err := s.DB.Model(&networkModels.FirewallTrafficRule{}).Where("visible = ?", true).Count(&count).Error; err != nil {
		return err
	}

	if count > 0 {
		return nil
	}

	rules := []networkModels.FirewallTrafficRule{
		{
			Name:        defaultAllowRuleInName,
			Description: "Auto-created by Sylve to preserve allow-by-default baseline policy.",
			Visible:     true,
			Enabled:     true,
			Log:         false,
			Quick:       false,
			Priority:    defaultFirewallPriority,
			Action:      "pass",
			Direction:   "in",
			Protocol:    "any",
			Family:      "any",
			SourceRaw:   "any",
			DestRaw:     "any",
		},
		{
			Name:        defaultAllowRuleOutName,
			Description: "Auto-created by Sylve to preserve allow-by-default baseline policy.",
			Visible:     true,
			Enabled:     true,
			Log:         false,
			Quick:       false,
			Priority:    defaultFirewallPriority + 1,
			Action:      "pass",
			Direction:   "out",
			Protocol:    "any",
			Family:      "any",
			SourceRaw:   "any",
			DestRaw:     "any",
		},
	}

	return s.DB.Create(&rules).Error
}

func (s *Service) GetFirewallNATRules() ([]networkModels.FirewallNATRule, error) {
	var rules []networkModels.FirewallNATRule
	if err := s.DB.
		Where("visible = ?", true).
		Order("priority ASC, id ASC").
		Find(&rules).Error; err != nil {
		return nil, err
	}

	for i := range rules {
		if rules[i].IngressInterfaces == nil {
			rules[i].IngressInterfaces = []string{}
		}
		if rules[i].EgressInterfaces == nil {
			rules[i].EgressInterfaces = []string{}
		}
	}

	return rules, nil
}

func (s *Service) getFirewallNATRulesForApply() ([]networkModels.FirewallNATRule, error) {
	var rules []networkModels.FirewallNATRule
	if err := s.DB.
		Preload("SourceObj.Entries").
		Preload("DestObj.Entries").
		Preload("TranslateToObj.Entries").
		Preload("DNATTargetObj.Entries").
		Preload("DstPortObj.Entries").
		Preload("RedirectPortObj.Entries").
		Order("priority ASC, id ASC").
		Find(&rules).Error; err != nil {
		return nil, err
	}

	for i := range rules {
		if rules[i].IngressInterfaces == nil {
			rules[i].IngressInterfaces = []string{}
		}
		if rules[i].EgressInterfaces == nil {
			rules[i].EgressInterfaces = []string{}
		}
	}

	return rules, nil
}

func (s *Service) GetFirewallAdvancedSettings() (*networkModels.FirewallAdvancedSettings, error) {
	var settings networkModels.FirewallAdvancedSettings
	if err := s.DB.First(&settings).Error; err != nil {
		return nil, err
	}

	return &settings, nil
}

func (s *Service) nextFirewallTrafficPriority() (int, error) {
	var maxPriority int
	if err := s.DB.Model(&networkModels.FirewallTrafficRule{}).Select("COALESCE(MAX(priority), 0)").Scan(&maxPriority).Error; err != nil {
		return defaultFirewallPriority, err
	}
	if maxPriority == 0 {
		return defaultFirewallPriority, nil
	}
	return maxPriority + 1, nil
}

func (s *Service) nextFirewallNATPriority() (int, error) {
	var maxPriority int
	if err := s.DB.Model(&networkModels.FirewallNATRule{}).Select("COALESCE(MAX(priority), 0)").Scan(&maxPriority).Error; err != nil {
		return defaultFirewallPriority, err
	}
	if maxPriority == 0 {
		return defaultFirewallPriority, nil
	}
	return maxPriority + 1, nil
}

func normalizePriority(priority int) int {
	if priority < defaultFirewallPriority {
		return defaultFirewallPriority
	}
	return priority
}

func (s *Service) maxHiddenTrafficPriority(tx *gorm.DB) (int, error) {
	var maxPriority int
	if err := tx.Model(&networkModels.FirewallTrafficRule{}).
		Where("visible = ?", false).
		Select("COALESCE(MAX(priority), 0)").
		Scan(&maxPriority).Error; err != nil {
		return 0, err
	}
	return maxPriority, nil
}

func (s *Service) maxHiddenNATPriority(tx *gorm.DB) (int, error) {
	var maxPriority int
	if err := tx.Model(&networkModels.FirewallNATRule{}).
		Where("visible = ?", false).
		Select("COALESCE(MAX(priority), 0)").
		Scan(&maxPriority).Error; err != nil {
		return 0, err
	}
	return maxPriority, nil
}

func (s *Service) shiftTrafficRulesDownFrom(tx *gorm.DB, fromPriority int, excludeID uint) error {
	query := tx.Model(&networkModels.FirewallTrafficRule{}).Where("priority >= ?", fromPriority)
	if excludeID > 0 {
		query = query.Where("id <> ?", excludeID)
	}
	return query.Update("priority", gorm.Expr("priority + 1")).Error
}

func (s *Service) shiftNATRulesDownFrom(tx *gorm.DB, fromPriority int, excludeID uint) error {
	query := tx.Model(&networkModels.FirewallNATRule{}).Where("priority >= ?", fromPriority)
	if excludeID > 0 {
		query = query.Where("id <> ?", excludeID)
	}
	return query.Update("priority", gorm.Expr("priority + 1")).Error
}

func (s *Service) moveTrafficRulePriority(tx *gorm.DB, ruleID uint, currentPriority int, desiredPriority int) error {
	if currentPriority == desiredPriority {
		return nil
	}
	if desiredPriority < currentPriority {
		if err := tx.Model(&networkModels.FirewallTrafficRule{}).
			Where("id <> ? AND priority >= ? AND priority < ?", ruleID, desiredPriority, currentPriority).
			Update("priority", gorm.Expr("priority + 1")).Error; err != nil {
			return err
		}
		return nil
	}
	return tx.Model(&networkModels.FirewallTrafficRule{}).
		Where("id <> ? AND priority <= ? AND priority > ?", ruleID, desiredPriority, currentPriority).
		Update("priority", gorm.Expr("priority - 1")).Error
}

func (s *Service) moveNATRulePriority(tx *gorm.DB, ruleID uint, currentPriority int, desiredPriority int) error {
	if currentPriority == desiredPriority {
		return nil
	}
	if desiredPriority < currentPriority {
		if err := tx.Model(&networkModels.FirewallNATRule{}).
			Where("id <> ? AND priority >= ? AND priority < ?", ruleID, desiredPriority, currentPriority).
			Update("priority", gorm.Expr("priority + 1")).Error; err != nil {
			return err
		}
		return nil
	}
	return tx.Model(&networkModels.FirewallNATRule{}).
		Where("id <> ? AND priority <= ? AND priority > ?", ruleID, desiredPriority, currentPriority).
		Update("priority", gorm.Expr("priority - 1")).Error
}

func snapshotTrafficPriorities(tx *gorm.DB) (map[uint]int, error) {
	var rules []networkModels.FirewallTrafficRule
	if err := tx.Select("id,priority").Find(&rules).Error; err != nil {
		return nil, err
	}
	out := make(map[uint]int, len(rules))
	for _, rule := range rules {
		out[rule.ID] = rule.Priority
	}
	return out, nil
}

func snapshotNATPriorities(tx *gorm.DB) (map[uint]int, error) {
	var rules []networkModels.FirewallNATRule
	if err := tx.Select("id,priority").Find(&rules).Error; err != nil {
		return nil, err
	}
	out := make(map[uint]int, len(rules))
	for _, rule := range rules {
		out[rule.ID] = rule.Priority
	}
	return out, nil
}

func restoreTrafficPriorities(tx *gorm.DB, snapshot map[uint]int) error {
	for id, priority := range snapshot {
		if err := tx.Model(&networkModels.FirewallTrafficRule{}).Where("id = ?", id).Update("priority", priority).Error; err != nil {
			return err
		}
	}
	return nil
}

func restoreNATPriorities(tx *gorm.DB, snapshot map[uint]int) error {
	for id, priority := range snapshot {
		if err := tx.Model(&networkModels.FirewallNATRule{}).Where("id = ?", id).Update("priority", priority).Error; err != nil {
			return err
		}
	}
	return nil
}

func (s *Service) validateFirewallAddressObjectRef(id *uint) error {
	if id == nil || *id == 0 {
		return nil
	}

	var object networkModels.Object
	if err := s.DB.Select("id,type").First(&object, *id).Error; err != nil {
		return fmt.Errorf("invalid_object_ref: %w", err)
	}

	switch object.Type {
	case "Host", "Network", "FQDN", "List":
		return nil
	default:
		return fmt.Errorf("invalid_object_type_for_address_selector: %s", object.Type)
	}
}

func (s *Service) validateFirewallPortObjectRef(id *uint) error {
	if id == nil || *id == 0 {
		return nil
	}

	var object networkModels.Object
	if err := s.DB.Select("id,type").First(&object, *id).Error; err != nil {
		return fmt.Errorf("invalid_object_ref: %w", err)
	}

	if object.Type != "Port" {
		return fmt.Errorf("invalid_object_type_for_port_selector: %s", object.Type)
	}

	return nil
}

func normalizeFirewallRequestStrings(raw string) string {
	return strings.TrimSpace(raw)
}

func normalizeProtocol(protocol string) string {
	p := strings.TrimSpace(strings.ToLower(protocol))
	if p == "" {
		return "any"
	}
	return p
}

func normalizeFamily(family string) string {
	f := strings.TrimSpace(strings.ToLower(family))
	if f == "" {
		return "any"
	}
	return f
}

func normalizeDirection(direction string) string {
	d := strings.TrimSpace(strings.ToLower(direction))
	if d == "" {
		return "in"
	}
	return d
}

func normalizeNATType(natType string) string {
	n := strings.TrimSpace(strings.ToLower(natType))
	if n == "" {
		return "snat"
	}
	return n
}

func normalizeTranslateMode(mode string) string {
	m := strings.TrimSpace(strings.ToLower(mode))
	if m == "" {
		return "interface"
	}
	return m
}

func normalizeInterfaceList(values []string) []string {
	if len(values) == 0 {
		return []string{}
	}

	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		iface := strings.TrimSpace(value)
		if iface == "" {
			continue
		}
		if _, ok := seen[iface]; ok {
			continue
		}
		seen[iface] = struct{}{}
		out = append(out, iface)
	}
	return out
}

func hasSelector(raw string, objID *uint) bool {
	return strings.TrimSpace(raw) != "" || (objID != nil && *objID > 0)
}

func validateFamilyAgainstRawAddress(value string, family string, allowCIDR bool, field string, allowAnyLiteral bool) error {
	v := strings.TrimSpace(value)
	if v == "" {
		return nil
	}

	if allowAnyLiteral && strings.EqualFold(v, "any") {
		return nil
	}

	isV4 := utils.IsValidIPv4(v)
	isV6 := utils.IsValidIPv6(v)
	isV4CIDR := utils.IsValidIPv4CIDR(v)
	isV6CIDR := utils.IsValidIPv6CIDR(v)

	if !(isV4 || isV6 || isV4CIDR || isV6CIDR) {
		return fmt.Errorf("invalid_%s_address: %s", field, v)
	}

	if !allowCIDR && (isV4CIDR || isV6CIDR) {
		return fmt.Errorf("%s_must_be_host_address", field)
	}

	switch family {
	case "inet":
		if isV6 || isV6CIDR {
			return fmt.Errorf("incompatible_family_for_%s: expected_ipv4", field)
		}
	case "inet6":
		if isV4 || isV4CIDR {
			return fmt.Errorf("incompatible_family_for_%s: expected_ipv6", field)
		}
	}

	return nil
}

func hasPortSelector(raw string, objID *uint) bool {
	return strings.TrimSpace(raw) != "" || (objID != nil && *objID > 0)
}

func validateRawPortSelector(raw string, field string) error {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return nil
	}

	if strings.HasPrefix(trimmed, "{") && strings.HasSuffix(trimmed, "}") {
		trimmed = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(trimmed, "{"), "}"))
	}

	tokens := strings.Split(trimmed, ",")
	for _, token := range tokens {
		part := strings.TrimSpace(token)
		if part == "" {
			return fmt.Errorf("invalid_%s_port_selector: empty_token", field)
		}
		if !parsePortValue(part) {
			return fmt.Errorf("invalid_%s_port_selector: %s", field, part)
		}
	}

	return nil
}

func (s *Service) validateFirewallHostObjectRef(id *uint, field string) error {
	if id == nil || *id == 0 {
		return nil
	}

	var object networkModels.Object
	if err := s.DB.Select("id,type").First(&object, *id).Error; err != nil {
		return fmt.Errorf("invalid_object_ref_for_%s: %w", field, err)
	}

	switch object.Type {
	case "Host", "FQDN":
		return nil
	default:
		return fmt.Errorf("invalid_object_type_for_%s: %s", field, object.Type)
	}
}

func (s *Service) validateFirewallTrafficRuleRequest(req *networkServiceInterfaces.UpsertFirewallTrafficRuleRequest) error {
	direction := normalizeDirection(req.Direction)
	family := normalizeFamily(req.Family)
	protocol := normalizeProtocol(req.Protocol)
	ingress := normalizeInterfaceList(req.IngressInterfaces)
	egress := normalizeInterfaceList(req.EgressInterfaces)

	switch direction {
	case "in":
		if len(egress) > 0 {
			return fmt.Errorf("in_direction_rejects_egress_interfaces")
		}
	case "out":
		if len(ingress) > 0 {
			return fmt.Errorf("out_direction_rejects_ingress_interfaces")
		}
	}

	if err := validateFamilyAgainstRawAddress(req.SourceRaw, family, true, "source_raw", true); err != nil {
		return err
	}
	if err := validateFamilyAgainstRawAddress(req.DestRaw, family, true, "dest_raw", true); err != nil {
		return err
	}

	if protocol != "tcp" && protocol != "udp" {
		if hasPortSelector(req.SrcPortsRaw, req.SrcPortObjID) || hasPortSelector(req.DstPortsRaw, req.DstPortObjID) {
			return fmt.Errorf("ports_require_tcp_or_udp_protocol")
		}
	} else {
		if err := validateRawPortSelector(req.SrcPortsRaw, "src_ports_raw"); err != nil {
			return err
		}
		if err := validateRawPortSelector(req.DstPortsRaw, "dst_ports_raw"); err != nil {
			return err
		}
	}

	return nil
}

func (s *Service) validateFirewallNATRuleRequest(req *networkServiceInterfaces.UpsertFirewallNATRuleRequest) error {
	natType := normalizeNATType(req.NATType)
	family := normalizeFamily(req.Family)
	protocol := normalizeProtocol(req.Protocol)
	ingress := normalizeInterfaceList(req.IngressInterfaces)
	egress := normalizeInterfaceList(req.EgressInterfaces)
	translateMode := normalizeTranslateMode(req.TranslateMode)
	policyRoutingEnabled := req.PolicyRoutingEnabled != nil && *req.PolicyRoutingEnabled
	policyRouteGateway := strings.TrimSpace(req.PolicyRouteGateway)

	if err := validateFamilyAgainstRawAddress(req.SourceRaw, family, true, "source_raw", true); err != nil {
		return err
	}
	if err := validateFamilyAgainstRawAddress(req.DestRaw, family, true, "dest_raw", true); err != nil {
		return err
	}
	if err := validateFamilyAgainstRawAddress(req.TranslateToRaw, family, false, "translate_to_raw", false); err != nil {
		return err
	}
	if err := validateFamilyAgainstRawAddress(req.DNATTargetRaw, family, false, "dnat_target_raw", false); err != nil {
		return err
	}

	if err := s.validateFirewallAddressObjectRef(req.SourceObjID); err != nil {
		return err
	}
	if err := s.validateFirewallAddressObjectRef(req.DestObjID); err != nil {
		return err
	}
	if err := s.validateFirewallHostObjectRef(req.TranslateToObjID, "translate_to_obj"); err != nil {
		return err
	}
	if err := s.validateFirewallHostObjectRef(req.DNATTargetObjID, "dnat_target_obj"); err != nil {
		return err
	}
	if err := s.validateFirewallPortObjectRef(req.DstPortObjID); err != nil {
		return err
	}
	if err := s.validateFirewallPortObjectRef(req.RedirectPortObjID); err != nil {
		return err
	}

	hasDNATMatchPort := hasPortSelector(req.DstPortsRaw, req.DstPortObjID)
	hasDNATRewritePort := hasPortSelector(req.RedirectPortsRaw, req.RedirectPortObjID)
	if err := validateRawPortSelector(req.DstPortsRaw, "dst_ports_raw"); err != nil {
		return err
	}
	if err := validateRawPortSelector(req.RedirectPortsRaw, "redirect_ports_raw"); err != nil {
		return err
	}
	if (hasDNATMatchPort || hasDNATRewritePort) && protocol != "tcp" && protocol != "udp" {
		return fmt.Errorf("dnat_ports_require_tcp_or_udp_protocol")
	}
	if hasDNATRewritePort && !hasDNATMatchPort {
		return fmt.Errorf("redirect_port_requires_destination_port_match")
	}

	switch natType {
	case "snat", "binat":
		if len(egress) == 0 {
			if policyRoutingEnabled {
				return fmt.Errorf("policy_routing_requires_exactly_one_egress_interface")
			}
			return fmt.Errorf("%s_requires_egress_interface", natType)
		}
		if len(ingress) > 0 && !policyRoutingEnabled {
			return fmt.Errorf("%s_ingress_interfaces_require_policy_routing", natType)
		}
		if hasSelector(req.DNATTargetRaw, req.DNATTargetObjID) ||
			hasPortSelector(req.DstPortsRaw, req.DstPortObjID) ||
			hasPortSelector(req.RedirectPortsRaw, req.RedirectPortObjID) {
			return fmt.Errorf("%s_rejects_dnat_only_fields", natType)
		}

		if translateMode == "interface" {
			if hasSelector(req.TranslateToRaw, req.TranslateToObjID) {
				return fmt.Errorf("translate_to_fields_not_allowed_for_translate_mode_interface")
			}
		} else {
			if !hasSelector(req.TranslateToRaw, req.TranslateToObjID) {
				return fmt.Errorf("translate_mode_address_requires_translate_target")
			}
			if strings.TrimSpace(req.TranslateToRaw) != "" && req.TranslateToObjID != nil {
				return fmt.Errorf("translate_to_raw_and_translate_to_obj_are_mutually_exclusive")
			}
		}

		if policyRoutingEnabled {
			if len(egress) != 1 {
				return fmt.Errorf("policy_routing_requires_exactly_one_egress_interface")
			}
			if policyRouteGateway == "" {
				return fmt.Errorf("policy_route_gateway_required_when_policy_routing_enabled")
			}
			if family != "inet" && family != "inet6" {
				return fmt.Errorf("policy_route_gateway_requires_explicit_family")
			}
			if err := validateFamilyAgainstRawAddress(policyRouteGateway, family, false, "policy_route_gateway", false); err != nil {
				return err
			}
		}
	case "dnat":
		if len(ingress) == 0 {
			return fmt.Errorf("dnat_requires_ingress_interface")
		}
		if len(egress) > 0 {
			return fmt.Errorf("dnat_rejects_egress_interfaces")
		}
		if policyRoutingEnabled {
			return fmt.Errorf("dnat_rejects_policy_routing")
		}
		if strings.TrimSpace(req.TranslateMode) != "" {
			return fmt.Errorf("dnat_rejects_translate_mode")
		}
		if hasSelector(req.TranslateToRaw, req.TranslateToObjID) {
			return fmt.Errorf("dnat_rejects_snat_translation_fields")
		}
		if !hasSelector(req.DNATTargetRaw, req.DNATTargetObjID) {
			return fmt.Errorf("dnat_requires_target_host")
		}
		if strings.TrimSpace(req.DNATTargetRaw) != "" && req.DNATTargetObjID != nil {
			return fmt.Errorf("dnat_target_raw_and_dnat_target_obj_are_mutually_exclusive")
		}
	default:
		return fmt.Errorf("invalid_nat_type: %s", natType)
	}

	return nil
}

func (s *Service) CreateFirewallTrafficRule(req *networkServiceInterfaces.UpsertFirewallTrafficRuleRequest) (uint, error) {
	if err := s.validateFirewallTrafficRuleRequest(req); err != nil {
		return 0, err
	}
	if err := s.validateFirewallAddressObjectRef(req.SourceObjID); err != nil {
		return 0, err
	}
	if err := s.validateFirewallAddressObjectRef(req.DestObjID); err != nil {
		return 0, err
	}
	if err := s.validateFirewallPortObjectRef(req.SrcPortObjID); err != nil {
		return 0, err
	}
	if err := s.validateFirewallPortObjectRef(req.DstPortObjID); err != nil {
		return 0, err
	}

	priority := defaultFirewallPriority
	if req.Priority != nil {
		priority = normalizePriority(*req.Priority)
	} else {
		nextPriority, err := s.nextFirewallTrafficPriority()
		if err != nil {
			return 0, err
		}
		priority = nextPriority
	}

	enabled := true
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	logEnabled := false
	if req.Log != nil {
		logEnabled = *req.Log
	}
	quick := false
	if req.Quick != nil {
		quick = *req.Quick
	}

	rule := networkModels.FirewallTrafficRule{
		Name:              strings.TrimSpace(req.Name),
		Description:       strings.TrimSpace(req.Description),
		Visible:           true,
		Enabled:           enabled,
		Log:               logEnabled,
		Quick:             quick,
		Priority:          priority,
		Action:            strings.TrimSpace(strings.ToLower(req.Action)),
		Direction:         normalizeDirection(req.Direction),
		Protocol:          normalizeProtocol(req.Protocol),
		IngressInterfaces: normalizeInterfaceList(req.IngressInterfaces),
		EgressInterfaces:  normalizeInterfaceList(req.EgressInterfaces),
		Family:            normalizeFamily(req.Family),
		SourceRaw:         normalizeFirewallRequestStrings(req.SourceRaw),
		SourceObjID:       req.SourceObjID,
		DestRaw:           normalizeFirewallRequestStrings(req.DestRaw),
		DestObjID:         req.DestObjID,
		SrcPortsRaw:       normalizeFirewallRequestStrings(req.SrcPortsRaw),
		SrcPortObjID:      req.SrcPortObjID,
		DstPortsRaw:       normalizeFirewallRequestStrings(req.DstPortsRaw),
		DstPortObjID:      req.DstPortObjID,
	}

	prioritySnapshot, err := snapshotTrafficPriorities(s.DB)
	if err != nil {
		return 0, err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		maxHidden, maxHiddenErr := s.maxHiddenTrafficPriority(tx)
		if maxHiddenErr != nil {
			return maxHiddenErr
		}
		targetPriority := priority
		if targetPriority <= maxHidden {
			targetPriority = maxHidden + 1
		}
		rule.Priority = targetPriority
		if shiftErr := s.shiftTrafficRulesDownFrom(tx, targetPriority, 0); shiftErr != nil {
			return shiftErr
		}
		return tx.Create(&rule).Error
	}); err != nil {
		return 0, err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			if deleteErr := tx.Delete(&networkModels.FirewallTrafficRule{}, rule.ID).Error; deleteErr != nil {
				return deleteErr
			}
			return restoreTrafficPriorities(tx, prioritySnapshot)
		})
		return 0, err
	}

	return rule.ID, nil
}

func (s *Service) EditFirewallTrafficRule(id uint, req *networkServiceInterfaces.UpsertFirewallTrafficRuleRequest) error {
	if err := s.validateFirewallTrafficRuleRequest(req); err != nil {
		return err
	}
	if err := s.validateFirewallAddressObjectRef(req.SourceObjID); err != nil {
		return err
	}
	if err := s.validateFirewallAddressObjectRef(req.DestObjID); err != nil {
		return err
	}
	if err := s.validateFirewallPortObjectRef(req.SrcPortObjID); err != nil {
		return err
	}
	if err := s.validateFirewallPortObjectRef(req.DstPortObjID); err != nil {
		return err
	}

	var current networkModels.FirewallTrafficRule
	if err := s.DB.First(&current, id).Error; err != nil {
		return err
	}
	if !current.Visible {
		return fmt.Errorf(errHiddenFirewallRuleMutation)
	}

	previous := current
	previous.IngressInterfaces = append([]string(nil), current.IngressInterfaces...)
	previous.EgressInterfaces = append([]string(nil), current.EgressInterfaces...)

	targetPriority := current.Priority
	if req.Priority != nil {
		targetPriority = normalizePriority(*req.Priority)
	}
	if req.Enabled != nil {
		current.Enabled = *req.Enabled
	}
	if req.Log != nil {
		current.Log = *req.Log
	}
	if req.Quick != nil {
		current.Quick = *req.Quick
	}

	current.Name = strings.TrimSpace(req.Name)
	current.Description = strings.TrimSpace(req.Description)
	current.Action = strings.TrimSpace(strings.ToLower(req.Action))
	current.Direction = normalizeDirection(req.Direction)
	current.Protocol = normalizeProtocol(req.Protocol)
	current.IngressInterfaces = normalizeInterfaceList(req.IngressInterfaces)
	current.EgressInterfaces = normalizeInterfaceList(req.EgressInterfaces)
	current.Family = normalizeFamily(req.Family)
	current.SourceRaw = normalizeFirewallRequestStrings(req.SourceRaw)
	current.SourceObjID = req.SourceObjID
	current.DestRaw = normalizeFirewallRequestStrings(req.DestRaw)
	current.DestObjID = req.DestObjID
	current.SrcPortsRaw = normalizeFirewallRequestStrings(req.SrcPortsRaw)
	current.SrcPortObjID = req.SrcPortObjID
	current.DstPortsRaw = normalizeFirewallRequestStrings(req.DstPortsRaw)
	current.DstPortObjID = req.DstPortObjID

	prioritySnapshot, err := snapshotTrafficPriorities(s.DB)
	if err != nil {
		return err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		maxHidden, maxHiddenErr := s.maxHiddenTrafficPriority(tx)
		if maxHiddenErr != nil {
			return maxHiddenErr
		}
		if targetPriority <= maxHidden {
			targetPriority = maxHidden + 1
		}
		if moveErr := s.moveTrafficRulePriority(tx, current.ID, current.Priority, targetPriority); moveErr != nil {
			return moveErr
		}
		current.Priority = targetPriority
		return tx.Save(&current).Error
	}); err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			if saveErr := tx.Save(&previous).Error; saveErr != nil {
				return saveErr
			}
			return restoreTrafficPriorities(tx, prioritySnapshot)
		})
		return err
	}

	return nil
}

func (s *Service) DeleteFirewallTrafficRule(id uint) error {
	var rule networkModels.FirewallTrafficRule
	if err := s.DB.First(&rule, id).Error; err != nil {
		return err
	}
	if !rule.Visible {
		return fmt.Errorf(errHiddenFirewallRuleMutation)
	}

	if err := s.DB.Delete(&rule).Error; err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Create(&rule).Error
		return err
	}

	return nil
}

func (s *Service) ReorderFirewallTrafficRules(req []networkServiceInterfaces.FirewallReorderRequest) error {
	if len(req) == 0 {
		return nil
	}

	ids := make([]uint, 0, len(req))
	seen := make(map[uint]struct{}, len(req))
	for _, item := range req {
		if item.ID == 0 {
			return fmt.Errorf("invalid_rule_id")
		}
		if _, ok := seen[item.ID]; ok {
			return fmt.Errorf("duplicate_rule_id: %d", item.ID)
		}
		seen[item.ID] = struct{}{}
		ids = append(ids, item.ID)
	}

	var existing []networkModels.FirewallTrafficRule
	if err := s.DB.Select("id,priority,visible").Where("id IN ?", ids).Find(&existing).Error; err != nil {
		return err
	}
	if len(existing) != len(ids) {
		return fmt.Errorf("some_firewall_traffic_rules_not_found")
	}

	previous := make(map[uint]int, len(existing))
	for _, rule := range existing {
		if !rule.Visible {
			return fmt.Errorf(errHiddenFirewallRuleMutation)
		}
		previous[rule.ID] = rule.Priority
	}

	seenPriorities := make(map[int]struct{}, len(req))
	for _, item := range req {
		p := normalizePriority(item.Priority)
		if _, ok := seenPriorities[p]; ok {
			return fmt.Errorf("duplicate_priority_in_reorder_request: %d", p)
		}
		seenPriorities[p] = struct{}{}
	}

	maxHidden, err := s.maxHiddenTrafficPriority(s.DB)
	if err != nil {
		return err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		for _, item := range req {
			targetPriority := normalizePriority(item.Priority) + maxHidden
			if err := tx.Model(&networkModels.FirewallTrafficRule{}).Where("id = ?", item.ID).Update("priority", targetPriority).Error; err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			for id, priority := range previous {
				if updateErr := tx.Model(&networkModels.FirewallTrafficRule{}).Where("id = ?", id).Update("priority", priority).Error; updateErr != nil {
					return updateErr
				}
			}
			return nil
		})
		return err
	}

	return nil
}

func (s *Service) CreateFirewallNATRule(req *networkServiceInterfaces.UpsertFirewallNATRuleRequest) (uint, error) {
	if err := s.validateFirewallNATRuleRequest(req); err != nil {
		return 0, err
	}

	priority := defaultFirewallPriority
	if req.Priority != nil {
		priority = normalizePriority(*req.Priority)
	} else {
		nextPriority, err := s.nextFirewallNATPriority()
		if err != nil {
			return 0, err
		}
		priority = nextPriority
	}

	enabled := true
	if req.Enabled != nil {
		enabled = *req.Enabled
	}
	logEnabled := false
	if req.Log != nil {
		logEnabled = *req.Log
	}

	rule := networkModels.FirewallNATRule{
		Name:                 strings.TrimSpace(req.Name),
		Description:          strings.TrimSpace(req.Description),
		Visible:              true,
		Enabled:              enabled,
		Log:                  logEnabled,
		Priority:             priority,
		NATType:              normalizeNATType(req.NATType),
		PolicyRoutingEnabled: req.PolicyRoutingEnabled != nil && *req.PolicyRoutingEnabled,
		PolicyRouteGateway:   "",
		IngressInterfaces:    normalizeInterfaceList(req.IngressInterfaces),
		EgressInterfaces:     normalizeInterfaceList(req.EgressInterfaces),
		Family:               normalizeFamily(req.Family),
		Protocol:             normalizeProtocol(req.Protocol),
		SourceRaw:            normalizeFirewallRequestStrings(req.SourceRaw),
		SourceObjID:          req.SourceObjID,
		DestRaw:              normalizeFirewallRequestStrings(req.DestRaw),
		DestObjID:            req.DestObjID,
		TranslateMode:        normalizeTranslateMode(req.TranslateMode),
		TranslateToRaw:       normalizeFirewallRequestStrings(req.TranslateToRaw),
		TranslateToObjID:     req.TranslateToObjID,
		DNATTargetRaw:        normalizeFirewallRequestStrings(req.DNATTargetRaw),
		DNATTargetObjID:      req.DNATTargetObjID,
		DstPortsRaw:          normalizeFirewallRequestStrings(req.DstPortsRaw),
		DstPortObjID:         req.DstPortObjID,
		RedirectPortsRaw:     normalizeFirewallRequestStrings(req.RedirectPortsRaw),
		RedirectPortObjID:    req.RedirectPortObjID,
	}
	if rule.PolicyRoutingEnabled {
		rule.PolicyRouteGateway = normalizeFirewallRequestStrings(req.PolicyRouteGateway)
	}

	prioritySnapshot, err := snapshotNATPriorities(s.DB)
	if err != nil {
		return 0, err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		maxHidden, maxHiddenErr := s.maxHiddenNATPriority(tx)
		if maxHiddenErr != nil {
			return maxHiddenErr
		}
		targetPriority := priority
		if targetPriority <= maxHidden {
			targetPriority = maxHidden + 1
		}
		rule.Priority = targetPriority
		if shiftErr := s.shiftNATRulesDownFrom(tx, targetPriority, 0); shiftErr != nil {
			return shiftErr
		}
		return tx.Create(&rule).Error
	}); err != nil {
		return 0, err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			if deleteErr := tx.Delete(&networkModels.FirewallNATRule{}, rule.ID).Error; deleteErr != nil {
				return deleteErr
			}
			return restoreNATPriorities(tx, prioritySnapshot)
		})
		return 0, err
	}

	return rule.ID, nil
}

func (s *Service) EditFirewallNATRule(id uint, req *networkServiceInterfaces.UpsertFirewallNATRuleRequest) error {
	if err := s.validateFirewallNATRuleRequest(req); err != nil {
		return err
	}

	var current networkModels.FirewallNATRule
	if err := s.DB.First(&current, id).Error; err != nil {
		return err
	}
	if !current.Visible {
		return fmt.Errorf(errHiddenFirewallRuleMutation)
	}

	previous := current
	previous.IngressInterfaces = append([]string(nil), current.IngressInterfaces...)
	previous.EgressInterfaces = append([]string(nil), current.EgressInterfaces...)

	targetPriority := current.Priority
	if req.Priority != nil {
		targetPriority = normalizePriority(*req.Priority)
	}
	if req.Enabled != nil {
		current.Enabled = *req.Enabled
	}
	if req.Log != nil {
		current.Log = *req.Log
	}

	current.Name = strings.TrimSpace(req.Name)
	current.Description = strings.TrimSpace(req.Description)
	current.NATType = normalizeNATType(req.NATType)
	current.IngressInterfaces = normalizeInterfaceList(req.IngressInterfaces)
	current.EgressInterfaces = normalizeInterfaceList(req.EgressInterfaces)
	current.Family = normalizeFamily(req.Family)
	current.Protocol = normalizeProtocol(req.Protocol)
	current.SourceRaw = normalizeFirewallRequestStrings(req.SourceRaw)
	current.SourceObjID = req.SourceObjID
	current.DestRaw = normalizeFirewallRequestStrings(req.DestRaw)
	current.DestObjID = req.DestObjID
	current.TranslateMode = normalizeTranslateMode(req.TranslateMode)
	current.TranslateToRaw = normalizeFirewallRequestStrings(req.TranslateToRaw)
	current.TranslateToObjID = req.TranslateToObjID
	current.DNATTargetRaw = normalizeFirewallRequestStrings(req.DNATTargetRaw)
	current.DNATTargetObjID = req.DNATTargetObjID
	current.DstPortsRaw = normalizeFirewallRequestStrings(req.DstPortsRaw)
	current.DstPortObjID = req.DstPortObjID
	current.RedirectPortsRaw = normalizeFirewallRequestStrings(req.RedirectPortsRaw)
	current.RedirectPortObjID = req.RedirectPortObjID
	current.PolicyRoutingEnabled = req.PolicyRoutingEnabled != nil && *req.PolicyRoutingEnabled
	current.PolicyRouteGateway = ""
	if current.PolicyRoutingEnabled {
		current.PolicyRouteGateway = normalizeFirewallRequestStrings(req.PolicyRouteGateway)
	}

	prioritySnapshot, err := snapshotNATPriorities(s.DB)
	if err != nil {
		return err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		maxHidden, maxHiddenErr := s.maxHiddenNATPriority(tx)
		if maxHiddenErr != nil {
			return maxHiddenErr
		}
		if targetPriority <= maxHidden {
			targetPriority = maxHidden + 1
		}
		if moveErr := s.moveNATRulePriority(tx, current.ID, current.Priority, targetPriority); moveErr != nil {
			return moveErr
		}
		current.Priority = targetPriority
		return tx.Save(&current).Error
	}); err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			if saveErr := tx.Save(&previous).Error; saveErr != nil {
				return saveErr
			}
			return restoreNATPriorities(tx, prioritySnapshot)
		})
		return err
	}

	return nil
}

func (s *Service) DeleteFirewallNATRule(id uint) error {
	var rule networkModels.FirewallNATRule
	if err := s.DB.First(&rule, id).Error; err != nil {
		return err
	}
	if !rule.Visible {
		return fmt.Errorf(errHiddenFirewallRuleMutation)
	}

	if err := s.DB.Delete(&rule).Error; err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Create(&rule).Error
		return err
	}

	return nil
}

func (s *Service) ReorderFirewallNATRules(req []networkServiceInterfaces.FirewallReorderRequest) error {
	if len(req) == 0 {
		return nil
	}

	ids := make([]uint, 0, len(req))
	seen := make(map[uint]struct{}, len(req))
	for _, item := range req {
		if item.ID == 0 {
			return fmt.Errorf("invalid_rule_id")
		}
		if _, ok := seen[item.ID]; ok {
			return fmt.Errorf("duplicate_rule_id: %d", item.ID)
		}
		seen[item.ID] = struct{}{}
		ids = append(ids, item.ID)
	}

	var existing []networkModels.FirewallNATRule
	if err := s.DB.Select("id,priority,visible").Where("id IN ?", ids).Find(&existing).Error; err != nil {
		return err
	}
	if len(existing) != len(ids) {
		return fmt.Errorf("some_firewall_nat_rules_not_found")
	}

	previous := make(map[uint]int, len(existing))
	for _, rule := range existing {
		if !rule.Visible {
			return fmt.Errorf(errHiddenFirewallRuleMutation)
		}
		previous[rule.ID] = rule.Priority
	}

	seenPriorities := make(map[int]struct{}, len(req))
	for _, item := range req {
		p := normalizePriority(item.Priority)
		if _, ok := seenPriorities[p]; ok {
			return fmt.Errorf("duplicate_priority_in_reorder_request: %d", p)
		}
		seenPriorities[p] = struct{}{}
	}

	maxHidden, err := s.maxHiddenNATPriority(s.DB)
	if err != nil {
		return err
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		for _, item := range req {
			targetPriority := normalizePriority(item.Priority) + maxHidden
			if err := tx.Model(&networkModels.FirewallNATRule{}).Where("id = ?", item.ID).Update("priority", targetPriority).Error; err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Transaction(func(tx *gorm.DB) error {
			for id, priority := range previous {
				if updateErr := tx.Model(&networkModels.FirewallNATRule{}).Where("id = ?", id).Update("priority", priority).Error; updateErr != nil {
					return updateErr
				}
			}
			return nil
		})
		return err
	}

	return nil
}

func (s *Service) UpdateFirewallAdvancedSettings(req *networkServiceInterfaces.FirewallAdvancedRequest) error {
	current, err := s.GetFirewallAdvancedSettings()
	if err != nil {
		return err
	}

	previous := *current
	current.PreRules = strings.TrimSpace(req.PreRules)
	current.PostRules = strings.TrimSpace(req.PostRules)

	if err := s.DB.Save(current).Error; err != nil {
		return err
	}

	if err := s.ApplyFirewallIfEnabled(); err != nil {
		_ = s.DB.Save(&previous).Error
		return err
	}

	return nil
}

func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, ".sylve-pf-*")
	if err != nil {
		return err
	}

	tmpName := tmp.Name()
	defer func() {
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}

	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}

	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}

	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpName, path)
}

func (s *Service) getDefaultRouteInterface() string {
	out, err := utils.RunCommand("/usr/sbin/route", "-n", "get", "default")
	if err != nil {
		return ""
	}

	lines := strings.Split(out, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface:") {
			return strings.TrimSpace(strings.TrimPrefix(line, "interface:"))
		}
	}

	return ""
}

func (s *Service) isPFEnabled() bool {
	out, err := firewallRunCommand("/sbin/pfctl", "-si")
	if err != nil {
		return false
	}
	return strings.Contains(strings.ToLower(out), "status: enabled")
}

func (s *Service) ensurePFKernelModuleLoaded() error {
	if _, err := firewallRunCommand("/sbin/kldstat", "-m", "pf"); err == nil {
		return nil
	}

	if _, err := firewallRunCommand("/sbin/kldload", "-n", "pf"); err != nil {
		lowered := strings.ToLower(err.Error())
		if strings.Contains(lowered, "already loaded") ||
			strings.Contains(lowered, "in kernel") ||
			strings.Contains(lowered, "file exists") {
			return nil
		}
		return fmt.Errorf("failed_to_load_pf_kernel_module: %w", err)
	}

	return nil
}

func (s *Service) ensurePFBackup() error {
	backupExists, err := utils.FileExists(pfBackupConfPath)
	if err != nil && !strings.Contains(strings.ToLower(err.Error()), "does not exist") {
		return err
	}
	if backupExists {
		return nil
	}

	currentExists, err := utils.FileExists(pfMainConfPath)
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "does not exist") {
			return nil
		}
		return err
	}
	if !currentExists {
		return nil
	}

	return utils.CopyFile(pfMainConfPath, pfBackupConfPath)
}

func (s *Service) ApplyFirewallConfig() error {
	s.firewallMutex.Lock()
	defer s.firewallMutex.Unlock()

	if err := s.ensurePFAutostartDisabledInRCConf(); err != nil {
		return err
	}

	if err := s.ensurePFKernelModuleLoaded(); err != nil {
		return err
	}

	if err := s.ensureDefaultAllowTrafficRules(); err != nil {
		return err
	}

	advanced, err := s.GetFirewallAdvancedSettings()
	if err != nil {
		return err
	}

	natRules, err := s.getFirewallNATRulesForApply()
	if err != nil {
		return err
	}

	trafficRules, err := s.getFirewallTrafficRulesForApply()
	if err != nil {
		return err
	}

	objectTables, err := s.buildFirewallObjectTables(trafficRules, natRules)
	if err != nil {
		return err
	}
	objectTablesRendered := renderFirewallObjectTables(objectTables)

	natRendered, err := s.renderNATRules(natRules, objectTables)
	if err != nil {
		return err
	}

	natPolicyRoutingRendered, err := s.renderNATPolicyRoutingRules(natRules, objectTables)
	if err != nil {
		return err
	}

	trafficRendered, err := s.renderTrafficRules(trafficRules, objectTables)
	if err != nil {
		return err
	}
	if strings.TrimSpace(natPolicyRoutingRendered) != "" {
		if strings.TrimSpace(trafficRendered) != "" {
			trafficRendered = strings.TrimRight(natPolicyRoutingRendered, "\n") + "\n" + trafficRendered
		} else {
			trafficRendered = natPolicyRoutingRendered
		}
	}

	tmpDir, err := os.MkdirTemp("", "sylve-pf-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	tmpSylveDir := filepath.Join(tmpDir, "pf.sylve")
	if err := os.MkdirAll(tmpSylveDir, 0755); err != nil {
		return err
	}

	tmpObjectTablesPath := filepath.Join(tmpSylveDir, "object-tables.conf")
	tmpNatPath := filepath.Join(tmpSylveDir, "nat-rules.conf")
	tmpTrafficPath := filepath.Join(tmpSylveDir, "traffic-rules.conf")
	tmpMainPath := filepath.Join(tmpDir, "pf.conf")

	if err := os.WriteFile(tmpObjectTablesPath, []byte(objectTablesRendered), 0644); err != nil {
		return err
	}

	if err := os.WriteFile(tmpNatPath, []byte(natRendered), 0644); err != nil {
		return err
	}

	if err := os.WriteFile(tmpTrafficPath, []byte(trafficRendered), 0644); err != nil {
		return err
	}

	mainCandidate := buildPFMainConfig(advanced.PreRules, advanced.PostRules, tmpObjectTablesPath, tmpNatPath, tmpTrafficPath)
	if err := os.WriteFile(tmpMainPath, []byte(mainCandidate), 0644); err != nil {
		return err
	}

	if _, err := firewallRunCommand("/sbin/pfctl", "-nf", tmpMainPath); err != nil {
		return formatPFValidationError(err, map[string]string{
			"pf.conf":            mainCandidate,
			"object-tables.conf": objectTablesRendered,
			"nat-rules.conf":     natRendered,
			"traffic-rules.conf": trafficRendered,
		})
	}

	if err := s.ensurePFBackup(); err != nil {
		return err
	}

	if err := os.MkdirAll(pfSylveDir, 0755); err != nil {
		return err
	}

	finalMain := buildPFMainConfig(advanced.PreRules, advanced.PostRules, pfObjectTablesPath, pfNatRulesPath, pfTrafficRulesPath)

	if err := atomicWriteFile(pfObjectTablesPath, []byte(objectTablesRendered), 0644); err != nil {
		return err
	}
	if err := atomicWriteFile(pfNatRulesPath, []byte(natRendered), 0644); err != nil {
		return err
	}
	if err := atomicWriteFile(pfTrafficRulesPath, []byte(trafficRendered), 0644); err != nil {
		return err
	}
	if err := atomicWriteFile(pfMainConfPath, []byte(finalMain), 0644); err != nil {
		return err
	}

	s.flushFirewallCounterDeltas()
	s.updateFirewallRuleNames()

	if s.isPFEnabled() {
		if err := system.ServiceAction("pf", "onereload"); err != nil {
			return err
		}
		return nil
	}

	return system.ServiceAction("pf", "onestart")
}

func extractCommandOutput(raw string) string {
	lowered := strings.ToLower(raw)
	index := strings.Index(lowered, "output:")
	if index == -1 {
		return strings.TrimSpace(raw)
	}
	return strings.TrimSpace(raw[index+len("output:"):])
}

func sourceLineAt(content string, lineNumber int) string {
	if lineNumber <= 0 {
		return ""
	}
	lines := strings.Split(content, "\n")
	if lineNumber > len(lines) {
		return ""
	}
	return strings.TrimSpace(lines[lineNumber-1])
}

func pfValidationHint(path string, message string, line string) string {
	loweredMessage := strings.ToLower(message)
	loweredLine := strings.ToLower(line)
	base := filepath.Base(path)

	if strings.Contains(loweredMessage, "rules must be in order") && base == "pf.conf" {
		return "check pf.conf statement order: options -> normalization -> queueing -> translation -> filtering"
	}
	if strings.Contains(loweredLine, "received-on") {
		return "received-on is not valid in this generated filter rule; use direction-specific on <interface> matching"
	}
	if strings.Contains(loweredMessage, "rule expands to no valid combination") {
		return "rule selectors/family likely conflict (for example IPv6 source with inet family)"
	}
	return ""
}

func formatPFValidationError(err error, candidates map[string]string) error {
	output := extractCommandOutput(err.Error())
	lines := strings.Split(output, "\n")
	details := make([]string, 0, len(lines))
	hints := make([]string, 0, len(lines))
	hasContext := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}

		match := pfValidationLinePattern.FindStringSubmatch(trimmed)
		if len(match) != 4 {
			details = append(details, trimmed)
			continue
		}

		filePath := match[1]
		lineNumber, convErr := strconv.Atoi(match[2])
		message := match[3]
		if convErr != nil {
			details = append(details, trimmed)
			continue
		}

		base := filepath.Base(filePath)
		context := sourceLineAt(candidates[base], lineNumber)
		if context != "" {
			hasContext = true
			details = append(details, fmt.Sprintf("%s:%d: %s (rule: %s)", base, lineNumber, message, context))
		} else {
			details = append(details, fmt.Sprintf("%s:%d: %s", base, lineNumber, message))
		}

		if hint := pfValidationHint(filePath, message, context); hint != "" {
			hints = append(hints, hint)
		}
	}

	detailText := strings.Join(details, "; ")
	hints = uniqueSortedValues(hints)
	if len(hints) == 0 {
		if hasContext {
			return fmt.Errorf("pf_validation_failed: %s", detailText)
		}
		return fmt.Errorf("pf_validation_failed: %s", output)
	}

	return fmt.Errorf("pf_validation_failed: %s | hint: %s", detailText, strings.Join(hints, " | "))
}

func buildPFMainConfig(preRules string, postRules string, objectTablesPath string, natPath string, trafficPath string) string {
	var b strings.Builder
	b.WriteString(pfManagedHeader)
	b.WriteString("\n\n")

	if strings.TrimSpace(preRules) != "" {
		b.WriteString("# --- sylve: pre rules ---\n")
		b.WriteString(strings.TrimSpace(preRules))
		b.WriteString("\n\n")
	}

	b.WriteString("nat-anchor \"sylve/nat-rules\" all\n")
	b.WriteString("rdr-anchor \"sylve/nat-rules\" all\n")
	b.WriteString("binat-anchor \"sylve/nat-rules\" all\n")
	b.WriteString("anchor \"sylve/nat-rules\"\n")
	b.WriteString(fmt.Sprintf("load anchor \"sylve/nat-rules\" from \"%s\"\n\n", natPath))

	b.WriteString("anchor \"sylve/object-tables\"\n")
	b.WriteString(fmt.Sprintf("load anchor \"sylve/object-tables\" from \"%s\"\n\n", objectTablesPath))

	b.WriteString("anchor \"sylve/traffic-rules\"\n")
	b.WriteString(fmt.Sprintf("load anchor \"sylve/traffic-rules\" from \"%s\"\n", trafficPath))

	if strings.TrimSpace(postRules) != "" {
		b.WriteString("\n# --- sylve: post rules ---\n")
		b.WriteString(strings.TrimSpace(postRules))
		b.WriteString("\n")
	}

	return b.String()
}

func compactPFList(values []string) string {
	switch len(values) {
	case 0:
		return ""
	case 1:
		return values[0]
	default:
		return "{ " + strings.Join(values, ", ") + " }"
	}
}

func splitByFamily(values []string) (v4 []string, v6 []string, other []string) {
	for _, value := range values {
		v := strings.TrimSpace(value)
		if v == "" {
			continue
		}

		switch {
		case utils.IsValidIPv4(v), utils.IsValidIPv4CIDR(v):
			v4 = append(v4, v)
		case utils.IsValidIPv6(v), utils.IsValidIPv6CIDR(v):
			v6 = append(v6, v)
		default:
			other = append(other, v)
		}
	}
	return v4, v6, other
}

type firewallObjectTable struct {
	ObjectID    uint
	ObjectName  string
	InetName    string
	InetValues  []string
	Inet6Name   string
	Inet6Values []string
}

func firewallObjectTableName(objectID uint, family string) string {
	return fmt.Sprintf("sylve_obj_%d_%s", objectID, family)
}

func uniqueSortedValues(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		v := strings.TrimSpace(value)
		if v == "" {
			continue
		}
		if _, ok := seen[v]; ok {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func (s *Service) buildFirewallObjectTables(trafficRules []networkModels.FirewallTrafficRule, natRules []networkModels.FirewallNATRule) (map[uint]firewallObjectTable, error) {
	objects := make(map[uint]*networkModels.Object)
	addObject := func(obj *networkModels.Object) {
		if obj == nil || obj.ID == 0 {
			return
		}
		if _, exists := objects[obj.ID]; exists {
			return
		}
		objects[obj.ID] = obj
	}

	for _, rule := range trafficRules {
		if !rule.Enabled {
			continue
		}
		addObject(rule.SourceObj)
		addObject(rule.DestObj)
	}
	for _, rule := range natRules {
		if !rule.Enabled {
			continue
		}
		addObject(rule.SourceObj)
		addObject(rule.DestObj)
	}

	dynamicValuesByObject, err := s.loadDynamicValuesForObjects(objects)
	if err != nil {
		return nil, err
	}
	for objectID, values := range dynamicValuesByObject {
		obj := objects[objectID]
		if obj == nil || len(values) == 0 {
			continue
		}
		obj.Resolutions = make([]networkModels.ObjectResolution, 0, len(values))
		for _, value := range values {
			obj.Resolutions = append(obj.Resolutions, networkModels.ObjectResolution{
				ObjectID:      objectID,
				ResolvedValue: value,
			})
		}
	}

	return buildFirewallObjectTables(trafficRules, natRules), nil
}

func buildFirewallObjectTables(trafficRules []networkModels.FirewallTrafficRule, natRules []networkModels.FirewallNATRule) map[uint]firewallObjectTable {
	objects := make(map[uint]*networkModels.Object)
	addObject := func(obj *networkModels.Object) {
		if obj == nil || obj.ID == 0 {
			return
		}
		if _, exists := objects[obj.ID]; exists {
			return
		}
		objects[obj.ID] = obj
	}

	for _, rule := range trafficRules {
		if !rule.Enabled {
			continue
		}
		addObject(rule.SourceObj)
		addObject(rule.DestObj)
	}
	for _, rule := range natRules {
		if !rule.Enabled {
			continue
		}
		addObject(rule.SourceObj)
		addObject(rule.DestObj)
	}

	tables := make(map[uint]firewallObjectTable, len(objects))
	for objectID, obj := range objects {
		values := objectValuesForFirewall(obj)
		v4, v6, _ := splitByFamily(values)
		v4 = uniqueSortedValues(v4)
		v6 = uniqueSortedValues(v6)

		table := firewallObjectTable{
			ObjectID:    objectID,
			ObjectName:  strings.TrimSpace(obj.Name),
			InetValues:  v4,
			Inet6Values: v6,
		}
		if len(v4) > 0 {
			table.InetName = firewallObjectTableName(objectID, "inet")
		}
		if len(v6) > 0 {
			table.Inet6Name = firewallObjectTableName(objectID, "inet6")
		}
		tables[objectID] = table
	}

	return tables
}

func renderFirewallObjectTables(tables map[uint]firewallObjectTable) string {
	var b strings.Builder
	b.WriteString("# managed by Sylve: object tables\n")

	if len(tables) == 0 {
		return b.String()
	}

	ids := make([]int, 0, len(tables))
	for id := range tables {
		ids = append(ids, int(id))
	}
	sort.Ints(ids)

	for _, id := range ids {
		table := tables[uint(id)]
		objectLabel := fmt.Sprintf("object id=%d", table.ObjectID)
		if table.ObjectName != "" {
			objectLabel += fmt.Sprintf(" name=%q", strings.ReplaceAll(table.ObjectName, "\n", " "))
		}
		b.WriteString("# " + objectLabel + "\n")
		if table.InetName != "" && len(table.InetValues) > 0 {
			b.WriteString(fmt.Sprintf("table <%s> persist { %s }\n", table.InetName, strings.Join(table.InetValues, ", ")))
		}
		if table.Inet6Name != "" && len(table.Inet6Values) > 0 {
			b.WriteString(fmt.Sprintf("table <%s> persist { %s }\n", table.Inet6Name, strings.Join(table.Inet6Values, ", ")))
		}
	}

	return b.String()
}

func objectValuesForFirewall(obj *networkModels.Object) []string {
	if obj == nil {
		return nil
	}

	useResolutions := obj.Type == "FQDN" || obj.Type == "List"
	values := []string{}

	if useResolutions && len(obj.Resolutions) > 0 {
		for _, resolution := range obj.Resolutions {
			if strings.TrimSpace(resolution.ResolvedValue) != "" {
				values = append(values, strings.TrimSpace(resolution.ResolvedValue))
			}
		}
	}

	if len(values) > 0 {
		return values
	}

	for _, entry := range obj.Entries {
		if strings.TrimSpace(entry.Value) != "" {
			values = append(values, strings.TrimSpace(entry.Value))
		}
	}

	return values
}

func firewallPortSelector(raw string, portObj *networkModels.Object) string {
	if strings.TrimSpace(raw) != "" {
		return strings.TrimSpace(raw)
	}

	if portObj == nil {
		return ""
	}

	ports := make([]string, 0, len(portObj.Entries))
	for _, entry := range portObj.Entries {
		value := strings.TrimSpace(entry.Value)
		if value == "" {
			continue
		}
		ports = append(ports, value)
	}

	return compactPFList(ports)
}

func firewallAddressSelector(raw string, obj *networkModels.Object, family string, objectTables map[uint]firewallObjectTable) (string, bool, string) {
	if strings.TrimSpace(raw) != "" {
		return strings.TrimSpace(raw), false, ""
	}

	if obj == nil {
		return "any", false, ""
	}

	table, ok := objectTables[obj.ID]
	if !ok {
		return "", true, fmt.Sprintf("object_id=%d has no usable inet/inet6 table values", obj.ID)
	}

	switch family {
	case "inet":
		if table.InetName == "" {
			return "", true, fmt.Sprintf("object_id=%d has no inet values", obj.ID)
		}
		return "<" + table.InetName + ">", false, ""
	case "inet6":
		if table.Inet6Name == "" {
			return "", true, fmt.Sprintf("object_id=%d has no inet6 values", obj.ID)
		}
		return "<" + table.Inet6Name + ">", false, ""
	default:
		if table.InetName != "" && table.Inet6Name != "" {
			return "{ <" + table.InetName + ">, <" + table.Inet6Name + "> }", false, ""
		}
		if table.InetName != "" {
			return "<" + table.InetName + ">", false, ""
		}
		if table.Inet6Name != "" {
			return "<" + table.Inet6Name + ">", false, ""
		}
		return "", true, fmt.Sprintf("object_id=%d has no usable inet/inet6 table values", obj.ID)
	}
}

func familiesForRule(ruleFamily string, srcObj *networkModels.Object, dstObj *networkModels.Object, srcRaw string, dstRaw string) []string {
	if ruleFamily == "inet" || ruleFamily == "inet6" {
		return []string{ruleFamily}
	}

	if strings.TrimSpace(srcRaw) != "" || strings.TrimSpace(dstRaw) != "" {
		return []string{"any"}
	}

	srcVals := objectValuesForFirewall(srcObj)
	dstVals := objectValuesForFirewall(dstObj)

	src4, src6, _ := splitByFamily(srcVals)
	dst4, dst6, _ := splitByFamily(dstVals)

	has4 := len(src4) > 0 || len(dst4) > 0
	has6 := len(src6) > 0 || len(dst6) > 0

	if has4 && has6 {
		return []string{"inet", "inet6"}
	}
	if has4 {
		return []string{"inet"}
	}
	if has6 {
		return []string{"inet6"}
	}

	return []string{"any"}
}

func familiesForRuleWithTables(ruleFamily string, srcObj *networkModels.Object, dstObj *networkModels.Object, srcRaw string, dstRaw string) []string {
	families := familiesForRule(ruleFamily, srcObj, dstObj, srcRaw, dstRaw)
	if ruleFamily != "any" {
		return families
	}

	if (srcObj != nil || dstObj != nil) && len(families) == 1 && families[0] == "any" {
		return []string{"inet", "inet6"}
	}

	return families
}

func addFamilyFromAddressValue(families map[string]struct{}, value string) {
	v := strings.TrimSpace(value)
	if v == "" || strings.EqualFold(v, "any") {
		return
	}

	switch {
	case utils.IsValidIPv4(v), utils.IsValidIPv4CIDR(v):
		families["inet"] = struct{}{}
	case utils.IsValidIPv6(v), utils.IsValidIPv6CIDR(v):
		families["inet6"] = struct{}{}
	}
}

func addFamiliesFromObjectValues(families map[string]struct{}, obj *networkModels.Object, hostOnly bool) {
	for _, value := range objectValuesForFirewall(obj) {
		v := strings.TrimSpace(value)
		if v == "" {
			continue
		}

		if hostOnly {
			switch {
			case utils.IsValidIPv4(v):
				families["inet"] = struct{}{}
			case utils.IsValidIPv6(v):
				families["inet6"] = struct{}{}
			}
			continue
		}

		addFamilyFromAddressValue(families, v)
	}
}

func familiesForNATRuleWithTables(rule networkModels.FirewallNATRule) []string {
	if rule.Family == "inet" || rule.Family == "inet6" {
		return []string{rule.Family}
	}

	families := make(map[string]struct{}, 2)
	for _, family := range familiesForRuleWithTables(rule.Family, rule.SourceObj, rule.DestObj, rule.SourceRaw, rule.DestRaw) {
		if family == "inet" || family == "inet6" {
			families[family] = struct{}{}
		}
	}

	addFamilyFromAddressValue(families, rule.SourceRaw)
	addFamilyFromAddressValue(families, rule.DestRaw)
	addFamilyFromAddressValue(families, rule.TranslateToRaw)
	addFamilyFromAddressValue(families, rule.DNATTargetRaw)
	addFamiliesFromObjectValues(families, rule.TranslateToObj, true)
	addFamiliesFromObjectValues(families, rule.DNATTargetObj, true)

	out := make([]string, 0, 2)
	if _, ok := families["inet"]; ok {
		out = append(out, "inet")
	}
	if _, ok := families["inet6"]; ok {
		out = append(out, "inet6")
	}

	if len(out) == 0 {
		return []string{"any"}
	}
	return out
}

func singleHostSelector(raw string, obj *networkModels.Object, family string) (string, bool, string) {
	if strings.TrimSpace(raw) != "" {
		value := strings.TrimSpace(raw)
		switch family {
		case "inet":
			if !utils.IsValidIPv4(value) {
				return "", true, fmt.Sprintf("raw target %q is not valid for family inet", value)
			}
		case "inet6":
			if !utils.IsValidIPv6(value) {
				return "", true, fmt.Sprintf("raw target %q is not valid for family inet6", value)
			}
		default:
			if !utils.IsValidIPv4(value) && !utils.IsValidIPv6(value) {
				return "", true, fmt.Sprintf("raw target %q is not a valid host address", value)
			}
		}
		return value, false, ""
	}

	if obj == nil {
		return "", true, "missing target object"
	}

	values := objectValuesForFirewall(obj)
	hosts := make([]string, 0, len(values))
	for _, value := range values {
		v := strings.TrimSpace(value)
		if v == "" {
			continue
		}
		switch family {
		case "inet":
			if utils.IsValidIPv4(v) {
				hosts = append(hosts, v)
			}
		case "inet6":
			if utils.IsValidIPv6(v) {
				hosts = append(hosts, v)
			}
		default:
			if utils.IsValidIPv4(v) || utils.IsValidIPv6(v) {
				hosts = append(hosts, v)
			}
		}
	}

	hosts = uniqueSortedValues(hosts)
	if len(hosts) == 0 {
		return "", true, fmt.Sprintf("object_id=%d has no host values", obj.ID)
	}
	if len(hosts) > 1 {
		return "", true, fmt.Sprintf("object_id=%d has multiple host values (%d)", obj.ID, len(hosts))
	}

	return hosts[0], false, ""
}

func pfProtoClause(protocol string) string {
	if protocol == "" || protocol == "any" {
		return ""
	}
	return " proto " + protocol
}

func (s *Service) renderTrafficRules(rules []networkModels.FirewallTrafficRule, objectTables map[uint]firewallObjectTable) (string, error) {
	var b strings.Builder
	b.WriteString("# managed by Sylve: traffic rules\n")

	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}

		if rule.SourceObjID != nil && strings.TrimSpace(rule.SourceRaw) == "" && rule.SourceObj == nil {
			message := fmt.Sprintf("skipped traffic rule id=%d name=%q: source object id=%d could not be resolved", rule.ID, rule.Name, *rule.SourceObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}
		if rule.DestObjID != nil && strings.TrimSpace(rule.DestRaw) == "" && rule.DestObj == nil {
			message := fmt.Sprintf("skipped traffic rule id=%d name=%q: destination object id=%d could not be resolved", rule.ID, rule.Name, *rule.DestObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}

		families := familiesForRuleWithTables(rule.Family, rule.SourceObj, rule.DestObj, rule.SourceRaw, rule.DestRaw)
		direction := normalizeDirection(rule.Direction)
		interfaces := []string{}
		if direction == "in" {
			interfaces = normalizeInterfaceList(rule.IngressInterfaces)
		} else {
			interfaces = normalizeInterfaceList(rule.EgressInterfaces)
		}
		if len(interfaces) == 0 {
			interfaces = []string{""}
		}

		sourcePort := firewallPortSelector(rule.SrcPortsRaw, rule.SrcPortObj)
		destPort := firewallPortSelector(rule.DstPortsRaw, rule.DstPortObj)

		for _, family := range families {
			srcSelector, srcSkipped, srcReason := firewallAddressSelector(rule.SourceRaw, rule.SourceObj, family, objectTables)
			if srcSkipped {
				message := fmt.Sprintf("skipped traffic rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, srcReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}
			dstSelector, dstSkipped, dstReason := firewallAddressSelector(rule.DestRaw, rule.DestObj, family, objectTables)
			if dstSkipped {
				message := fmt.Sprintf("skipped traffic rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, dstReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}

			if srcSelector == "" || dstSelector == "" {
				continue
			}

			for _, iface := range interfaces {
				var line strings.Builder
				line.WriteString(rule.Action)
				line.WriteString(" ")
				line.WriteString(direction)
				if rule.Log {
					line.WriteString(" log")
				}
				if rule.Quick {
					line.WriteString(" quick")
				}
				if strings.TrimSpace(iface) != "" {
					line.WriteString(" on ")
					line.WriteString(strings.TrimSpace(iface))
				}
				if family == "inet" || family == "inet6" {
					line.WriteString(" ")
					line.WriteString(family)
				}
				line.WriteString(pfProtoClause(rule.Protocol))
				line.WriteString(" from ")
				line.WriteString(srcSelector)
				if sourcePort != "" {
					line.WriteString(" port ")
					line.WriteString(sourcePort)
				}
				line.WriteString(" to ")
				line.WriteString(dstSelector)
				if destPort != "" {
					line.WriteString(" port ")
					line.WriteString(destPort)
				}
				line.WriteString(" label \"")
				line.WriteString(trafficRuleLabel(rule.ID))
				line.WriteString("\"")

				b.WriteString(line.String())
				b.WriteString("\n")
			}
		}
	}

	return b.String(), nil
}

func (s *Service) renderNATRules(rules []networkModels.FirewallNATRule, objectTables map[uint]firewallObjectTable) (string, error) {
	var b strings.Builder
	b.WriteString("# managed by Sylve: nat rules\n")

	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}

		natType := normalizeNATType(rule.NATType)
		translateMode := normalizeTranslateMode(rule.TranslateMode)

		if rule.SourceObjID != nil && strings.TrimSpace(rule.SourceRaw) == "" && rule.SourceObj == nil {
			message := fmt.Sprintf("skipped nat rule id=%d name=%q: source object id=%d could not be resolved", rule.ID, rule.Name, *rule.SourceObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}
		if rule.DestObjID != nil && strings.TrimSpace(rule.DestRaw) == "" && rule.DestObj == nil {
			message := fmt.Sprintf("skipped nat rule id=%d name=%q: destination object id=%d could not be resolved", rule.ID, rule.Name, *rule.DestObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}
		if rule.TranslateToObjID != nil && strings.TrimSpace(rule.TranslateToRaw) == "" && rule.TranslateToObj == nil {
			message := fmt.Sprintf("skipped nat rule id=%d name=%q: translate target object id=%d could not be resolved", rule.ID, rule.Name, *rule.TranslateToObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}
		if rule.DNATTargetObjID != nil && strings.TrimSpace(rule.DNATTargetRaw) == "" && rule.DNATTargetObj == nil {
			message := fmt.Sprintf("skipped nat rule id=%d name=%q: dnat target object id=%d could not be resolved", rule.ID, rule.Name, *rule.DNATTargetObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}

		ingressInterfaces := normalizeInterfaceList(rule.IngressInterfaces)
		egressInterfaces := normalizeInterfaceList(rule.EgressInterfaces)

		switch natType {
		case "snat", "binat":
			if len(egressInterfaces) == 0 {
				return "", fmt.Errorf("%s_rule_requires_egress_interface: id=%d name=%s", natType, rule.ID, rule.Name)
			}
		case "dnat":
			if len(ingressInterfaces) == 0 {
				return "", fmt.Errorf("dnat_rule_requires_ingress_interface: id=%d name=%s", rule.ID, rule.Name)
			}
		default:
			return "", fmt.Errorf("invalid_nat_type_for_rule: id=%d type=%s", rule.ID, natType)
		}

		primaryInterfaces := []string{}
		if natType == "dnat" {
			primaryInterfaces = ingressInterfaces
		} else {
			primaryInterfaces = egressInterfaces
		}

		families := familiesForNATRuleWithTables(rule)
		matchPortSelector := firewallPortSelector(rule.DstPortsRaw, rule.DstPortObj)
		redirectPortSelector := firewallPortSelector(rule.RedirectPortsRaw, rule.RedirectPortObj)

		for _, family := range families {
			srcSelector, srcSkipped, srcReason := firewallAddressSelector(rule.SourceRaw, rule.SourceObj, family, objectTables)
			if srcSkipped {
				message := fmt.Sprintf("skipped nat rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, srcReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}
			dstSelector, dstSkipped, dstReason := firewallAddressSelector(rule.DestRaw, rule.DestObj, family, objectTables)
			if dstSkipped {
				message := fmt.Sprintf("skipped nat rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, dstReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}

			if srcSelector == "" || dstSelector == "" {
				continue
			}

			targetSelector := ""
			switch natType {
			case "snat", "binat":
				if translateMode == "address" {
					target, targetSkipped, targetReason := singleHostSelector(rule.TranslateToRaw, rule.TranslateToObj, family)
					if targetSkipped {
						message := fmt.Sprintf("skipped nat rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, targetReason)
						logger.L.Warn().Msg(message)
						b.WriteString("# " + message + "\n")
						continue
					}
					targetSelector = target
				}
			case "dnat":
				target, targetSkipped, targetReason := singleHostSelector(rule.DNATTargetRaw, rule.DNATTargetObj, family)
				if targetSkipped {
					message := fmt.Sprintf("skipped nat rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, targetReason)
					logger.L.Warn().Msg(message)
					b.WriteString("# " + message + "\n")
					continue
				}
				targetSelector = target
			}

			for _, primaryIface := range primaryInterfaces {
				if strings.TrimSpace(primaryIface) == "" {
					continue
				}
				primary := strings.TrimSpace(primaryIface)

				var line strings.Builder
				switch natType {
				case "snat":
					line.WriteString("nat")
				case "binat":
					line.WriteString("binat")
				case "dnat":
					line.WriteString("rdr")
				}
				if rule.Log {
					line.WriteString(" log")
				}
				line.WriteString(" on ")
				line.WriteString(primary)

				if family == "inet" || family == "inet6" {
					line.WriteString(" ")
					line.WriteString(family)
				}

				line.WriteString(pfProtoClause(rule.Protocol))
				line.WriteString(" from ")
				line.WriteString(srcSelector)
				line.WriteString(" to ")
				line.WriteString(dstSelector)

				if natType == "dnat" {
					if matchPortSelector != "" {
						line.WriteString(" port ")
						line.WriteString(matchPortSelector)
					}
					line.WriteString(" tag ")
					line.WriteString(natRuleLabel(rule.ID))
					line.WriteString(" -> ")
					line.WriteString(targetSelector)
					if redirectPortSelector != "" {
						line.WriteString(" port ")
						line.WriteString(redirectPortSelector)
					}
				} else {
					line.WriteString(" tag ")
					line.WriteString(natRuleLabel(rule.ID))
					line.WriteString(" -> ")
					if translateMode == "address" {
						line.WriteString(targetSelector)
					} else {
						line.WriteString("(")
						line.WriteString(primary)
						line.WriteString(")")
					}
				}

				b.WriteString(line.String())
				b.WriteString("\n")
			}
		}
	}

	return b.String(), nil
}

func (s *Service) renderNATPolicyRoutingRules(rules []networkModels.FirewallNATRule, objectTables map[uint]firewallObjectTable) (string, error) {
	var b strings.Builder
	b.WriteString("# managed by Sylve: nat policy routing companion rules\n")

	emitted := false
	for _, rule := range rules {
		if !rule.Enabled || !rule.PolicyRoutingEnabled {
			continue
		}

		natType := normalizeNATType(rule.NATType)
		if natType != "snat" && natType != "binat" {
			return "", fmt.Errorf("policy_routing_requires_snat_or_binat: id=%d type=%s", rule.ID, natType)
		}

		if rule.SourceObjID != nil && strings.TrimSpace(rule.SourceRaw) == "" && rule.SourceObj == nil {
			message := fmt.Sprintf("skipped nat policy rule id=%d name=%q: source object id=%d could not be resolved", rule.ID, rule.Name, *rule.SourceObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}
		if rule.DestObjID != nil && strings.TrimSpace(rule.DestRaw) == "" && rule.DestObj == nil {
			message := fmt.Sprintf("skipped nat policy rule id=%d name=%q: destination object id=%d could not be resolved", rule.ID, rule.Name, *rule.DestObjID)
			logger.L.Warn().Msg(message)
			b.WriteString("# " + message + "\n")
			continue
		}

		egressInterfaces := normalizeInterfaceList(rule.EgressInterfaces)
		if len(egressInterfaces) != 1 {
			return "", fmt.Errorf("policy_routing_requires_single_egress_interface_for_rule: id=%d name=%s", rule.ID, rule.Name)
		}
		egressIface := strings.TrimSpace(egressInterfaces[0])
		if egressIface == "" {
			return "", fmt.Errorf("policy_routing_requires_single_egress_interface_for_rule: id=%d name=%s", rule.ID, rule.Name)
		}

		families := familiesForNATRuleWithTables(rule)
		gateway := strings.TrimSpace(rule.PolicyRouteGateway)
		if gateway == "" {
			return "", fmt.Errorf("policy_route_gateway_required_for_rule: id=%d name=%s", rule.ID, rule.Name)
		}

		for _, family := range families {
			srcSelector, srcSkipped, srcReason := firewallAddressSelector(rule.SourceRaw, rule.SourceObj, family, objectTables)
			if srcSkipped {
				message := fmt.Sprintf("skipped nat policy rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, srcReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}
			dstSelector, dstSkipped, dstReason := firewallAddressSelector(rule.DestRaw, rule.DestObj, family, objectTables)
			if dstSkipped {
				message := fmt.Sprintf("skipped nat policy rule id=%d name=%q family=%s: %s", rule.ID, rule.Name, family, dstReason)
				logger.L.Warn().Msg(message)
				b.WriteString("# " + message + "\n")
				continue
			}

			if srcSelector == "" || dstSelector == "" {
				continue
			}

			routedDstSelector := dstSelector
			if strings.EqualFold(strings.TrimSpace(dstSelector), "any") {
				routedDstSelector = "! self"
			}

			ingressIfaces := normalizeInterfaceList(rule.IngressInterfaces)
			if len(ingressIfaces) == 0 {
				ingressIfaces = []string{""}
			}

			if family != "inet" && family != "inet6" {
				return "", fmt.Errorf("policy_route_gateway_requires_explicit_family_for_rule: id=%d name=%s", rule.ID, rule.Name)
			}
			if err := validateFamilyAgainstRawAddress(gateway, family, false, "policy_route_gateway", false); err != nil {
				return "", fmt.Errorf("invalid_policy_route_gateway_for_rule: id=%d name=%s: %w", rule.ID, rule.Name, err)
			}

			for _, ingressIface := range ingressIfaces {
				var line strings.Builder
				line.WriteString("pass in quick")
				if strings.TrimSpace(ingressIface) != "" {
					line.WriteString(" on ")
					line.WriteString(strings.TrimSpace(ingressIface))
				}
				line.WriteString(" route-to (")
				line.WriteString(egressIface)
				line.WriteString(" ")
				line.WriteString(gateway)
				line.WriteString(")")
				if family == "inet" || family == "inet6" {
					line.WriteString(" ")
					line.WriteString(family)
				}
				line.WriteString(pfProtoClause(rule.Protocol))
				line.WriteString(" from ")
				line.WriteString(srcSelector)
				line.WriteString(" to ")
				line.WriteString(routedDstSelector)
				line.WriteString(" tag \"")
				line.WriteString(natRuleLabel(rule.ID))
				line.WriteString("\" label \"")
				line.WriteString(natPolicyRuleLabel(rule.ID, "in"))
				line.WriteString("\"")

				b.WriteString(line.String())
				b.WriteString("\n")
				emitted = true
			}

			var outLine strings.Builder
			outLine.WriteString("pass out quick on ")
			outLine.WriteString(egressIface)
			outLine.WriteString(" route-to (")
			outLine.WriteString(egressIface)
			outLine.WriteString(" ")
			outLine.WriteString(gateway)
			outLine.WriteString(")")
			if family == "inet" || family == "inet6" {
				outLine.WriteString(" ")
				outLine.WriteString(family)
			}
			outLine.WriteString(pfProtoClause(rule.Protocol))
			outLine.WriteString(" from ")
			outLine.WriteString(srcSelector)
			outLine.WriteString(" to ")
			outLine.WriteString(routedDstSelector)
			outLine.WriteString(" tag \"")
			outLine.WriteString(natRuleLabel(rule.ID))
			outLine.WriteString("\" label \"")
			outLine.WriteString(natPolicyRuleLabel(rule.ID, "out"))
			outLine.WriteString("\"")

			b.WriteString(outLine.String())
			b.WriteString("\n")
			emitted = true
		}
	}

	if !emitted {
		return "", nil
	}

	return b.String(), nil
}

func parsePortValue(value string) bool {
	v := strings.TrimSpace(value)
	if v == "" {
		return false
	}

	if strings.Contains(v, ":") {
		parts := strings.Split(v, ":")
		if len(parts) != 2 {
			return false
		}
		start, err := strconv.Atoi(parts[0])
		if err != nil || !utils.IsValidPort(start) {
			return false
		}
		end, err := strconv.Atoi(parts[1])
		if err != nil || !utils.IsValidPort(end) {
			return false
		}
		return start <= end
	}

	n, err := strconv.Atoi(v)
	if err != nil {
		return false
	}

	return utils.IsValidPort(n)
}

func resolveFQDNValues(name string) ([]string, error) {
	ips, err := net.LookupIP(name)
	if err != nil {
		return nil, err
	}

	values := make([]string, 0, len(ips))
	for _, ip := range ips {
		values = append(values, ip.String())
	}
	return values, nil
}
