// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package iscsi

import (
	"fmt"
	"strings"

	iscsiModels "github.com/alchemillahq/sylve/internal/db/models/iscsi"
	"github.com/alchemillahq/sylve/internal/logger"
	"github.com/alchemillahq/sylve/pkg/utils"
)

const configMarker = "# === This file is automatically generated by Sylve, don't edit! ==="

var configPath = "/etc/iscsi.conf"
var targetConfigPath = "/etc/ctl.conf"

func SetConfigPath(path string) {
	configPath = path
}

func SetTargetConfigPath(path string) {
	targetConfigPath = path
}

func (s *Service) GenerateConfig() (string, error) {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.generateConfig()
}

func (s *Service) generateConfig() (string, error) {
	var initiators []iscsiModels.ISCSIInitiator
	if err := s.DB.Find(&initiators).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_initiators: %w", err)
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")

	for _, ini := range initiators {
		if ini.Nickname == "" {
			return "", invalidRequest("nickname_required")
		}
		if err := validateBareConfigToken(ini.Nickname, "nickname", maxNicknameLength); err != nil {
			return "", err
		}
		targetAddress, err := normalizeInitiatorTargetAddress(ini.TargetAddress)
		if err != nil {
			return "", err
		}
		if ini.TargetName == "" {
			return "", invalidRequest("target_name_required")
		}
		if err := validateBareConfigToken(ini.TargetName, "target_name", maxISCSINameLength); err != nil {
			return "", err
		}
		if ini.InitiatorName != "" {
			if err := validateBareConfigToken(ini.InitiatorName, "initiator_name", maxISCSINameLength); err != nil {
				return "", err
			}
		}
		authMethod := strings.TrimSpace(ini.AuthMethod)
		if authMethod == "" {
			authMethod = "None"
		}
		if err := validateAuthMethod(authMethod, ini.CHAPName, ini.CHAPSecret, ini.TgtCHAPName, ini.TgtCHAPSecret); err != nil {
			return "", err
		}

		b.WriteString(fmt.Sprintf("%s {\n", ini.Nickname))
		b.WriteString(fmt.Sprintf("\ttargetaddress\t= %s;\n", targetAddress))
		b.WriteString(fmt.Sprintf("\ttargetname\t= %s;\n", ini.TargetName))
		if ini.InitiatorName != "" {
			b.WriteString(fmt.Sprintf("\tinitiatorname\t= %s;\n", ini.InitiatorName))
		}

		switch authMethod {
		case "CHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %q;\n", ini.CHAPName))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %q;\n", ini.CHAPSecret))
		case "MutualCHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %q;\n", ini.CHAPName))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %q;\n", ini.CHAPSecret))
			b.WriteString(fmt.Sprintf("\ttgtChapName\t= %q;\n", ini.TgtCHAPName))
			b.WriteString(fmt.Sprintf("\ttgtChapSecret\t= %q;\n", ini.TgtCHAPSecret))
		}

		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteConfig(reload bool) error {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.writeConfig(reload)
}

func (s *Service) writeConfig(reload bool) error {
	cfg, err := s.generateConfig()
	if err != nil {
		return err
	}

	if err := utils.AtomicWriteFile(configPath, []byte(cfg), 0600); err != nil {
		logger.L.Error().Err(err).Msg("failed to write iSCSI initiator config")
		return applyFailed("failed_to_write_iscsi_config", err)
	}

	if !reload {
		return nil
	}

	if _, err := utils.RunCommandAllowExitCode("/usr/bin/iscsictl", []int{0}, "-Aa"); err != nil {
		logger.L.Error().Err(err).Msg("failed to add configured iSCSI initiator sessions")
		return applyFailed("failed_to_add_iscsi_sessions", err)
	}

	return nil
}

func (s *Service) GenerateTargetConfig() (string, error) {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.generateTargetConfig()
}

func (s *Service) generateTargetConfig() (string, error) {
	var targets []iscsiModels.ISCSITarget
	if err := s.DB.Preload("Portals").Preload("LUNs").Find(&targets).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_targets: %w", err)
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")
	usedZVols := make(map[string]struct{})

	for _, tgt := range targets {
		if tgt.TargetName == "" {
			return "", invalidRequest("target_name_required")
		}
		if err := validateBareConfigToken(tgt.TargetName, "target_name", maxISCSINameLength); err != nil {
			return "", err
		}
		if err := validateQuotedConfigValue(tgt.Alias, "alias", maxQuotedLength); err != nil {
			return "", err
		}
		authMethod := strings.TrimSpace(tgt.AuthMethod)
		if authMethod == "" {
			authMethod = "None"
		}
		if err := validateTargetAuthMethod(authMethod, tgt.CHAPName, tgt.CHAPSecret, tgt.MutualCHAPName, tgt.MutualCHAPSecret); err != nil {
			return "", err
		}

		b.WriteString(fmt.Sprintf("portal-group pg-%d {\n", tgt.ID))
		b.WriteString("\tdiscovery-auth-group no-authentication\n")
		for _, portal := range tgt.Portals {
			address, err := normalizePortalAddress(portal.Address)
			if err != nil {
				return "", err
			}
			port := portal.Port
			if port == 0 {
				port = 3260
			}
			if port < 1 || port > 65535 {
				return "", invalidRequest("portal_port_must_be_between_1_and_65535")
			}
			b.WriteString(fmt.Sprintf("\tlisten %s:%d\n", address, port))
		}
		b.WriteString("}\n\n")

		if authMethod == "CHAP" || authMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("auth-group ag-%d {\n", tgt.ID))
			if authMethod == "MutualCHAP" {
				b.WriteString(fmt.Sprintf("\tchap-mutual %q %q %q %q\n",
					tgt.CHAPName, tgt.CHAPSecret, tgt.MutualCHAPName, tgt.MutualCHAPSecret))
			} else {
				b.WriteString(fmt.Sprintf("\tchap %q %q\n", tgt.CHAPName, tgt.CHAPSecret))
			}
			b.WriteString("}\n\n")
		}

		b.WriteString(fmt.Sprintf("target %s {\n", tgt.TargetName))
		if tgt.Alias != "" {
			b.WriteString(fmt.Sprintf("\talias %q\n", tgt.Alias))
		}
		b.WriteString(fmt.Sprintf("\tportal-group pg-%d\n", tgt.ID))
		if authMethod == "CHAP" || authMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("\tauth-group ag-%d\n", tgt.ID))
		} else {
			b.WriteString("\tauth-group no-authentication\n")
		}
		for _, lun := range tgt.LUNs {
			if lun.LUNNumber < 0 {
				return "", invalidRequest("lun_number_must_be_non_negative")
			}
			if err := validateZVol(lun.ZVol); err != nil {
				return "", err
			}
			if _, exists := usedZVols[lun.ZVol]; exists {
				return "", resourceConflict("zvol_already_in_use", nil)
			}
			usedZVols[lun.ZVol] = struct{}{}

			b.WriteString(fmt.Sprintf("\tlun %d {\n", lun.LUNNumber))
			b.WriteString(fmt.Sprintf("\t\tpath /dev/zvol/%s\n", lun.ZVol))
			b.WriteString("\t}\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteTargetConfig(reload bool) error {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.writeTargetConfig(reload)
}

func (s *Service) writeTargetConfig(reload bool) error {
	cfg, err := s.generateTargetConfig()
	if err != nil {
		return err
	}

	if _, err := utils.RunCommandWithInput("/usr/sbin/ctld", cfg, "-t", "-f", "/dev/stdin"); err != nil {
		logger.L.Error().Err(err).Msg("failed to validate iSCSI target config")
		return applyFailed("failed_to_validate_target_config", err)
	}

	if err := utils.AtomicWriteFile(targetConfigPath, []byte(cfg), 0600); err != nil {
		logger.L.Error().Err(err).Msg("failed to write iSCSI target config")
		return applyFailed("failed_to_write_target_config", err)
	}

	if !reload {
		return nil
	}

	if _, err := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0}, "ctld", "onestatus"); err != nil {
		if _, startErr := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0}, "ctld", "onestart"); startErr != nil {
			logger.L.Error().Err(startErr).Msg("failed to start ctld")
			return applyFailed("failed_to_start_target_service", startErr)
		}
		return nil
	}

	if _, err := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0}, "ctld", "onereload"); err != nil {
		logger.L.Error().Err(err).Msg("failed to reload ctld")
		return applyFailed("failed_to_reload_target_config", err)
	}

	return nil
}

func ensureISCSIServiceStarted(service string) error {
	if _, err := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0}, service, "onestatus"); err == nil {
		return nil
	}

	if _, err := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0}, service, "onestart"); err != nil {
		return err
	}
	return nil
}

func (s *Service) SetEnabled(enabled bool) error {
	if !enabled {
		return nil
	}

	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	if err := s.writeConfig(false); err != nil {
		return err
	}
	if err := s.writeTargetConfig(false); err != nil {
		return err
	}
	if err := ensureISCSIServiceStarted("iscsid"); err != nil {
		return applyFailed("failed_to_start_initiator_service", err)
	}
	if err := ensureISCSIServiceStarted("ctld"); err != nil {
		return applyFailed("failed_to_start_target_service", err)
	}
	if _, err := utils.RunCommandAllowExitCode("/usr/bin/iscsictl", []int{0}, "-Aa"); err != nil {
		return applyFailed("failed_to_add_iscsi_sessions", err)
	}

	return nil
}
