// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package iscsi

import (
	"context"
	"errors"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	iscsiModels "github.com/alchemillahq/sylve/internal/db/models/iscsi"
	"github.com/alchemillahq/sylve/internal/logger"
	"github.com/alchemillahq/sylve/pkg/utils"
)

const configMarker = "# === This file is automatically generated by Sylve, don't edit! ==="

var configPath = "/etc/iscsi.conf"
var targetConfigPath = "/etc/ctl.conf"

func SetConfigPath(path string) func() {
	previous := configPath
	configPath = path
	return func() { configPath = previous }
}

func SetTargetConfigPath(path string) func() {
	previous := targetConfigPath
	targetConfigPath = path
	return func() { targetConfigPath = previous }
}

func (s *Service) GenerateConfig() (string, error) {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.generateConfig()
}

func (s *Service) generateConfig() (string, error) {
	var initiators []iscsiModels.ISCSIInitiator
	if err := s.DB.Find(&initiators).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_initiators: %w", err)
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")

	for _, ini := range initiators {
		if ini.Nickname == "" {
			return "", invalidRequest("nickname_required")
		}
		if err := validateBareConfigToken(ini.Nickname, "nickname", maxNicknameLength); err != nil {
			return "", err
		}
		targetAddress, err := normalizeInitiatorTargetAddress(ini.TargetAddress)
		if err != nil {
			return "", err
		}
		if ini.TargetName == "" {
			return "", invalidRequest("target_name_required")
		}
		if err := validateBareConfigToken(ini.TargetName, "target_name", maxISCSINameLength); err != nil {
			return "", err
		}
		if ini.InitiatorName != "" {
			if err := validateBareConfigToken(ini.InitiatorName, "initiator_name", maxISCSINameLength); err != nil {
				return "", err
			}
		}
		authMethod := strings.TrimSpace(ini.AuthMethod)
		if authMethod == "" {
			authMethod = "None"
		}
		if err := validateAuthMethod(authMethod, ini.CHAPName, ini.CHAPSecret, ini.TgtCHAPName, ini.TgtCHAPSecret); err != nil {
			return "", err
		}

		b.WriteString(fmt.Sprintf("%s {\n", ini.Nickname))
		b.WriteString(fmt.Sprintf("\ttargetaddress\t= %s;\n", targetAddress))
		b.WriteString(fmt.Sprintf("\ttargetname\t= %s;\n", ini.TargetName))
		if ini.InitiatorName != "" {
			b.WriteString(fmt.Sprintf("\tinitiatorname\t= %s;\n", ini.InitiatorName))
		}

		switch authMethod {
		case "CHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %s;\n", nativeQuote(ini.CHAPName)))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %s;\n", nativeQuote(ini.CHAPSecret)))
		case "MutualCHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %s;\n", nativeQuote(ini.CHAPName)))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %s;\n", nativeQuote(ini.CHAPSecret)))
			b.WriteString(fmt.Sprintf("\ttgtChapName\t= %s;\n", nativeQuote(ini.TgtCHAPName)))
			b.WriteString(fmt.Sprintf("\ttgtChapSecret\t= %s;\n", nativeQuote(ini.TgtCHAPSecret)))
		}

		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteConfig(reload bool) error {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.writeConfig(reload)
}

func (s *Service) writeConfig(reload bool) error {
	cfg, err := s.generateConfig()
	if err != nil {
		return err
	}

	if err := utils.AtomicWriteFile(s.initiatorPath(), []byte(cfg), 0600); err != nil {
		logger.L.Error().Err(err).Msg("failed to write iSCSI initiator config")
		return applyFailed("failed_to_write_iscsi_config", err)
	}

	if !reload {
		return nil
	}

	if _, err := s.runInitiatorCommand("-Aa"); err != nil {
		logger.L.Error().Err(err).Msg("failed to add configured iSCSI initiator sessions")
		return applyFailed("failed_to_add_iscsi_sessions", err)
	}

	return nil
}

func (s *Service) GenerateTargetConfig() (string, error) {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	ctx, cancel := s.targetContext()
	defer cancel()
	return s.generateTargetConfigContext(ctx)
}

func (s *Service) generateTargetConfigContext(ctx context.Context) (string, error) {
	var targets []iscsiModels.ISCSITarget
	if err := s.DB.Preload("Portals").Preload("LUNs").Order("id").Find(&targets).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_targets: %w", err)
	}
	endpoints, attachments, err := s.collectPortalEndpointsContext(ctx, targets)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")
	usedZVols := make(map[string]struct{})
	if s.runtime != nil && s.runtime.pidFile != "" {
		if err := validateNativeQuotedValue(s.runtime.pidFile, "pidfile"); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "pidfile %s\n\n", nativeQuote(s.runtime.pidFile))
	}
	for _, endpoint := range endpoints {
		fmt.Fprintf(&b, "portal-group %s {\n\tdiscovery-auth-group no-authentication\n\tlisten %s\n}\n\n", s.groupName(endpoint), nativeQuote(endpoint.listen()))
	}
	for _, target := range targets {
		if len(attachments[target.ID]) == 0 {
			b.WriteString("portal-group pg-unbound {\n}\n\n")
			break
		}
	}

	for _, tgt := range targets {
		if tgt.TargetName == "" {
			return "", invalidRequest("target_name_required")
		}
		if err := validateBareConfigToken(tgt.TargetName, "target_name", maxISCSINameLength); err != nil {
			return "", err
		}
		if err := validateNativeQuotedValue(tgt.Alias, "alias"); err != nil {
			return "", err
		}
		authMethod := strings.TrimSpace(tgt.AuthMethod)
		if authMethod == "" {
			authMethod = "None"
		}
		if err := validateTargetAuthMethod(authMethod, tgt.CHAPName, tgt.CHAPSecret, tgt.MutualCHAPName, tgt.MutualCHAPSecret); err != nil {
			return "", err
		}

		if authMethod == "CHAP" || authMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("auth-group ag-%d {\n", tgt.ID))
			if authMethod == "MutualCHAP" {
				b.WriteString(fmt.Sprintf("\tchap-mutual %s %s %s %s\n",
					nativeQuote(tgt.CHAPName), nativeQuote(tgt.CHAPSecret), nativeQuote(tgt.MutualCHAPName), nativeQuote(tgt.MutualCHAPSecret)))
			} else {
				b.WriteString(fmt.Sprintf("\tchap %s %s\n", nativeQuote(tgt.CHAPName), nativeQuote(tgt.CHAPSecret)))
			}
			b.WriteString("}\n\n")
		}

		b.WriteString(fmt.Sprintf("target %s {\n", nativeQuote(tgt.TargetName)))
		if tgt.Alias != "" {
			b.WriteString(fmt.Sprintf("\talias %s\n", nativeQuote(tgt.Alias)))
		}
		if len(attachments[tgt.ID]) == 0 {
			b.WriteString("\tportal-group pg-unbound\n")
		}
		for _, endpoint := range attachments[tgt.ID] {
			fmt.Fprintf(&b, "\tportal-group %s\n", s.groupName(endpoint))
		}
		if authMethod == "CHAP" || authMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("\tauth-group ag-%d\n", tgt.ID))
		} else {
			b.WriteString("\tauth-group no-authentication\n")
		}
		sort.Slice(tgt.LUNs, func(i, j int) bool { return tgt.LUNs[i].LUNNumber < tgt.LUNs[j].LUNNumber })
		for _, lun := range tgt.LUNs {
			if lun.LUNNumber < 0 {
				return "", invalidRequest("lun_number_must_be_non_negative")
			}
			if lun.LUNNumber > maxTargetLUNNumber {
				return "", invalidRequest("lun_number_must_be_between_0_and_1023")
			}
			if err := validateZVol(lun.ZVol); err != nil {
				return "", err
			}
			if _, exists := usedZVols[lun.ZVol]; exists {
				return "", resourceConflict("zvol_already_in_use", nil)
			}
			usedZVols[lun.ZVol] = struct{}{}
			if _, err := s.statBacking("/dev/zvol/" + lun.ZVol); err != nil {
				return "", invalidRequest("zvol_backing_not_available")
			}

			b.WriteString(fmt.Sprintf("\tlun %d {\n", lun.LUNNumber))
			b.WriteString(fmt.Sprintf("\t\tpath %s\n", nativeQuote("/dev/zvol/"+lun.ZVol)))
			b.WriteString("\t}\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteTargetConfig(reload bool) error {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	return s.writeTargetConfig(reload)
}

type targetLUN struct {
	name      string
	path      string
	backing   os.FileInfo
	number    int
	size      uint64
	blocksize uint64
}

type targetDefinition struct {
	name   string
	groups []string
	luns   []targetLUN
}

type targetGroup struct {
	listeners    []portalEndpoint
	rawListeners []string
}

type targetConfiguration struct {
	groups  map[string]targetGroup
	targets []targetDefinition
}

func (s *Service) statBacking(path string) (os.FileInfo, error) {
	stat := s.backingStat
	if stat == nil {
		stat = os.Stat
	}
	info, err := stat(path)
	if err != nil {
		return nil, errors.New("zvol_backing_not_available")
	}
	if info.Mode()&os.ModeDevice == 0 {
		return nil, errors.New("zvol_backing_not_a_device")
	}
	return info, nil
}

type nativeConfigToken struct {
	value  string
	quoted bool
}

func nativeConfigTokens(text string) ([]nativeConfigToken, error) {
	var tokens []nativeConfigToken
	for i := 0; i < len(text); {
		switch text[i] {
		case ' ', '\t', '\n':
			i++
		case '\r':
			if i+1 >= len(text) || text[i+1] != '\n' {
				return nil, errors.New("invalid_native_config_token")
			}
			i += 2
		case '#':
			for i < len(text) && text[i] != '\n' {
				i++
			}
		case '{', '}', ';':
			tokens = append(tokens, nativeConfigToken{value: text[i : i+1]})
			i++
		case '"':
			i++
			start := i
			for i < len(text) && text[i] != '"' {
				if text[i] < 0x20 || text[i] == 0x7f {
					return nil, errors.New("invalid_native_config_token")
				}
				i++
			}
			if i == len(text) || i == start {
				return nil, errors.New("invalid_native_config_quote")
			}
			tokens = append(tokens, nativeConfigToken{value: text[start:i], quoted: true})
			i++
		default:
			start := i
			for i < len(text) && strings.ContainsRune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-@_/:[]", rune(text[i])) {
				i++
			}
			if start == i {
				return nil, errors.New("invalid_native_config_token")
			}
			tokens = append(tokens, nativeConfigToken{value: text[start:i]})
		}
	}
	return tokens, nil
}

type configTokenReader struct {
	tokens []nativeConfigToken
	index  int
}

func (p *configTokenReader) next(syntax bool) string {
	if p.index >= len(p.tokens) {
		return ""
	}
	token := p.tokens[p.index]
	p.index++
	if syntax && token.quoted {
		return ""
	}
	if !syntax && !token.quoted && (token.value == "{" || token.value == "}") {
		return ""
	}
	return token.value
}

func (s *Service) inspectTargetConfig(text string) (*targetConfiguration, error) {
	if !strings.HasPrefix(text, configMarker+"\n") {
		return nil, errors.New("target_config_not_owned")
	}
	tokens, err := nativeConfigTokens(text)
	if err != nil {
		return nil, err
	}
	p := configTokenReader{tokens: tokens}
	state := &targetConfiguration{groups: make(map[string]targetGroup)}
	authNames := make(map[string]bool)
	targetNames := make(map[string]bool)
	invalid := errors.New("unsupported_owned_target_config")
	hasPIDFile := false
	for p.index < len(tokens) {
		kind, name := p.next(true), p.next(false)
		if kind == "pidfile" {
			if hasPIDFile || len(state.groups) > 0 || len(state.targets) > 0 || s.runtime == nil || s.runtime.pidFile == "" || name != s.runtime.pidFile {
				return nil, invalid
			}
			hasPIDFile = true
			continue
		}
		if name == "" || p.next(true) != "{" {
			return nil, invalid
		}
		switch kind {
		case "portal-group":
			if !strings.HasPrefix(name, "pg-") {
				return nil, invalid
			}
			if _, exists := state.groups[name]; exists {
				return nil, invalid
			}
			var group targetGroup
			for {
				clause := p.next(true)
				if clause == "}" {
					break
				}
				value := p.next(false)
				if clause == "discovery-auth-group" && value == "no-authentication" {
					continue
				}
				if clause != "listen" {
					return nil, invalid
				}
				endpoint, err := s.parseListener(value)
				if err != nil {
					return nil, invalid
				}
				group.listeners = append(group.listeners, endpoint)
				group.rawListeners = append(group.rawListeners, value)
			}
			state.groups[name] = group
		case "auth-group":
			if !strings.HasPrefix(name, "ag-") || authNames[name] {
				return nil, invalid
			}
			authNames[name] = true
			clause := p.next(true)
			arity := 0
			if clause == "chap" {
				arity = 2
			} else if clause == "chap-mutual" {
				arity = 4
			} else {
				return nil, invalid
			}
			for range arity {
				value := p.next(false)
				if value == "" {
					return nil, invalid
				}
			}
			if p.next(true) != "}" {
				return nil, invalid
			}
		case "target":
			if targetNames[name] {
				return nil, invalid
			}
			targetNames[name] = true
			target := targetDefinition{name: name}
			seenLUNs := make(map[int]bool)
			seenGroups := make(map[string]bool)
			for {
				clause := p.next(true)
				if clause == "}" {
					break
				}
				value := p.next(false)
				switch clause {
				case "alias":
					if err := validateNativeQuotedValue(value, "alias"); err != nil || value == "" {
						return nil, invalid
					}
				case "auth-group":
					if value != "no-authentication" && !authNames[value] {
						return nil, invalid
					}
				case "portal-group":
					if _, exists := state.groups[value]; !exists || seenGroups[value] {
						return nil, invalid
					}
					seenGroups[value] = true
					target.groups = append(target.groups, value)
				case "lun":
					number, err := strconv.Atoi(value)
					if err != nil || number < 0 || number > maxTargetLUNNumber || seenLUNs[number] || p.next(true) != "{" {
						return nil, invalid
					}
					seenLUNs[number] = true
					lun := targetLUN{name: fmt.Sprintf("%s,lun,%d", name, number), number: number, blocksize: 512}
					for {
						field := p.next(true)
						if field == "}" {
							break
						}
						if field != "path" || lun.path != "" {
							return nil, invalid
						}
						lun.path = p.next(false)
						if !strings.HasPrefix(lun.path, "/dev/zvol/") || validateZVol(strings.TrimPrefix(lun.path, "/dev/zvol/")) != nil {
							return nil, invalid
						}
					}
					if lun.path == "" {
						return nil, invalid
					}
					target.luns = append(target.luns, lun)
				default:
					return nil, invalid
				}
			}
			if len(target.groups) == 0 {
				return nil, invalid
			}
			state.targets = append(state.targets, target)
		default:
			return nil, invalid
		}
	}
	return state, nil
}

func (s *Service) parseListener(value string) (portalEndpoint, error) {
	if endpoint, err := s.endpoint(value, 3260); err == nil {
		return endpoint, nil
	}
	host, port, err := splitListener(value)
	if err != nil {
		return portalEndpoint{}, err
	}
	return s.endpoint(host, port)
}

func splitListener(value string) (string, int, error) {
	i := strings.LastIndex(value, ":")
	if i < 0 {
		return "", 0, errors.New("invalid_listener")
	}
	host := value[:i]
	if strings.Contains(host, ":") && !(strings.HasPrefix(host, "[") && strings.HasSuffix(host, "]")) {
		return "", 0, errors.New("invalid_listener")
	}
	port, err := strconv.Atoi(value[i+1:])
	if err != nil || port < 1 || port > 65535 {
		return "", 0, errors.New("invalid_listener")
	}
	return host, port, nil
}

func (state *targetConfiguration) activeEndpoints() []portalEndpoint {
	used := make(map[string]bool)
	var endpoints []portalEndpoint
	for _, target := range state.targets {
		for _, name := range target.groups {
			if used[name] {
				continue
			}
			used[name] = true
			endpoints = append(endpoints, state.groups[name].listeners...)
		}
	}
	return endpoints
}

func (s *Service) checkConfigEndpoints(ctx context.Context, state *targetConfiguration) error {
	var endpoints []portalEndpoint
	for _, group := range state.groups {
		endpoints = append(endpoints, group.listeners...)
	}
	if s.endpointsOverlap(ctx, endpoints) {
		return errors.New("portal_listener_overlap")
	}
	return nil
}

func (s *Service) prepareTargetConfig(ctx context.Context, text string) (*targetConfiguration, error) {
	state, err := s.inspectTargetConfig(text)
	if err != nil {
		return nil, err
	}
	if err := s.checkConfigEndpoints(ctx, state); err != nil {
		return nil, err
	}
	for i := range state.targets {
		for j := range state.targets[i].luns {
			lun := &state.targets[i].luns[j]
			lun.backing, err = s.statBacking(lun.path)
			if err != nil {
				return nil, err
			}
			out, err := s.runTargetCommand(ctx, "", "/usr/sbin/diskinfo", lun.path)
			if err != nil {
				return nil, errors.New("failed_to_check_backing_geometry")
			}
			fields := strings.Fields(out)
			if len(fields) < 3 {
				return nil, errors.New("invalid_backing_geometry")
			}
			lun.blocksize, err = strconv.ParseUint(fields[1], 10, 64)
			if err != nil || lun.blocksize == 0 {
				return nil, errors.New("invalid_backing_geometry")
			}
			lun.size, err = strconv.ParseUint(fields[2], 10, 64)
			if err != nil || lun.size == 0 {
				return nil, errors.New("invalid_backing_geometry")
			}
		}
	}
	if _, err := s.runTargetCommand(ctx, text, "/usr/sbin/ctld", "-t", "-f", "/dev/stdin"); err != nil {
		return nil, errors.New("failed_to_validate_target_config")
	}
	return state, nil
}

func (s *Service) checkListenerTransition(ctx context.Context, pid int, endpoints []portalEndpoint) error {
	data, err := os.ReadFile(s.targetPath())
	if os.IsNotExist(err) {
		return errors.New("iscsi_listener_normalization_requires_stop")
	}
	if err != nil {
		return errors.New("failed_to_read_target_config")
	}
	old, err := s.inspectTargetConfig(string(data))
	if err != nil {
		return errors.New("iscsi_listener_normalization_requires_stop")
	}
	listeners, err := s.targetListeners(ctx, pid)
	if err != nil {
		return err
	}
	for _, group := range old.groups {
		for i, before := range group.listeners {
			for _, after := range endpoints {
				if !before.sameSocket(after) || group.rawListeners[i] == after.listen() {
					continue
				}
				for _, live := range listeners {
					if live.sameSocket(before) {
						return errors.New("iscsi_listener_normalization_requires_stop")
					}
				}
			}
		}
	}
	return nil
}

func (s *Service) writeTargetConfig(reload bool) error {
	ctx, cancel := s.targetContext()
	defer cancel()
	text, err := s.generateTargetConfigContext(ctx)
	if err != nil {
		return applyFailed("invalid_target_configuration", err)
	}
	state, err := s.prepareTargetConfig(ctx, text)
	if err != nil {
		return applyFailed(err.Error(), nil)
	}
	return s.writePreparedTargets(ctx, text, state, reload)
}

func (s *Service) writePreparedTargets(ctx context.Context, text string, state *targetConfiguration, reload bool) error {
	enabled, err := s.desiredTargetEnabled()
	if err != nil {
		return applyFailed("failed_to_read_target_service_state", nil)
	}
	var pid int
	if !enabled {
		if err := s.stopTarget(ctx); err != nil {
			return err
		}
	} else {
		pid, err = s.targetPID(ctx)
		if err != nil && !errors.Is(err, errTargetStopped) {
			return applyFailed("failed_to_check_target_service", nil)
		}
		if pid != 0 {
			if err := s.checkListenerTransition(ctx, pid, state.activeEndpoints()); err != nil {
				return applyFailed(err.Error(), nil)
			}
		}
	}
	if err := utils.AtomicWriteFile(s.targetPath(), []byte(text), 0600); err != nil {
		return applyFailed("failed_to_write_target_config", err)
	}
	if !enabled || !reload {
		return nil
	}
	return s.applyTargetRuntime(ctx, state, pid != 0)
}

func (s *Service) applyTargetRuntime(ctx context.Context, state *targetConfiguration, running bool) error {
	action, reason := "onestart", "failed_to_start_target_service"
	if running {
		action, reason = "onereload", "failed_to_reload_target_config"
	}
	if _, err := s.targetService(ctx, action); err != nil {
		return applyFailed(reason, nil)
	}
	settle, interval := s.targetTimings()
	if err := waitTarget(ctx, settle); err != nil {
		return applyFailed("target_runtime_check_timeout", nil)
	}
	lastIdentity, matches := "", 0
	for {
		identity, err := s.checkTargetRuntime(ctx, state)
		if err == nil {
			if identity == lastIdentity {
				matches++
			} else {
				matches, lastIdentity = 1, identity
			}
			if matches == 2 {
				return nil
			}
		} else {
			matches, lastIdentity = 0, ""
		}
		if err := waitTarget(ctx, interval); err != nil {
			return applyFailed("target_runtime_checks_pending", nil)
		}
	}
}

func (s *Service) StartTargets() error {
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()
	enabled, err := s.desiredTargetEnabled()
	if err != nil {
		return applyFailed("failed_to_read_target_service_state", nil)
	}
	ctx, cancel := s.targetContext()
	defer cancel()
	if !enabled {
		return s.stopTarget(ctx)
	}
	text, err := s.generateTargetConfigContext(ctx)
	if err == nil {
		var state *targetConfiguration
		state, err = s.prepareTargetConfig(ctx, text)
		if err == nil {
			return s.writePreparedTargets(ctx, text, state, true)
		}
	}
	data, err := os.ReadFile(s.targetPath())
	if err != nil {
		return applyFailed("target_startup_no_valid_owned_file", nil)
	}
	state, err := s.prepareTargetConfig(ctx, string(data))
	if err != nil {
		return applyFailed("target_startup_no_valid_owned_file", nil)
	}
	pid, err := s.targetPID(ctx)
	if err != nil && !errors.Is(err, errTargetStopped) {
		return applyFailed("target_startup_pending", nil)
	}
	if err := s.applyTargetRuntime(ctx, state, pid != 0); err != nil {
		return err
	}
	return applyFailed("target_startup_using_owned_file", nil)
}
