// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package iscsi

import (
	"fmt"
	"os"
	"strings"

	iscsiModels "github.com/alchemillahq/sylve/internal/db/models/iscsi"
	"github.com/alchemillahq/sylve/internal/logger"
	"github.com/alchemillahq/sylve/pkg/utils"
)

const configMarker = "# === This file is automatically generated by Sylve, don't edit! ==="
const configPath = "/etc/iscsi.conf"
const targetConfigPath = "/etc/ctl.conf"

func (s *Service) GenerateConfig() (string, error) {
	var initiators []iscsiModels.ISCSIInitiator
	if err := s.DB.Find(&initiators).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_initiators: %w", err)
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")

	for _, ini := range initiators {
		b.WriteString(fmt.Sprintf("%s {\n", ini.Nickname))
		b.WriteString(fmt.Sprintf("\ttargetaddress\t= %s;\n", ini.TargetAddress))
		b.WriteString(fmt.Sprintf("\ttargetname\t= %s;\n", ini.TargetName))
		if ini.InitiatorName != "" {
			b.WriteString(fmt.Sprintf("\tinitiatorname\t= %s;\n", ini.InitiatorName))
		}

		switch ini.AuthMethod {
		case "CHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %q;\n", ini.CHAPName))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %q;\n", ini.CHAPSecret))
		case "MutualCHAP":
			b.WriteString("\tauthmethod\t= CHAP;\n")
			b.WriteString(fmt.Sprintf("\tchapiname\t= %q;\n", ini.CHAPName))
			b.WriteString(fmt.Sprintf("\tchapsecret\t= %q;\n", ini.CHAPSecret))
			b.WriteString(fmt.Sprintf("\ttgtChapName\t= %q;\n", ini.TgtCHAPName))
			b.WriteString(fmt.Sprintf("\ttgtChapSecret\t= %q;\n", ini.TgtCHAPSecret))
		}

		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteConfig(reload bool) error {
	cfg, err := s.GenerateConfig()
	if err != nil {
		return err
	}

	if err := os.WriteFile(configPath, []byte(cfg), 0600); err != nil {
		return fmt.Errorf("failed_to_write_iscsi_config: %w", err)
	}

	if reload {
		if _, err := utils.RunCommandAllowExitCode("/usr/bin/iscsictl", []int{0, 1}, "-Ra"); err != nil {
			logger.L.Warn().Err(err).Msg("iscsictl -Ra returned unexpected error")
		}

		if _, err := utils.RunCommandAllowExitCode("/usr/bin/iscsictl", []int{0, 1}, "-Aa"); err != nil {
			logger.L.Warn().Err(err).Msg("iscsictl -Aa returned unexpected error")
		}
	}

	return nil
}

func (s *Service) GenerateTargetConfig() (string, error) {
	var targets []iscsiModels.ISCSITarget
	if err := s.DB.Preload("Portals").Preload("LUNs").Find(&targets).Error; err != nil {
		return "", fmt.Errorf("failed_to_load_targets: %w", err)
	}

	var b strings.Builder
	b.WriteString(configMarker + "\n\n")

	for _, tgt := range targets {
		b.WriteString(fmt.Sprintf("portal-group pg-%d {\n", tgt.ID))
		b.WriteString("\tdiscovery-auth-group no-authentication\n")
		for _, p := range tgt.Portals {
			port := p.Port
			if port == 0 {
				port = 3260
			}
			b.WriteString(fmt.Sprintf("\tlisten %s:%d\n", p.Address, port))
		}
		b.WriteString("}\n\n")

		if tgt.AuthMethod == "CHAP" || tgt.AuthMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("auth-group ag-%d {\n", tgt.ID))
			if tgt.AuthMethod == "MutualCHAP" {
				b.WriteString(fmt.Sprintf("\tchap-mutual %q %q %q %q\n",
					tgt.CHAPName, tgt.CHAPSecret, tgt.MutualCHAPName, tgt.MutualCHAPSecret))
			} else {
				b.WriteString(fmt.Sprintf("\tchap %q %q\n", tgt.CHAPName, tgt.CHAPSecret))
			}
			b.WriteString("}\n\n")
		}

		b.WriteString(fmt.Sprintf("target %s {\n", tgt.TargetName))
		if tgt.Alias != "" {
			b.WriteString(fmt.Sprintf("\talias %q\n", tgt.Alias))
		}
		b.WriteString(fmt.Sprintf("\tportal-group pg-%d\n", tgt.ID))
		if tgt.AuthMethod == "CHAP" || tgt.AuthMethod == "MutualCHAP" {
			b.WriteString(fmt.Sprintf("\tauth-group ag-%d\n", tgt.ID))
		} else {
			b.WriteString("\tauth-group no-authentication\n")
		}
		for _, lun := range tgt.LUNs {
			b.WriteString(fmt.Sprintf("\tlun %d {\n", lun.LUNNumber))
			b.WriteString(fmt.Sprintf("\t\tpath /dev/zvol/%s\n", lun.ZVol))
			b.WriteString("\t}\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func (s *Service) WriteTargetConfig(reload bool) error {
	cfg, err := s.GenerateTargetConfig()
	if err != nil {
		return err
	}

	if err := os.WriteFile(targetConfigPath, []byte(cfg), 0600); err != nil {
		return fmt.Errorf("failed_to_write_target_config: %w", err)
	}

	if reload {
		if _, err := utils.RunCommandAllowExitCode("/usr/sbin/service", []int{0, 1}, "ctld", "onerestart"); err != nil {
			logger.L.Warn().Err(err).Msg("service ctld onerestart returned unexpected error")
		}
	}

	return nil
}
