// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2025 The FreeBSD Foundation.
//
// This software was developed by Hayzam Sherif <hayzam@alchemilla.io>
// of Alchemilla Ventures Pvt. Ltd. <hello@alchemilla.io>,
// under sponsorship from the FreeBSD Foundation.

package jail

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/alchemillahq/gzfs"
	"github.com/alchemillahq/sylve/internal/config"
	"github.com/alchemillahq/sylve/internal/db/models"
	jailModels "github.com/alchemillahq/sylve/internal/db/models/jail"
	networkModels "github.com/alchemillahq/sylve/internal/db/models/network"
	vmModels "github.com/alchemillahq/sylve/internal/db/models/vm"
	clusterServiceInterfaces "github.com/alchemillahq/sylve/internal/interfaces/services/cluster"
	jailServiceInterfaces "github.com/alchemillahq/sylve/internal/interfaces/services/jail"
	networkServiceInterfaces "github.com/alchemillahq/sylve/internal/interfaces/services/network"
	systemServiceInterfaces "github.com/alchemillahq/sylve/internal/interfaces/services/system"
	"github.com/alchemillahq/sylve/internal/logger"
	"github.com/alchemillahq/sylve/pkg/utils"
	cpuid "github.com/klauspost/cpuid/v2"

	"gorm.io/gorm"
)

const JAIL_CONF_PREAMBLE = "# Sylve Jail Configuration File\n# Generated by Sylve - Editing this file manually is not recommended, changes will be overwritten.\n\n"

var _ jailServiceInterfaces.JailServiceInterface = (*Service)(nil)

type Service struct {
	DB             *gorm.DB
	NetworkService networkServiceInterfaces.NetworkServiceInterface
	System         systemServiceInterfaces.SystemServiceInterface
	GZFS           *gzfs.Client

	ctx               context.Context
	crudMutex         sync.Mutex
	createMutex       sync.Mutex
	actionMutex       sync.Mutex
	networkUpdateChan chan int64

	liveStateMutex     sync.RWMutex
	liveStateByCTID    map[uint]jailServiceInterfaces.State
	liveStateUpdatedAt time.Time
	hashCacheMutex     sync.RWMutex
	ctidHashByCTID     map[uint]string

	leftPanelRefreshEmitterMu sync.RWMutex
	leftPanelRefreshEmitter   func(reason string)
	guestIdentityChecker      clusterServiceInterfaces.GuestIdentityAvailabilityChecker

	usagePersistQueue   chan struct{}
	usageRetentionQueue chan struct{}
	monitorOnce         sync.Once

	bootstrapActiveMu sync.Map
}

func (s *Service) SetGuestIdentityAvailabilityChecker(
	checker clusterServiceInterfaces.GuestIdentityAvailabilityChecker,
) {
	s.guestIdentityChecker = checker
}

func NewJailService(
	db *gorm.DB,
	networkService networkServiceInterfaces.NetworkServiceInterface,
	systemService systemServiceInterfaces.SystemServiceInterface,
	gzfs *gzfs.Client) jailServiceInterfaces.JailServiceInterface {
	s := &Service{
		DB:                  db,
		NetworkService:      networkService,
		System:              systemService,
		GZFS:                gzfs,
		ctx:                 context.Background(),
		networkUpdateChan:   make(chan int64, 100),
		liveStateByCTID:     make(map[uint]jailServiceInterfaces.State),
		ctidHashByCTID:      make(map[uint]string),
		usagePersistQueue:   make(chan struct{}, 1),
		usageRetentionQueue: make(chan struct{}, 1),
	}

	go s.networkUpdateWorker()
	go s.jailUsagePersistWorker()
	go s.jailUsageRetentionWorker()
	go s.RecoverInterruptedBootstraps(context.Background())

	networkService.RegisterOnJailObjectUpdateCallback(func(jailIDs []uint) {
		for _, id := range jailIDs {
			select {
			case s.networkUpdateChan <- int64(id):
			default:
				logger.L.Warn().Msgf("Network update channel full, skipping jail %d", id)
			}
		}
	})

	return s
}

func (s *Service) IsJailEnabled() bool {
	var basicSettings models.BasicSettings
	err := s.DB.First(&basicSettings).Error

	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return false
		} else {
			return false
		}
	} else {
		if !slices.Contains(basicSettings.Services, models.Jails) {
			return false
		}
	}

	return true
}

func (s *Service) GetJails() ([]jailModels.Jail, error) {
	var jails []jailModels.Jail
	if err := s.DB.
		Preload("Storages").
		Preload("JailHooks").
		Preload("Networks").
		Preload("Networks.MacAddressObj").
		Preload("Networks.MacAddressObj.Entries").
		Preload("Networks.MacAddressObj.Resolutions").
		Preload("Networks.IPv4Obj").
		Preload("Networks.IPv4Obj.Entries").
		Preload("Networks.IPv4Obj.Resolutions").
		Preload("Networks.IPv4GwObj").
		Preload("Networks.IPv4GwObj.Entries").
		Preload("Networks.IPv4GwObj.Resolutions").
		Preload("Networks.IPv6Obj").
		Preload("Networks.IPv6Obj.Entries").
		Preload("Networks.IPv6Obj.Resolutions").
		Preload("Networks.IPv6GwObj").
		Preload("Networks.IPv6GwObj.Entries").
		Preload("Networks.IPv6GwObj.Resolutions").
		Find(&jails).Error; err != nil {
		logger.L.Error().Err(err).Msg("get_jails: failed to fetch jails")
		return nil, fmt.Errorf("failed_to_fetch_jails: %w", err)
	}
	return jails, nil
}

func (s *Service) GetJail(id uint) (*jailModels.Jail, error) {
	var jail jailModels.Jail
	if err := s.DB.
		Preload("Storages").
		Preload("JailHooks").
		Preload("Snapshots", func(db *gorm.DB) *gorm.DB {
			return db.Order("created_at ASC, id ASC")
		}).
		Preload("Networks").
		Preload("Networks.MacAddressObj").
		Preload("Networks.MacAddressObj.Entries").
		Preload("Networks.MacAddressObj.Resolutions").
		Preload("Networks.IPv4Obj").
		Preload("Networks.IPv4Obj.Entries").
		Preload("Networks.IPv4Obj.Resolutions").
		Preload("Networks.IPv4GwObj").
		Preload("Networks.IPv4GwObj.Entries").
		Preload("Networks.IPv4GwObj.Resolutions").
		Preload("Networks.IPv6Obj").
		Preload("Networks.IPv6Obj.Entries").
		Preload("Networks.IPv6Obj.Resolutions").
		Preload("Networks.IPv6GwObj").
		Preload("Networks.IPv6GwObj.Entries").
		Preload("Networks.IPv6GwObj.Resolutions").
		First(&jail, "id = ?", id).Error; err != nil {
		logger.L.Error().Err(err).Msgf("get_jail: failed to fetch jail with id %d", id)
		return nil, fmt.Errorf("failed_to_fetch_jail: %w", err)
	}

	return &jail, nil
}

func (s *Service) GetJailByCTID(ctId uint) (*jailModels.Jail, error) {
	var jail jailModels.Jail
	if err := s.DB.
		Preload("Storages").
		Preload("JailHooks").
		Preload("Snapshots", func(db *gorm.DB) *gorm.DB {
			return db.Order("created_at ASC, id ASC")
		}).
		Preload("Networks").
		Preload("Networks.MacAddressObj").
		Preload("Networks.MacAddressObj.Entries").
		Preload("Networks.MacAddressObj.Resolutions").
		Preload("Networks.IPv4Obj").
		Preload("Networks.IPv4Obj.Entries").
		Preload("Networks.IPv4Obj.Resolutions").
		Preload("Networks.IPv4GwObj").
		Preload("Networks.IPv4GwObj.Entries").
		Preload("Networks.IPv4GwObj.Resolutions").
		Preload("Networks.IPv6Obj").
		Preload("Networks.IPv6Obj.Entries").
		Preload("Networks.IPv6Obj.Resolutions").
		Preload("Networks.IPv6GwObj").
		Preload("Networks.IPv6GwObj.Entries").
		Preload("Networks.IPv6GwObj.Resolutions").
		First(&jail, "ct_id = ?", ctId).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			logger.L.Debug().Uint("ct_id", ctId).Msg("jail_not_found")
		} else {
			logger.L.Error().Err(err).Uint("ct_id", ctId).Msg("get_jail_by_ctid_failed")
		}
		return nil, fmt.Errorf("failed_to_fetch_jail_by_ctid: %w", err)
	}

	return &jail, nil
}

func (s *Service) GetJailsSimple() ([]jailServiceInterfaces.SimpleList, error) {
	var jails []jailModels.Jail

	if err := s.DB.Model(&jailModels.Jail{}).Select("id, name, ct_id").Find(&jails).Error; err != nil {
		logger.L.Error().Err(err).Msg("get_jails_simple: failed to fetch jails")
		return nil, fmt.Errorf("failed_to_fetch_jails_simple: %w", err)
	}

	var list []jailServiceInterfaces.SimpleList
	var states []jailServiceInterfaces.State

	states, err := s.GetStates()
	if err != nil {
		return nil, fmt.Errorf("failed_to_get_states: %w", err)
	}

	for _, jail := range jails {
		state := "INACTIVE"

		for _, s := range states {
			if s.CTID == jail.CTID {
				if strings.TrimSpace(s.State) == "" {
					state = "UNKNOWN"
				} else {
					state = s.State
				}
				break
			}
		}

		list = append(list, jailServiceInterfaces.SimpleList{
			ID:    jail.ID,
			Name:  jail.Name,
			CTID:  jail.CTID,
			State: state,
		})
	}

	return list, nil
}

func (s *Service) GetSimpleJail(identifier int, byCTID bool) (jailServiceInterfaces.SimpleList, error) {
	if !s.IsJailEnabled() {
		return jailServiceInterfaces.SimpleList{}, nil
	}

	var jail jailModels.Jail

	query := s.DB.
		Model(&jailModels.Jail{}).
		Select("id", "name", "ct_id")

	if byCTID {
		query = query.Where("ct_id = ?", identifier)
	} else {
		query = query.Where("id = ?", identifier)
	}

	if err := query.First(&jail).Error; err != nil {
		return jailServiceInterfaces.SimpleList{}, fmt.Errorf("failed_to_get_simple_jail: %w", err)
	}

	state, err := s.GetStateByCtId(uint(jail.CTID))
	if err != nil {
		state.State = "UNKNOWN"
	} else if strings.TrimSpace(state.State) == "" {
		state.State = "UNKNOWN"
	}

	simple := jailServiceInterfaces.SimpleList{
		ID:    jail.ID,
		CTID:  jail.CTID,
		Name:  jail.Name,
		State: state.State,
	}

	return simple, nil
}

func (s *Service) GetJailType(ctId uint) (jailModels.JailType, error) {
	var jail struct {
		Type jailModels.JailType
	}

	if err := s.DB.Model(&jailModels.Jail{}).
		Select("type").
		Where("ct_id = ?", ctId).
		First(&jail).Error; err != nil {
		logger.L.Error().Err(err).Msgf("get_jail_type: failed to fetch jail type for ct_id %d", ctId)
		return "", fmt.Errorf("failed_to_get_jail_type: %w", err)
	}

	return jail.Type, nil
}

func (s *Service) ValidateCreate(ctx context.Context, data jailServiceInterfaces.CreateJailRequest) error {
	if data.Name == "" || !utils.IsValidVMName(data.Name) {
		return fmt.Errorf("invalid_vm_name")
	}

	if data.Hostname != "" && !utils.IsValidHostname(data.Hostname) {
		return fmt.Errorf("invalid_hostname")
	}

	if data.CTID == nil || *data.CTID <= 0 || *data.CTID > 9999 {
		return fmt.Errorf("invalid_ct_id")
	}

	var existingCount int64
	if err := s.DB.Model(&jailModels.Jail{}).
		Where("ct_id = ?", *data.CTID).
		Count(&existingCount).Error; err != nil {
		return fmt.Errorf("failed_to_count_jails: %w", err)
	}
	if existingCount > 0 {
		return fmt.Errorf("jail_with_ctid_already_exists")
	}

	if data.VLAN != nil {
		vlan := *data.VLAN
		if vlan < 0 || vlan > 4095 {
			return fmt.Errorf("invalid_vlan")
		}
	}

	if err := s.validateNoStaleJailCreateArtifacts(ctx, *data.CTID); err != nil {
		return err
	}

	if data.Description != "" && (len(data.Description) < 1 || len(data.Description) > 1024) {
		return fmt.Errorf("invalid_description")
	}

	if data.Type != jailModels.JailTypeFreeBSD && data.Type != jailModels.JailTypeLinux {
		return fmt.Errorf("invalid_jail_type")
	}

	pools, err := s.System.GetUsablePools(ctx)
	if err != nil {
		return fmt.Errorf("failed_to_get_usable_pools: %w", err)
	}

	foundPool := ""
	for _, pool := range pools {
		if pool.Name == data.Pool {
			foundPool = pool.Name
			break
		}
	}

	if foundPool == "" {
		return fmt.Errorf("pool_not_found")
	}

	if data.Base != "" && data.BootstrapName != "" {
		return fmt.Errorf("base_and_bootstrap_name_are_mutually_exclusive")
	}

	if data.Base != "" {
		ex, err := s.FindBaseByUUID(data.Base)
		if err != nil {
			return err
		}

		if _, err := os.Stat(ex); os.IsNotExist(err) {
			return fmt.Errorf("base_path_does_not_exist")
		} else if err != nil {
			return fmt.Errorf("failed_to_stat_base_path: %w", err)
		}

		isDir, err := utils.IsDir(ex)
		if err != nil {
			return fmt.Errorf("failed_to_check_base_path_type: %w", err)
		}
		if !isDir {
			return fmt.Errorf("base_is_not_a_directory")
		}
	} else if data.BootstrapName != "" {
		bootstrapDataset := fmt.Sprintf("%s/sylve/bootstraps/%s", data.Pool, data.BootstrapName)
		bootstrapMount := fmt.Sprintf("/%s/sylve/bootstraps/%s", data.Pool, data.BootstrapName)

		var bRecord jailModels.JailBootstrap
		if err := s.DB.Where("pool = ? AND name = ?", data.Pool, data.BootstrapName).First(&bRecord).Error; err != nil {
			return fmt.Errorf("bootstrap_not_found")
		}
		if bRecord.Status != "completed" {
			return fmt.Errorf("bootstrap_not_completed")
		}

		ds, _ := s.GZFS.ZFS.Get(ctx, bootstrapDataset, false)
		if ds == nil {
			return fmt.Errorf("bootstrap_dataset_does_not_exist")
		}

		if _, err := os.Stat(bootstrapMount); os.IsNotExist(err) {
			return fmt.Errorf("bootstrap_mount_does_not_exist")
		}
	} else {
		return fmt.Errorf("download_uuid_or_bootstrap_name_required")
	}

	existingDataset, err := s.GZFS.ZFS.Get(ctx, fmt.Sprintf("%s/sylve/jails/%d", foundPool, *data.CTID), false)
	if err != nil {
		if !strings.Contains(err.Error(), "dataset does not exist") {
			return fmt.Errorf("failed_to_get_existing_datasets: %w", err)
		}
	}

	if existingDataset != nil {
		return fmt.Errorf("jail_base_fs_with_ctid_already_exists")
	}

	swAvailable := true
	mac := uint(0)
	dhcp := false
	slaac := false

	if data.SwitchName == "" {
		return fmt.Errorf("switch_name_required")
	} else if strings.ToLower(data.SwitchName) == "inherit" || strings.ToLower(data.SwitchName) == "none" {
		swAvailable = false
	}

	if swAvailable {
		found := false

		var stdSwitch networkModels.StandardSwitch
		if err := s.DB.First(&stdSwitch, "name = ?", data.SwitchName).Error; err == nil {
			found = true
		}

		var manualSwitch networkModels.ManualSwitch
		if err := s.DB.First(&manualSwitch, "name = ?", data.SwitchName).Error; err == nil {
			found = true
		}

		if !found {
			return fmt.Errorf("standard_switch_not_found")
		}
	}

	if data.MAC != nil {
		mac = uint(*data.MAC)
		if mac != 0 && swAvailable {
			used, _, err := s.NetworkService.IsObjectUsed(mac)
			if err != nil {
				return fmt.Errorf("failed_to_check_mac_usage: %w", err)
			}

			if used {
				return fmt.Errorf("mac_already_used")
			}
		}
	}

	if data.DHCP != nil {
		dhcp = *data.DHCP
	}

	if data.SLAAC != nil {
		slaac = *data.SLAAC
	}

	if swAvailable {
		if data.MACRaw != "" && !utils.IsValidMAC(data.MACRaw) {
			return fmt.Errorf("invalid_mac")
		}

		if data.IPv4Raw != "" && !utils.IsValidIPv4CIDR(data.IPv4Raw) {
			return fmt.Errorf("invalid_ipv4_cidr")
		}

		if data.IPv4GwRaw != "" && !utils.IsValidIPv4(data.IPv4GwRaw) {
			return fmt.Errorf("invalid_ipv4_gateway")
		}

		if data.IPv6Raw != "" && !utils.IsValidIPv6CIDR(data.IPv6Raw) {
			return fmt.Errorf("invalid_ipv6_cidr")
		}

		if data.IPv6GwRaw != "" && !utils.IsValidIPv6(data.IPv6GwRaw) {
			return fmt.Errorf("invalid_ipv6_gateway")
		}

		if !dhcp {
			if data.IPv4 != nil {
				ipv4Id := uint(*data.IPv4)
				if ipv4Id != 0 && data.IPv4Gw != nil {
					ipv4GwId := uint(*data.IPv4Gw)
					if ipv4GwId == 0 && data.IPv4GwRaw == "" {
						return fmt.Errorf("invalid_ipv4_gateway")
					}

					isUsed, _, err := s.NetworkService.IsObjectUsed(ipv4Id)
					if err != nil {
						return fmt.Errorf("failed_to_check_ipv4_usage: %w", err)
					}

					if isUsed {
						return fmt.Errorf("ipv4_already_used")
					}
				}
			}
		}

		if !slaac {
			if data.IPv6 != nil {
				ipv6Id := uint(*data.IPv6)

				if ipv6Id != 0 && data.IPv6Gw != nil {
					ipv6GwId := uint(*data.IPv6Gw)
					if ipv6GwId == 0 && data.IPv6GwRaw == "" {
						return fmt.Errorf("invalid_ipv6_gateway")
					}

					isUsed, _, err := s.NetworkService.IsObjectUsed(ipv6Id)
					if err != nil {
						return fmt.Errorf("failed_to_check_ipv6_usage: %w", err)
					}

					if isUsed {
						return fmt.Errorf("ipv6_already_used")
					}
				}
			}
		}
	}

	if data.Type == jailModels.JailTypeLinux {
		if dhcp || slaac {
			return fmt.Errorf("linux_jails_cannot_use_dhcp_or_slaac")
		}
	}

	if !utils.IsValidJailAllowedOpts(data.AllowedOptions) {
		return fmt.Errorf("invalid_jail_allowed_options")
	}

	if config.IsDevFSDisabled() && slices.Contains(data.AllowedOptions, "allow.mount.devfs") {
		return fmt.Errorf("devfs_management_disabled")
	}

	if data.StartOrder < 0 {
		return fmt.Errorf("start_order_must_be_greater_than_or_equal_to_0")
	}

	if s.guestIdentityChecker != nil {
		if err := s.guestIdentityChecker.RequireGuestIDAvailable(ctx, *data.CTID); err != nil {
			return err
		}
	}

	return nil
}

func isZFSDatasetMissingError(err error) bool {
	if err == nil {
		return false
	}

	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "dataset does not exist") ||
		strings.Contains(msg, "no such dataset") ||
		strings.Contains(msg, "does not exist")
}

func isZFSDatasetBusyError(err error) bool {
	if err == nil {
		return false
	}

	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "dataset is busy") ||
		strings.Contains(msg, "resource busy")
}

func isZFSDatasetDependentCloneError(err error) bool {
	if err == nil {
		return false
	}

	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "dependent clones") ||
		strings.Contains(msg, "filesystem has dependent clones")
}

func isRetriableZFSDestroyError(err error) bool {
	return isZFSDatasetBusyError(err) || isZFSDatasetDependentCloneError(err)
}

const jailDeleteStopTimeout = 10 * time.Second

type jailDeletePlan struct {
	jailID       uint
	ctID         uint
	rootDatasets []string
	macIDs       []uint
}

type jailDeleteRuntime struct {
	isRunning    func(uint) (bool, error)
	stop         func(uint) error
	removeConfig func(string) error
	removeDevfs  func(uint) error
}

func (s *Service) hostJailDeleteRuntime() jailDeleteRuntime {
	return jailDeleteRuntime{
		isRunning: s.IsJailRunning,
		stop: func(ctID uint) error {
			return s.JailAction(int(ctID), "stop")
		},
		removeConfig: os.RemoveAll,
		removeDevfs: func(ctID uint) error {
			if config.IsDevFSDisabled() {
				return nil
			}
			if _, err := os.Stat("/etc/devfs.rules"); err != nil {
				if errors.Is(err, os.ErrNotExist) {
					return nil
				}
				return fmt.Errorf("failed_to_stat_devfs_rules: %w", err)
			}
			return s.RemoveDevfsRulesForCTID(ctID)
		},
	}
}

func ensureJailStoppedForDelete(ctx context.Context, ctID uint, runtime jailDeleteRuntime) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if runtime.isRunning == nil || runtime.stop == nil {
		return fmt.Errorf("jail_delete_runtime_not_initialized")
	}

	running, err := runtime.isRunning(ctID)
	if err != nil {
		return fmt.Errorf("failed_to_check_jail_runtime_before_delete: %w", err)
	}
	if !running {
		return nil
	}

	if err := runtime.stop(ctID); err != nil {
		return fmt.Errorf("failed_to_stop_jail_before_delete: %w", err)
	}

	ticker := time.NewTicker(250 * time.Millisecond)
	defer ticker.Stop()
	timeout := time.NewTimer(jailDeleteStopTimeout)
	defer timeout.Stop()

	for {
		running, err = runtime.isRunning(ctID)
		if err != nil {
			return fmt.Errorf("failed_to_verify_jail_stopped_before_delete: %w", err)
		}
		if !running {
			return nil
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("jail_stop_verification_canceled: %w", ctx.Err())
		case <-timeout.C:
			return fmt.Errorf("jail_failed_to_stop_before_delete")
		case <-ticker.C:
		}
	}
}

func (s *Service) destroyStorageDatasetForDelete(ctx context.Context, datasetName string) error {
	if s.GZFS == nil || s.GZFS.ZFS == nil {
		return fmt.Errorf("zfs_client_not_initialized")
	}

	datasetName = strings.TrimSpace(datasetName)
	if datasetName == "" {
		return nil
	}

	const maxAttempts = 8
	const retryDelay = 750 * time.Millisecond

	var lastErr error

	for attempt := 1; attempt <= maxAttempts; attempt++ {
		dataset, err := s.GZFS.ZFS.Get(ctx, datasetName, true)
		if err != nil {
			if isZFSDatasetMissingError(err) {
				return nil
			}
			return fmt.Errorf("failed_to_get_dataset_for_storage: %w", err)
		}
		if dataset == nil {
			return nil
		}

		err = dataset.Destroy(ctx, true, false)
		if err == nil || isZFSDatasetMissingError(err) {
			return nil
		}

		lastErr = err
		if attempt == maxAttempts || !isRetriableZFSDestroyError(lastErr) {
			break
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("failed_to_destroy_storage_dataset_canceled: %w", ctx.Err())
		case <-time.After(retryDelay):
		}
	}

	return fmt.Errorf("failed_to_destroy_storage_dataset_after_retries: %w", lastErr)
}

func appendJailCreateCleanupWarning(warnings *[]string, ctid uint, code string, err error) {
	message := code
	if err != nil {
		message = fmt.Sprintf("%s: %v", code, err)
		logger.L.Warn().Uint("ctid", ctid).Err(err).Msg(code)
	} else {
		logger.L.Warn().Uint("ctid", ctid).Msg(code)
	}

	*warnings = append(*warnings, message)
}

func uniqueUintValues(values []uint) []uint {
	if len(values) == 0 {
		return []uint{}
	}

	seen := make(map[uint]struct{}, len(values))
	out := make([]uint, 0, len(values))
	for _, value := range values {
		if value == 0 {
			continue
		}

		if _, exists := seen[value]; exists {
			continue
		}

		seen[value] = struct{}{}
		out = append(out, value)
	}

	return out
}

func (s *Service) hasStaleJailRootDatasetForCreate(ctx context.Context, ctid uint) (bool, error) {
	if s.System == nil {
		return false, fmt.Errorf("system_service_not_initialized")
	}

	if s.GZFS == nil || s.GZFS.ZFS == nil {
		return false, fmt.Errorf("zfs_client_not_initialized")
	}

	pools, err := s.System.GetUsablePools(ctx)
	if err != nil {
		return false, fmt.Errorf("failed_to_list_usable_pools_for_jail_create_precheck: %w", err)
	}

	for _, pool := range pools {
		if pool == nil {
			continue
		}

		poolName := strings.TrimSpace(pool.Name)
		if poolName == "" {
			continue
		}

		datasetName := fmt.Sprintf("%s/sylve/jails/%d", poolName, ctid)
		ds, getErr := s.GZFS.ZFS.Get(ctx, datasetName, false)
		if getErr != nil {
			if isZFSDatasetMissingError(getErr) {
				continue
			}

			return false, fmt.Errorf("failed_to_check_jail_root_dataset_for_create_precheck: %w", getErr)
		}

		if ds != nil {
			return true, nil
		}
	}

	return false, nil
}

func (s *Service) validateNoStaleJailCreateArtifacts(ctx context.Context, ctid uint) error {
	rootDatasetExists, err := s.hasStaleJailRootDatasetForCreate(ctx, ctid)
	if err != nil {
		return err
	}

	if rootDatasetExists {
		return fmt.Errorf(
			"jail_create_stale_artifacts_detected: ctid=%d root_dataset_exists=%t",
			ctid,
			rootDatasetExists,
		)
	}

	return nil
}

func (s *Service) forceRemoveJailRuntimeArtifacts(ctid uint, warnings *[]string) {
	jailsPath, err := config.GetJailsPath()
	if err != nil {
		appendJailCreateCleanupWarning(warnings, ctid, "failed_to_get_jails_path_for_create_rollback", err)
		return
	}

	jailDir := filepath.Join(jailsPath, fmt.Sprintf("%d", ctid))
	if _, statErr := os.Stat(jailDir); statErr == nil {
		if removeErr := os.RemoveAll(jailDir); removeErr != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_remove_jail_runtime_dir_for_create_rollback", removeErr)
		}
	}
}

func (s *Service) forceRemoveJailZFSDatasets(ctx context.Context, ctid uint, fallbackPool string, warnings *[]string) {
	if s.GZFS == nil || s.GZFS.ZFS == nil {
		appendJailCreateCleanupWarning(warnings, ctid, "zfs_client_not_initialized_during_jail_create_rollback", fmt.Errorf("zfs_client_not_initialized"))
		return
	}

	poolNames := make(map[string]struct{})
	if fallbackPool = strings.TrimSpace(fallbackPool); fallbackPool != "" {
		poolNames[fallbackPool] = struct{}{}
	}

	if s.System != nil {
		pools, err := s.System.GetUsablePools(ctx)
		if err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_list_usable_pools_for_jail_create_rollback", err)
		} else {
			for _, pool := range pools {
				if pool == nil {
					continue
				}

				poolName := strings.TrimSpace(pool.Name)
				if poolName == "" {
					continue
				}

				poolNames[poolName] = struct{}{}
			}
		}
	}

	var jailIDs []uint
	if err := s.DB.Model(&jailModels.Jail{}).
		Where("ct_id = ?", ctid).
		Pluck("id", &jailIDs).Error; err != nil {
		appendJailCreateCleanupWarning(warnings, ctid, "failed_to_lookup_jail_ids_for_zfs_rollback", err)
	}

	if len(jailIDs) > 0 {
		var storagePools []string
		if err := s.DB.Model(&jailModels.Storage{}).
			Where("jid IN ?", jailIDs).
			Where("pool IS NOT NULL AND pool <> ''").
			Pluck("pool", &storagePools).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_lookup_jail_storage_pools_for_zfs_rollback", err)
		} else {
			for _, pool := range storagePools {
				poolName := strings.TrimSpace(pool)
				if poolName == "" {
					continue
				}

				poolNames[poolName] = struct{}{}
			}
		}
	}

	for poolName := range poolNames {
		datasetName := fmt.Sprintf("%s/sylve/jails/%d", poolName, ctid)

		ds, getErr := s.GZFS.ZFS.Get(ctx, datasetName, false)
		if getErr != nil {
			if isZFSDatasetMissingError(getErr) {
				continue
			}
			appendJailCreateCleanupWarning(
				warnings,
				ctid,
				fmt.Sprintf("failed_to_get_jail_dataset_%s_for_create_rollback", datasetName),
				getErr,
			)
			continue
		}

		if ds == nil {
			continue
		}

		if destroyErr := ds.Destroy(ctx, true, false); destroyErr != nil && !isZFSDatasetMissingError(destroyErr) {
			appendJailCreateCleanupWarning(
				warnings,
				ctid,
				fmt.Sprintf("failed_to_destroy_jail_dataset_%s_for_create_rollback", datasetName),
				destroyErr,
			)
		}
	}
}

func (s *Service) forceRemoveJailDBRecords(ctid uint, warnings *[]string) {
	var jailIDs []uint
	if err := s.DB.Model(&jailModels.Jail{}).
		Where("ct_id = ?", ctid).
		Pluck("id", &jailIDs).Error; err != nil {
		appendJailCreateCleanupWarning(warnings, ctid, "failed_to_lookup_jail_ids_for_db_rollback", err)
		return
	}

	if len(jailIDs) > 0 {
		if err := s.DB.Where("jid IN ?", jailIDs).Delete(&jailModels.Network{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_networks_for_create_rollback", err)
		}
		if err := s.DB.Where("jid IN ?", jailIDs).Delete(&jailModels.JailHooks{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_hooks_for_create_rollback", err)
		}
		if err := s.DB.Where("jid IN ?", jailIDs).Delete(&jailModels.JailStats{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_stats_for_create_rollback", err)
		}
		if err := s.DB.Where("jid IN ?", jailIDs).Delete(&jailModels.JailSnapshot{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_snapshots_for_create_rollback", err)
		}
		if err := s.DB.Where("jid IN ?", jailIDs).Delete(&jailModels.Storage{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_storages_for_create_rollback", err)
		}
		if err := s.DB.Where("id IN ?", jailIDs).Delete(&jailModels.Jail{}).Error; err != nil {
			appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_rows_for_create_rollback", err)
		}
	}

	if err := s.DB.Where("ct_id = ?", ctid).Delete(&jailModels.Jail{}).Error; err != nil {
		appendJailCreateCleanupWarning(warnings, ctid, "failed_to_delete_jail_rows_by_ctid_for_create_rollback", err)
	}
}

func (s *Service) cleanupAutoCreatedJailCreateObjects(ctid uint, autoCreatedIDs []uint, warnings *[]string) {
	for _, objID := range uniqueUintValues(autoCreatedIDs) {
		if s.NetworkService != nil {
			used, _, err := s.NetworkService.IsObjectUsed(objID)
			if err != nil {
				appendJailCreateCleanupWarning(
					warnings,
					ctid,
					fmt.Sprintf("failed_to_check_auto_created_object_usage_%d_during_create_rollback", objID),
					err,
				)
				continue
			}
			if used {
				continue
			}
		} else {
			var refs int64

			if err := s.DB.Model(&vmModels.Network{}).
				Where("mac_id = ?", objID).
				Count(&refs).Error; err != nil {
				appendJailCreateCleanupWarning(
					warnings,
					ctid,
					fmt.Sprintf("failed_to_count_vm_refs_for_auto_object_%d_during_create_rollback", objID),
					err,
				)
				continue
			}
			if refs > 0 {
				continue
			}

			if err := s.DB.Model(&jailModels.Network{}).
				Where("mac_id = ? OR ipv4_id = ? OR ipv4_gw_id = ? OR ipv6_id = ? OR ipv6_gw_id = ?",
					objID, objID, objID, objID, objID).
				Count(&refs).Error; err != nil {
				appendJailCreateCleanupWarning(
					warnings,
					ctid,
					fmt.Sprintf("failed_to_count_jail_refs_for_auto_object_%d_during_create_rollback", objID),
					err,
				)
				continue
			}
			if refs > 0 {
				continue
			}

			if err := s.DB.Model(&networkModels.DHCPStaticLease{}).
				Where("mac_object_id = ?", objID).
				Count(&refs).Error; err != nil {
				appendJailCreateCleanupWarning(
					warnings,
					ctid,
					fmt.Sprintf("failed_to_count_dhcp_refs_for_auto_object_%d_during_create_rollback", objID),
					err,
				)
				continue
			}
			if refs > 0 {
				continue
			}
		}

		if err := s.DB.Where("object_id = ?", objID).Delete(&networkModels.ObjectEntry{}).Error; err != nil {
			appendJailCreateCleanupWarning(
				warnings,
				ctid,
				fmt.Sprintf("failed_to_delete_auto_created_object_entries_%d_during_create_rollback", objID),
				err,
			)
		}
		if err := s.DB.Where("object_id = ?", objID).Delete(&networkModels.ObjectResolution{}).Error; err != nil {
			appendJailCreateCleanupWarning(
				warnings,
				ctid,
				fmt.Sprintf("failed_to_delete_auto_created_object_resolutions_%d_during_create_rollback", objID),
				err,
			)
		}
		if err := s.DB.Delete(&networkModels.Object{}, objID).Error; err != nil {
			appendJailCreateCleanupWarning(
				warnings,
				ctid,
				fmt.Sprintf("failed_to_delete_auto_created_object_%d_during_create_rollback", objID),
				err,
			)
		}
	}
}

func (s *Service) cleanupFailedJailCreate(ctid uint, fallbackPool string, autoCreatedIDs []uint) {
	if ctid == 0 {
		return
	}

	cleanupCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	warnings := make([]string, 0)

	s.forceRemoveJailRuntimeArtifacts(ctid, &warnings)
	s.forceRemoveJailZFSDatasets(cleanupCtx, ctid, fallbackPool, &warnings)
	s.forceRemoveJailDBRecords(ctid, &warnings)
	s.cleanupAutoCreatedJailCreateObjects(ctid, autoCreatedIDs, &warnings)

	if !config.IsDevFSDisabled() {
		if _, statErr := os.Stat("/etc/devfs.rules"); statErr == nil {
			if err := s.RemoveDevfsRulesForCTID(ctid); err != nil {
				appendJailCreateCleanupWarning(&warnings, ctid, "failed_to_remove_devfs_rules_for_create_rollback", err)
			}
		}
	}

	if len(warnings) > 0 {
		logger.L.Warn().
			Uint("ctid", ctid).
			Strs("warnings", warnings).
			Msg("jail_create_rollback_cleanup_warnings")
	}
}

func (s *Service) CreateHardwareConfig(data jailModels.Jail) (string, string, error) {
	cpuCores := data.Cores
	memory := data.Memory

	cpuCfg := ""
	memoryCfg := ""

	ctidHash := s.GetCTIDHash(data.CTID)

	jails, err := s.GetJails()
	if err != nil {
		return "", "", fmt.Errorf("failed_to_get_jails: %w", err)
	}

	numLogicalCores := cpuid.CPU.LogicalCores
	coreUsage := map[int]int{}
	for _, jail := range jails {
		for _, core := range jail.CPUSet {
			coreUsage[core]++
		}
	}

	type CoreCount struct {
		Core  int
		Count int
	}

	var allCores []CoreCount
	for i := 0; i < numLogicalCores; i++ {
		allCores = append(allCores, CoreCount{Core: i, Count: coreUsage[i]})
	}

	sort.Slice(allCores, func(i, j int) bool {
		return allCores[i].Count < allCores[j].Count
	})

	if cpuCores > 0 && len(allCores) > 0 {
		selectedCores := []int{}
		for i := 0; i < cpuCores && i < len(allCores); i++ {
			selectedCores = append(selectedCores, allCores[i].Core)
		}
		if len(selectedCores) > 0 {
			coreListStr := strings.Trim(strings.Replace(fmt.Sprint(selectedCores), " ", ",", -1), "[]")
			cpuCfg = fmt.Sprintf("cpuset -l %s -j %s", coreListStr, ctidHash)
		}
	}

	if memory > 0 {
		memoryMB := memory / (1024 * 1024)
		memoryCfg = fmt.Sprintf("rctl -a jail:%s:memoryuse:deny=%dM", ctidHash, memoryMB)
	}

	return cpuCfg, memoryCfg, nil
}

func (s *Service) CreateJailConfig(data jailModels.Jail, mountPoint string, mac string) (string, error) {
	ctid := data.CTID

	if mountPoint == "" {
		return "", fmt.Errorf("mount_point_not_found")
	}

	jailsPath, err := config.GetJailsPath()
	if err != nil {
		return "", fmt.Errorf("failed_to_get_jails_path: %w", err)
	}

	// Append devfs rules if provided
	if !config.IsDevFSDisabled() && data.DevFSRuleset != "" {
		devFsRulesetPath := filepath.Join("/etc", "devfs.rules")
		f, err := os.OpenFile(devFsRulesetPath, os.O_APPEND|os.O_WRONLY, 0600)
		if err != nil {
			return "", fmt.Errorf("failed_to_open_devfs_rules_file: %w", err)
		}

		rule := fmt.Sprintf("\n[devfsrules_jails_sylve_%d=%d]\n", ctid, ctid)
		rule += "add include $devfsrules_jails\n"
		rule += data.DevFSRuleset + "\n"
		if _, err := f.WriteString(rule); err != nil {
			f.Close()
			return "", fmt.Errorf("failed_to_write_devfs_rules: %w", err)
		}
		f.Close()

		if _, err := utils.RunCommand("service", "devfs", "restart"); err != nil {
			return "", fmt.Errorf("failed_to_reload_devfs_rules: %w", err)
		}
	}

	// Host-side jail directory (config/logs/scripts managed by Sylve)
	jailDir := filepath.Join(jailsPath, fmt.Sprintf("%d", ctid))
	hostScriptsDir := filepath.Join(jailDir, "scripts")
	if err := os.MkdirAll(hostScriptsDir, 0755); err != nil {
		return "", fmt.Errorf("failed_to_create_jail_scripts_directory: %w", err)
	}

	// Inside-jail scripts dir: /usr/local/sylve/scripts
	jailScriptsRelDir := filepath.Join("usr", "local", "sylve", "scripts")
	jailScriptsFsDir := filepath.Join(mountPoint, jailScriptsRelDir)
	if err := os.MkdirAll(jailScriptsFsDir, 0755); err != nil {
		return "", fmt.Errorf("failed_to_create_in_jail_scripts_directory: %w", err)
	}

	var rcConfPath string

	if data.Type == jailModels.JailTypeFreeBSD {
		rcConfPath = filepath.Join(mountPoint, "etc", "rc.conf")
		if _, err := os.Stat(rcConfPath); os.IsNotExist(err) {
			if err := os.WriteFile(rcConfPath, []byte(""), 0644); err != nil {
				return "", fmt.Errorf("failed_to_create_rc_conf: %w", err)
			}
		}
	}

	logPath := filepath.Join(jailDir, fmt.Sprintf("%d.log", ctid))

	writeScript := func(path, content string, executable bool) error {
		// If completely empty, just write a minimal shell script
		if strings.TrimSpace(content) == "" {
			content = "#!/bin/sh\n"
		} else {
			// Strip leading blank lines so we can ensure the shebang is line 1
			trimmed := strings.TrimLeft(content, "\r\n")

			if !strings.HasPrefix(trimmed, "#!") {
				// Prepend shebang if it's not already there
				content = "#!/bin/sh\n" + trimmed
			} else {
				// Already has a shebang at the top after trimming blank lines
				content = trimmed
			}
		}

		mode := os.FileMode(0644)
		if executable {
			mode = 0755
		}

		return os.WriteFile(path, []byte(content), mode)
	}

	var cfg string
	ctidHash := s.GetCTIDHash(ctid)

	cfg += JAIL_CONF_PREAMBLE
	cfg += fmt.Sprintf("%s {\n", ctidHash)
	cfg += fmt.Sprintf("\t$ctid = \"%s\";\n", ctidHash)

	if data.Hostname != "" {
		cfg += fmt.Sprintf("\thost.hostname = \"%s\";\n", data.Hostname)
	} else {
		cfg += fmt.Sprintf("\thost.hostname = \"%s\";\n", utils.MakeValidHostname(data.Name))
	}

	// Jail root filesystem path
	cfg += fmt.Sprintf("\tpath = \"%s\";\n\n", mountPoint)

	// Allowed options
	if len(data.AllowedOptions) > 0 {
		for _, opt := range data.AllowedOptions {
			cfg += fmt.Sprintf("\t%s;\n", opt)
		}
		cfg += "\n"
	}

	// devfs mount and rules
	if !config.IsDevFSDisabled() && data.AllowedOptions != nil && utils.StringInSlice("allow.mount.devfs", data.AllowedOptions) {
		cfg += "\tmount.devfs;\n"

		if data.DevFSRuleset != "" {
			cfg += fmt.Sprintf("\tdevfs_ruleset=%d;\n\n", ctid)
		} else {
			// default ruleset
			cfg += "\tdevfs_ruleset=61181;\n\n"
		}
	}

	var preStartCfg, startCfg, postStartCfg, preStopCfg, stopCfg, postStopCfg string

	if len(data.Networks) > 0 {
		if mac == "" {
			return "", fmt.Errorf("missing_mac_for_network")
		}

		var networkId string

		network := data.Networks[0]
		if network.SwitchID > 0 {
			// Use network database ID for unique interface naming
			networkId = fmt.Sprintf("net%d", network.ID)

			cfg += "\tvnet;\n"
			cfg += fmt.Sprintf("\tvnet.interface = \"%s_%sb\";\n", ctidHash, networkId)

			prevMAC, err := utils.PreviousMAC(mac)
			if err != nil {
				return "", fmt.Errorf("failed to get previous mac: %w", err)
			}

			// ### Start Sylve-Managed Network ###
			preStartCfg += "### Start Sylve-Managed Network ###\n\n"
			preStartCfg += fmt.Sprintf("# Setup Network Interface %s_%sb\n", ctidHash, networkId)
			preStartCfg += fmt.Sprintf("ifconfig %s_%sa ether %s up\n", ctidHash, networkId, prevMAC)
			preStartCfg += fmt.Sprintf("ifconfig %s_%sb ether %s up\n", ctidHash, networkId, mac)
			preStartCfg += "\n"

			bridgeName, err := s.NetworkService.GetBridgeNameByIDType(network.SwitchID, network.SwitchType)
			if err != nil {
				return "", fmt.Errorf("failed to get bridge name: %w", err)
			}

			epairA := fmt.Sprintf("%s_%sa", ctidHash, networkId)

			if network.VLAN != nil && *network.VLAN > 0 {
				vlanIface := fmt.Sprintf("%s.%d", epairA, *network.VLAN)
				preStartCfg += fmt.Sprintf("if ! ifconfig %s > /dev/null 2>&1; then\n", vlanIface)
				preStartCfg += fmt.Sprintf("\tifconfig vlan create vlandev %s vlan %d name %s group svm-vlan up\n", epairA, *network.VLAN, vlanIface)
				preStartCfg += "fi\n"
				preStartCfg += fmt.Sprintf("if ! ifconfig %s | grep -qw %s; then\n", bridgeName, vlanIface)
				preStartCfg += fmt.Sprintf("\tifconfig %s addm %s 2>&1 || true\n", bridgeName, vlanIface)
				preStartCfg += "fi\n"
			} else {
				preStartCfg += fmt.Sprintf("if ! ifconfig %s | grep -qw %s; then\n", bridgeName, epairA)
				preStartCfg += fmt.Sprintf("\tifconfig %s addm %s 2>&1 || true\n", bridgeName, epairA)
				preStartCfg += "fi\n"
			}
			preStartCfg += fmt.Sprintf("# End Setup Network Interface %s_%sb\n", ctidHash, networkId)
			preStartCfg += "### End Sylve-Managed Network ###\n\n"
		}

		// DHCP / SLAAC / static config inside jail — FreeBSD JAILS ONLY
		if data.Type == jailModels.JailTypeFreeBSD {
			ifName := fmt.Sprintf("ifconfig_%s_%sb", ctidHash, networkId)
			lineDHCP := fmt.Sprintf("%s=\"SYNCDHCP\"\n", ifName)
			ipv6Name := fmt.Sprintf("%s_ipv6", ifName)
			lineSLAAC := fmt.Sprintf("%s=\"inet6 accept_rtadv\"\n", ipv6Name)
			lineRTSold := "rtsold_enable=\"YES\"\n"

			rcF, err := os.OpenFile(rcConfPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
			if err != nil {
				return "", fmt.Errorf("open rc.conf: %w", err)
			}

			defer rcF.Close()

			b, err := os.ReadFile(rcConfPath)
			if err != nil && !os.IsNotExist(err) {
				return "", fmt.Errorf("read rc.conf: %w", err)
			}

			existing := string(b)
			var rcToAppend strings.Builder

			if network.DHCP {
				if !strings.Contains(existing, lineDHCP) {
					rcToAppend.WriteString(lineDHCP)
				}
			} else {
				if (network.IPv4ID != nil && *network.IPv4ID > 0) && (network.IPv4GwID != nil && *network.IPv4GwID > 0) {
					ipv4Addr, err := s.NetworkService.GetObjectEntryByID(*network.IPv4ID)
					if err != nil {
						return "", fmt.Errorf("failed_to_get_ipv4_address_object: %w", err)
					}

					ip, mask, err := utils.SplitIPv4AndMask(ipv4Addr)
					if err != nil {
						return "", fmt.Errorf("failed_to_split_ipv4_address_and_mask: %w", err)
					}

					lineIPv4 := fmt.Sprintf("%s=\"inet %s netmask %s\"\n", ifName, ip, mask)
					if !strings.Contains(existing, lineIPv4) {
						rcToAppend.WriteString(lineIPv4)
					}

					if network.IPv4GwID != nil && *network.IPv4GwID > 0 {
						ipv4GwAddr, err := s.NetworkService.GetObjectEntryByID(*network.IPv4GwID)
						if err != nil {
							return "", fmt.Errorf("failed_to_get_ipv4_gateway_object: %w", err)
						}

						lineGw4 := fmt.Sprintf("defaultrouter=\"%s\"\n", ipv4GwAddr)
						if !strings.Contains(existing, lineGw4) {
							rcToAppend.WriteString(lineGw4)
						}
					}
				}
			}

			if network.SLAAC {
				if !strings.Contains(existing, lineSLAAC) {
					rcToAppend.WriteString(lineSLAAC)
				}

				if !strings.Contains(existing, lineRTSold) {
					rcToAppend.WriteString(lineRTSold)
				}
			}

			if network.IPv6ID != nil && *network.IPv6ID > 0 {
				ipv6Addr, err := s.NetworkService.GetObjectEntryByID(*network.IPv6ID)
				if err != nil {
					return "", fmt.Errorf("failed_to_get_ipv6_address_object: %w", err)
				}

				lineIPv6 := fmt.Sprintf("%s=\"inet6 %s\"\n", ipv6Name, ipv6Addr)
				if !strings.Contains(existing, lineIPv6) {
					rcToAppend.WriteString(lineIPv6)
				}
			}

			if network.IPv6GwID != nil && *network.IPv6GwID > 0 {
				ipv6GwAddr, err := s.NetworkService.GetObjectEntryByID(*network.IPv6GwID)
				if err != nil {
					return "", fmt.Errorf("failed_to_get_ipv6_gateway_object: %w", err)
				}

				lineGw6 := fmt.Sprintf("ipv6_defaultrouter=\"%s\"\n", ipv6GwAddr)
				if !strings.Contains(existing, lineGw6) {
					rcToAppend.WriteString(lineGw6)
				}
			}

			if len(rcToAppend.String()) > 0 {
				if _, err := rcF.WriteString(rcToAppend.String()); err != nil {
					return "", fmt.Errorf("append to rc.conf: %w", err)
				}
			}
		}
	}

	var inheritLines strings.Builder

	if data.InheritIPv4 {
		inheritLines.WriteString("\tip4=\"inherit\";\n")
	}

	if data.InheritIPv6 {
		inheritLines.WriteString("\tip6=\"inherit\";\n")
	}

	if inheritLines.Len() > 0 {
		cfg += fmt.Sprintf("\n%s\n", inheritLines.String())
	}

	for _, hook := range data.JailHooks {
		if !hook.Enabled || hook.Script == "" {
			continue
		}

		add := func(buf *string) {
			*buf += "### Start User-Managed Hook ###\n"
			*buf += hook.Script + "\n"
			*buf += "### End User-Managed Hook ###\n"
		}

		switch hook.Phase {
		case jailModels.JailHookPhasePreStart:
			add(&preStartCfg)
		case jailModels.JailHookPhaseStart:
			add(&startCfg)
		case jailModels.JailHookPhasePostStart:
			add(&postStartCfg)
		case jailModels.JailHookPhasePreStop:
			add(&preStopCfg)
		case jailModels.JailHookPhaseStop:
			add(&stopCfg)
		case jailModels.JailHookPhasePostStop:
			add(&postStopCfg)
		}
	}

	cpuCfg, memoryCfg, err := s.CreateHardwareConfig(data)
	if err != nil {
		return "", fmt.Errorf("failed_to_create_hardware_config: %w", err)
	}

	if cpuCfg != "" {
		postStartCfg += cpuCfg + "\n"
	}

	if memoryCfg != "" {
		postStartCfg += memoryCfg + "\n"
	}

	if cpuCfg != "" || memoryCfg != "" {
		postStartCfg += "\n"
	}

	// Logging & env
	cfg += fmt.Sprintf("\texec.consolelog += \"%s\";\n", logPath)
	if data.CleanEnvironment {
		cfg += "\texec.clean;\n"
	}

	// --- Write scripts & wire them into exec.* ---

	// prestart: host environment
	preStartHostPath := filepath.Join(hostScriptsDir, "pre-start.sh")
	if err := writeScript(preStartHostPath, preStartCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_pre_start_script: %w", err)
	}
	if preStartCfg != "" {
		cfg += fmt.Sprintf("\texec.prestart += \"%s\";\n", preStartHostPath)
	}

	// start: jail environment -> needs inside-jail path
	startHostPath := filepath.Join(hostScriptsDir, "start.sh")
	if err := writeScript(startHostPath, startCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_start_script: %w", err)
	}
	startJailFsPath := filepath.Join(jailScriptsFsDir, "start.sh")
	if err := writeScript(startJailFsPath, startCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_in_jail_start_script: %w", err)
	}
	startJailExecPath := "/" + filepath.Join(jailScriptsRelDir, "start.sh")
	if startCfg != "" {
		cfg += fmt.Sprintf("\texec.start += \"%s\";\n", startJailExecPath)
	}

	// poststart: host environment
	postStartHostPath := filepath.Join(hostScriptsDir, "post-start.sh")
	if err := writeScript(postStartHostPath, postStartCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_post_start_script: %w", err)
	}
	if postStartCfg != "" {
		cfg += fmt.Sprintf("\texec.poststart += \"%s\";\n", postStartHostPath)
	}

	// prestop: host environment
	preStopHostPath := filepath.Join(hostScriptsDir, "pre-stop.sh")
	if err := writeScript(preStopHostPath, preStopCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_pre_stop_script: %w", err)
	}
	if preStopCfg != "" {
		cfg += fmt.Sprintf("\texec.prestop += \"%s\";\n", preStopHostPath)
	}

	// stop: jail environment -> needs inside-jail path
	stopHostPath := filepath.Join(hostScriptsDir, "stop.sh")
	if err := writeScript(stopHostPath, stopCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_stop_script: %w", err)
	}
	stopJailFsPath := filepath.Join(jailScriptsFsDir, "stop.sh")
	if err := writeScript(stopJailFsPath, stopCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_in_jail_stop_script: %w", err)
	}
	stopJailExecPath := "/" + filepath.Join(jailScriptsRelDir, "stop.sh")
	if stopCfg != "" {
		cfg += fmt.Sprintf("\texec.stop += \"%s\";\n", stopJailExecPath)
	}

	// poststop: host environment
	postStopHostPath := filepath.Join(hostScriptsDir, "post-stop.sh")
	if err := writeScript(postStopHostPath, postStopCfg, true); err != nil {
		return "", fmt.Errorf("failed_to_write_post_stop_script: %w", err)
	}
	if postStopCfg != "" {
		cfg += fmt.Sprintf("\texec.poststop += \"%s\";\n", postStopHostPath)
	}

	// fstab if any (mount.fstab, host-side path)
	if data.Fstab != "" {
		fstabPath := filepath.Join(jailDir, "fstab")
		if err := os.WriteFile(fstabPath, []byte(data.Fstab), 0644); err != nil {
			return "", fmt.Errorf("failed_to_write_fstab_file: %w", err)
		}
		cfg += fmt.Sprintf("\tmount.fstab = \"%s\";\n\n", fstabPath)
	}

	// User additional options
	if data.AdditionalOptions != "" {
		cfg += "\n### These are user-defined additional options ###\n"
		cfg += "\n" + data.AdditionalOptions + "\n"
	}

	if data.MetadataMeta != "" {
		cfg += fmt.Sprintf("\tmeta = \"%s\";\n", data.MetadataMeta)
	}

	if data.MetadataEnv != "" {
		cfg += fmt.Sprintf("\tenv = \"%s\";\n", data.MetadataEnv)
	}

	cfg += "\n\tpersist;\n"
	cfg += "}\n"

	return cfg, nil
}

func (s *Service) rollbackJailCreation(ctx context.Context, state *jailServiceInterfaces.JailCreationState) {
	if state == nil {
		return
	}

	if state.JailDir != "" {
		if err := os.RemoveAll(state.JailDir); err != nil {
			logger.L.Error().Err(err).Str("jail_dir", state.JailDir).
				Msg("rollback_jail_creation: failed to remove jail directory")
		}
	}

	if state.DatasetName != "" {
		ds, err := s.GZFS.ZFS.Get(ctx, state.DatasetName, false)
		if err != nil {
			logger.L.Error().Err(err).Str("dataset", state.DatasetName).
				Msg("rollback_jail_creation: failed to get dataset")
		} else if ds != nil {
			err := ds.Destroy(ctx, true, false)
			if err != nil {
				logger.L.Error().Err(err).Str("dataset", state.DatasetName).
					Msg("rollback_jail_creation: failed to destroy dataset")
			}
		}
	}

	if !config.IsDevFSDisabled() && state.CTID != 0 {
		if err := s.RemoveDevfsRulesForCTID(state.CTID); err != nil {
			logger.L.Error().Err(err).Uint("ctid", state.CTID).
				Msg("rollback_jail_creation: failed to remove devfs rules block")
		}
	}
}

func uniqueObjectName(tx *gorm.DB, base string) string {
	name := base
	for i := 0; ; i++ {
		if i > 0 {
			name = fmt.Sprintf("%s-%d", base, i)
		}
		var exists int64
		tx.Model(&networkModels.Object{}).Where("name = ?", name).Limit(1).Count(&exists)
		if exists == 0 {
			return name
		}
	}
}

func createRawObject(tx *gorm.DB, objType, baseName, rawValue string, autoCreatedIDs *[]uint) (uint, error) {
	name := uniqueObjectName(tx, baseName)

	obj := networkModels.Object{
		Name: name,
		Type: objType,
	}
	if err := tx.Create(&obj).Error; err != nil {
		return 0, fmt.Errorf("failed_to_create_raw_object: %w", err)
	}

	if err := tx.Create(&networkModels.ObjectEntry{
		ObjectID: obj.ID,
		Value:    rawValue,
	}).Error; err != nil {
		return 0, fmt.Errorf("failed_to_create_raw_object_entry: %w", err)
	}

	*autoCreatedIDs = append(*autoCreatedIDs, obj.ID)
	return obj.ID, nil
}

func resolveRawIP(ptr *int, raw string, tx *gorm.DB, objType, baseName string, autoCreatedIDs *[]uint) (*uint, error) {
	if ptr != nil && *ptr != 0 {
		id := new(uint)
		*id = uint(*ptr)
		return id, nil
	}
	if raw != "" {
		id := new(uint)
		var err error
		*id, err = createRawObject(tx, objType, baseName, raw, autoCreatedIDs)
		if err != nil {
			return nil, err
		}
		return id, nil
	}
	return nil, nil
}

func (s *Service) CreateJail(ctx context.Context, data jailServiceInterfaces.CreateJailRequest) (err error) {
	s.createMutex.Lock()
	defer s.createMutex.Unlock()

	if err = s.ValidateCreate(ctx, data); err != nil {
		logger.L.Debug().Err(err).Msg("create_jail: validation failed")
		return err
	}

	ctid := *data.CTID
	autoCreatedIDs := make([]uint, 0, 5)

	defer func() {
		if err == nil {
			return
		}

		s.cleanupFailedJailCreate(ctid, data.Pool, autoCreatedIDs)
	}()

	datasetName := fmt.Sprintf("%s/sylve/jails/%d", data.Pool, ctid)
	mountPoint := fmt.Sprintf("/%s/sylve/jails/%d", data.Pool, ctid)

	var dataset *gzfs.Dataset
	dataset, err = s.GZFS.ZFS.CreateFilesystem(ctx, datasetName, map[string]string{})
	if err != nil || dataset == nil {
		if err == nil {
			err = fmt.Errorf("nil_dataset_returned")
		}

		err = fmt.Errorf("failed_to_create_jail_dataset: %w", err)
		return
	}

	var jail jailModels.Jail

	jail.Name = data.Name
	jail.CTID = ctid
	jail.Description = data.Description
	jail.StartAtBoot = data.StartAtBoot
	jail.StartOrder = data.StartOrder
	jail.ResourceLimits = data.ResourceLimits
	jail.AdditionalOptions = data.AdditionalOptions
	jail.Fstab = data.Fstab

	jail.ResolvConf = data.ResolvConf

	jail.AllowedOptions = data.AllowedOptions
	jail.Type = data.Type
	jail.MetadataEnv = data.MetadataEnv
	jail.MetadataMeta = data.MetadataMeta

	if data.CleanEnvironment != nil {
		jail.CleanEnvironment = *data.CleanEnvironment
	} else {
		jail.CleanEnvironment = false
	}

	jail.JailHooks = []jailModels.JailHooks{
		{
			Phase:   jailModels.JailHookPhasePreStart,
			Enabled: data.Hooks.Prestart.Enabled,
			Script:  data.Hooks.Prestart.Script,
		},
		{
			Phase:   jailModels.JailHookPhaseStart,
			Enabled: data.Hooks.Start.Enabled,
			Script:  data.Hooks.Start.Script,
		},
		{
			Phase:   jailModels.JailHookPhasePostStart,
			Enabled: data.Hooks.Poststart.Enabled,
			Script:  data.Hooks.Poststart.Script,
		},
		{
			Phase:   jailModels.JailHookPhasePreStop,
			Enabled: data.Hooks.Prestop.Enabled,
			Script:  data.Hooks.Prestop.Script,
		},
		{
			Phase:   jailModels.JailHookPhaseStop,
			Enabled: data.Hooks.Stop.Enabled,
			Script:  data.Hooks.Stop.Script,
		},
		{
			Phase:   jailModels.JailHookPhasePostStop,
			Enabled: data.Hooks.Poststop.Enabled,
			Script:  data.Hooks.Poststop.Script,
		},
	}

	if jail.ResourceLimits != nil && *jail.ResourceLimits {
		jail.Cores = *data.Cores
		jail.Memory = *data.Memory
	} else {
		jail.Cores = 0
		jail.Memory = 0
	}

	jail.DevFSRuleset = data.DevFSRuleset

	jail.Storages = append(jail.Storages, jailModels.Storage{
		Pool:   data.Pool,
		GUID:   dataset.GUID,
		Name:   "Base Filesystem",
		IsBase: true,
	})

	tx := s.DB.Begin()
	if tx.Error != nil {
		return fmt.Errorf("failed_to_begin_tx: %w", tx.Error)
	}

	txCommitted := false
	defer func() {
		if err != nil && !txCommitted {
			_ = tx.Rollback()
		}
	}()

	// Create networks first to get their database IDs
	var createdNetworks []jailModels.Network
	var macStr string

	if strings.ToLower(data.SwitchName) != "inherit" && strings.ToLower(data.SwitchName) != "none" {
		var mac uint
		if data.MAC != nil {
			mac = uint(*data.MAC)
		}

		swType := ""
		swName := ""
		swID := uint(0)

		var stdSwitch networkModels.StandardSwitch
		if err = tx.First(&stdSwitch, "name = ?", data.SwitchName).Error; err == nil {
			swType = "standard"
			swName = stdSwitch.Name
			swID = stdSwitch.ID
		}

		var manualSwitch networkModels.ManualSwitch
		if err = tx.First(&manualSwitch, "name = ?", data.SwitchName).Error; err == nil {
			swType = "manual"
			swName = manualSwitch.Name
			swID = manualSwitch.ID
		}

		if swType == "" {
			err = fmt.Errorf("switch_not_found: %s", data.SwitchName)
			return
		}

		if mac == 0 {
			if data.MACRaw != "" {
				var macErr error
				mac, macErr = createRawObject(tx, "Mac", fmt.Sprintf("%s-%s-MAC", data.Name, swName), data.MACRaw, &autoCreatedIDs)
				if macErr != nil {
					err = macErr
					return
				}

				macStr = data.MACRaw
			} else {
				base := fmt.Sprintf("%s-%s", data.Name, swName)
				name := uniqueObjectName(tx, base)

				macAddress := utils.GenerateRandomMAC()
				macObj := networkModels.Object{
					Type: "Mac",
					Name: name,
				}

				macStr = macAddress

				if err = tx.Create(&macObj).Error; err != nil {
					err = fmt.Errorf("failed_to_create_mac_object: %w", err)
					return
				}
				autoCreatedIDs = append(autoCreatedIDs, macObj.ID)

				macEntry := networkModels.ObjectEntry{
					ObjectID: macObj.ID,
					Value:    macAddress,
				}

				if err = tx.Create(&macEntry).Error; err != nil {
					err = fmt.Errorf("failed_to_create_mac_entry: %w", err)
					return
				}

				mac = macObj.ID
			}
		} else {
			var macEntry networkModels.ObjectEntry
			if err = tx.Where("object_id = ?", mac).First(&macEntry).Error; err != nil {
				err = fmt.Errorf("failed_to_get_mac_entry: %w", err)
				return
			}

			macStr = macEntry.Value
		}

		var ipv4ID, ipv4GwID, ipv6ID, ipv6GwID *uint
		ipv4ID, err = resolveRawIP(data.IPv4, data.IPv4Raw, tx, "Network", fmt.Sprintf("%s-%s-IPv4", data.Name, swName), &autoCreatedIDs)
		if err != nil {
			return
		}
		ipv4GwID, err = resolveRawIP(data.IPv4Gw, data.IPv4GwRaw, tx, "Host", fmt.Sprintf("%s-%s-IPv4-GW", data.Name, swName), &autoCreatedIDs)
		if err != nil {
			return
		}
		ipv6ID, err = resolveRawIP(data.IPv6, data.IPv6Raw, tx, "Network", fmt.Sprintf("%s-%s-IPv6", data.Name, swName), &autoCreatedIDs)
		if err != nil {
			return
		}
		ipv6GwID, err = resolveRawIP(data.IPv6Gw, data.IPv6GwRaw, tx, "Host", fmt.Sprintf("%s-%s-IPv6-GW", data.Name, swName), &autoCreatedIDs)
		if err != nil {
			return
		}

		dhcp := false
		slaac := false

		if data.DHCP != nil && *data.DHCP {
			dhcp = *data.DHCP
		}

		if data.SLAAC != nil && *data.SLAAC {
			slaac = *data.SLAAC
		}

		vlan := 0
		if data.VLAN != nil {
			vlan = *data.VLAN
			if vlan < 0 || vlan > 4095 {
				return fmt.Errorf("invalid_vlan")
			}
		}

		// Create the network record first to get its ID
		network := jailModels.Network{
			Name:           fmt.Sprintf("Initial Switch - %s - %s", swName, data.Name),
			SwitchID:       swID,
			SwitchType:     swType,
			MacID:          &mac,
			IPv4ID:         ipv4ID,
			IPv4GwID:       ipv4GwID,
			IPv6ID:         ipv6ID,
			IPv6GwID:       ipv6GwID,
			DHCP:           dhcp,
			SLAAC:          slaac,
			DefaultGateway: true,
			VLAN:           &vlan,
		}

		if err = tx.Create(&network).Error; err != nil {
			err = fmt.Errorf("failed_to_create_network: %w", err)
			return
		}

		createdNetworks = append(createdNetworks, network)
	}

	if data.InheritIPv4 != nil {
		jail.InheritIPv4 = *data.InheritIPv4
	}

	if data.InheritIPv6 != nil {
		jail.InheritIPv6 = *data.InheritIPv6
	}

	// Associate the created networks with the jail
	jail.Networks = createdNetworks

	// Check if a jail with this CTID already exists
	var existingJail jailModels.Jail
	if err = tx.Where("ct_id = ?", jail.CTID).First(&existingJail).Error; err == nil {
		// Jail already exists - this is an error, don't overwrite existing jails
		logger.L.Error().Uint("ctid", jail.CTID).Msg("jail with this CTID already exists")
		err = fmt.Errorf("jail_with_ctid_already_exists: %d", jail.CTID)
		return
	} else if err != gorm.ErrRecordNotFound {
		// Some other database error occurred
		logger.L.Error().Err(err).Uint("ctid", jail.CTID).Msg("failed to check for existing jail")
		err = fmt.Errorf("failed_to_check_existing_jail: %w", err)
		return
	}

	// Now create the jail record and associate it with the networks
	if err = tx.Create(&jail).Error; err != nil {
		logger.L.Error().Err(err).Msg("create_jail: failed to create jail")
		err = fmt.Errorf("failed_to_create_jail: %w", err)
		return
	}

	// Update network records to link them to the jail
	for i := range createdNetworks {
		createdNetworks[i].JailID = jail.ID
		if err = tx.Save(&createdNetworks[i]).Error; err != nil {
			logger.L.Error().Err(err).Msg("create_jail: failed to update network jail association")
			err = fmt.Errorf("failed_to_update_network_jail_association: %w", err)
			return
		}
	}

	// Update jail.Networks to reflect the saved state with proper JailID
	jail.Networks = createdNetworks

	// Commit the transaction before the potentially long-running file copy
	if err = tx.Commit().Error; err != nil {
		/*
			2025/12/05 06:53:39 /zroot/projects/Sylve/internal/services/jail/jail.go:1081 duplicated key not allowed
			[0.167ms] [rows:0] INSERT INTO `jail_networks` (`jid`,`name`,`switch_id`,`switch_type`,`mac_id`,`ipv4_id`,`ipv4_gw_id`,`ipv6_id`,`ipv6_gw_id`,`default_gateway`,`dhcp`,`sla_ac`) VALUES (53,"Initial Switch",1,"manual",42,0,0,0,0,true,false,false) ON CONFLICT (`id`) DO UPDATE SET `jid`=`excluded`.`jid` RETURNING `id`
		*/
		// ^ If duplicate just continue?
		if strings.Contains(err.Error(), "duplicated key not allowed") {
			err = nil
		} else {
			err = fmt.Errorf("failed_to_commit_tx: %w", err)
			return
		}
	}
	txCommitted = true

	if data.BootstrapName != "" {
		bootstrapMount := fmt.Sprintf("/%s/sylve/bootstraps/%s", data.Pool, data.BootstrapName)
		if err = utils.CopyDirContents(bootstrapMount, mountPoint); err != nil {
			err = fmt.Errorf("failed_to_copy_bootstrap: %w", err)
			return
		}
	} else {
		var base string
		base, err = s.FindBaseByUUID(data.Base)
		if err != nil {
			err = fmt.Errorf("failed_to_find_base: %w", err)
			return
		}

		isDir, _ := utils.IsDir(base)
		if isDir {
			if err = utils.CopyDirContents(base, mountPoint); err != nil {
				err = fmt.Errorf("failed_to_copy_base: %w", err)
				return
			}
		} else {
			err = fmt.Errorf("base_is_not_a_directory")
			return
		}
	}

	var jailsPath string
	jailsPath, err = config.GetJailsPath()
	if err != nil {
		err = fmt.Errorf("failed_to_get_jails_path: %w", err)
		return
	}

	if jailsPath == "" {
		err = fmt.Errorf("jails_path_not_found")
		return
	}

	jailDir := filepath.Join(jailsPath, fmt.Sprintf("%d", ctid))
	if err = os.MkdirAll(jailDir, 0755); err != nil {
		err = fmt.Errorf("failed_to_create_jail_directory: %w", err)
		return
	}

	logsPath := filepath.Join(jailDir, fmt.Sprintf("%d.log", ctid))
	if err = os.WriteFile(logsPath, []byte(""), 0644); err != nil {
		err = fmt.Errorf("failed_to_write_log_file: %w", err)
		return
	}

	fstabPath := filepath.Join(jailDir, "fstab")
	if err = os.WriteFile(fstabPath, []byte(jail.Fstab), 0644); err != nil {
		err = fmt.Errorf("failed_to_write_fstab_file: %w", err)
		return
	}

	if strings.TrimSpace(jail.ResolvConf) != "" {
		resolvPath := filepath.Join(mountPoint, "etc", "resolv.conf")
		if err = os.MkdirAll(filepath.Dir(resolvPath), 0755); err != nil {
			err = fmt.Errorf("failed_to_prepare_resolv_conf_path: %w", err)
			return
		}

		if err = os.WriteFile(resolvPath, []byte(jail.ResolvConf), 0644); err != nil {
			err = fmt.Errorf("failed_to_write_resolv_conf_file: %w", err)
			return
		}
	}

	var jCfg string
	jCfg, err = s.CreateJailConfig(jail, mountPoint, macStr)
	if err != nil {
		err = fmt.Errorf("failed_to_create_jail_config: %w", err)
		return
	}

	jailConfigPath := filepath.Join(jailDir, fmt.Sprintf("%d.conf", ctid))
	if err = os.WriteFile(jailConfigPath, []byte(jCfg), 0644); err != nil {
		err = fmt.Errorf("failed_to_write_jail_config_file: %w", err)
		return
	}

	sylveDir := filepath.Join(mountPoint, ".sylve")
	if err = os.MkdirAll(sylveDir, 0755); err != nil {
		err = fmt.Errorf("failed_to_create_sylve_directory: %w", err)
		return
	}

	err = s.WriteJailJSON(ctid)
	if err != nil {
		logger.L.Error().Err(err).Msg("Failed to write jail metadata")
		return
	}

	return nil
}

func (s *Service) loadJailDeletePlan(ctx context.Context, ctID uint) (jailDeletePlan, error) {
	plan := jailDeletePlan{ctID: ctID}
	db := s.DB.WithContext(ctx)

	var jail jailModels.Jail
	if err := db.Model(&jailModels.Jail{}).
		Select("id, ct_id").
		Where("ct_id = ?", ctID).
		Take(&jail).Error; err != nil {
		return plan, fmt.Errorf("failed_to_fetch_jail_by_ctid: %w", err)
	}
	plan.jailID = jail.ID

	var pools []string
	if err := db.Model(&jailModels.Storage{}).
		Where("jid = ? AND is_base = ?", jail.ID, true).
		Pluck("pool", &pools).Error; err != nil {
		return plan, fmt.Errorf("failed_to_collect_jail_root_pools_for_delete: %w", err)
	}

	seenDatasets := make(map[string]struct{}, len(pools))
	for _, pool := range pools {
		pool = strings.Trim(strings.TrimSpace(pool), "/")
		if pool == "" {
			continue
		}
		dataset := fmt.Sprintf("%s/sylve/jails/%d", pool, ctID)
		if _, exists := seenDatasets[dataset]; exists {
			continue
		}
		seenDatasets[dataset] = struct{}{}
		plan.rootDatasets = append(plan.rootDatasets, dataset)
	}
	sort.Strings(plan.rootDatasets)

	if err := db.Model(&jailModels.Network{}).
		Where("jid = ? AND mac_id IS NOT NULL", jail.ID).
		Pluck("mac_id", &plan.macIDs).Error; err != nil {
		return plan, fmt.Errorf("failed_to_collect_jail_mac_ids_for_delete: %w", err)
	}
	plan.macIDs = uniqueUintValues(plan.macIDs)
	sort.Slice(plan.macIDs, func(i, j int) bool { return plan.macIDs[i] < plan.macIDs[j] })

	return plan, nil
}

func (s *Service) deleteJailDatabaseGraph(
	ctx context.Context,
	plan jailDeletePlan,
	allowReplicationPolicy bool,
) error {
	return s.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if !allowReplicationPolicy {
			if err := requireJailDeletionDetachedDB(tx, plan.ctID); err != nil {
				return err
			}
		}
		if err := tx.Where("jid = ?", plan.jailID).Delete(&jailModels.Network{}).Error; err != nil {
			return fmt.Errorf("failed_to_delete_jail_networks: %w", err)
		}
		if err := tx.Where("jid = ?", plan.jailID).Delete(&jailModels.JailHooks{}).Error; err != nil {
			return fmt.Errorf("failed_to_delete_jail_hooks: %w", err)
		}
		if err := tx.Where("jid = ?", plan.jailID).Delete(&jailModels.JailStats{}).Error; err != nil {
			return fmt.Errorf("failed_to_delete_jail_stats: %w", err)
		}
		if err := tx.Where("jid = ?", plan.jailID).Delete(&jailModels.JailSnapshot{}).Error; err != nil {
			return fmt.Errorf("failed_to_delete_jail_snapshots: %w", err)
		}
		storageDB := tx
		if allowReplicationPolicy {
			// Replication/migration retirement removes only stale local metadata.
			// Its explicit caller has already handled ownership and storage; the
			// normal topology hook must not reinterpret this as a user mutation.
			storageDB = tx.Session(&gorm.Session{SkipHooks: true})
		}
		if err := storageDB.Where("jid = ?", plan.jailID).Delete(&jailModels.Storage{}).Error; err != nil {
			return fmt.Errorf("failed_to_delete_jail_storages: %w", err)
		}

		result := tx.Where("id = ? AND ct_id = ?", plan.jailID, plan.ctID).Delete(&jailModels.Jail{})
		if result.Error != nil {
			return fmt.Errorf("failed_to_delete_jail: %w", result.Error)
		}
		if result.RowsAffected != 1 {
			return fmt.Errorf("failed_to_delete_jail: jail_identity_changed")
		}
		return nil
	})
}

func appendJailDeleteWarning(result *jailServiceInterfaces.DeleteJailResult, ctID uint, warning string, err error) {
	if result == nil {
		return
	}
	message := warning
	if err != nil {
		message = fmt.Sprintf("%s: %v", warning, err)
		logger.L.Warn().Uint("ctid", ctID).Err(err).Msg(warning)
	} else {
		logger.L.Warn().Uint("ctid", ctID).Msg(warning)
	}
	result.Warnings = append(result.Warnings, message)
}

func (s *Service) cleanupDeletedJailMACObjects(
	ctx context.Context,
	plan jailDeletePlan,
	result *jailServiceInterfaces.DeleteJailResult,
) {
	for _, macID := range plan.macIDs {
		if s.NetworkService != nil {
			used, _, err := s.NetworkService.IsObjectUsed(macID)
			if err != nil {
				appendJailDeleteWarning(
					result,
					plan.ctID,
					fmt.Sprintf("mac_cleanup_incomplete: object_id=%d", macID),
					err,
				)
				continue
			}
			if used {
				appendJailDeleteWarning(
					result,
					plan.ctID,
					fmt.Sprintf("mac_cleanup_incomplete: object_id=%d still_in_use", macID),
					nil,
				)
				continue
			}
		}

		err := s.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			if err := tx.Where("object_id = ?", macID).Delete(&networkModels.ObjectEntry{}).Error; err != nil {
				return fmt.Errorf("failed_to_delete_object_entries: %w", err)
			}
			if err := tx.Where("object_id = ?", macID).Delete(&networkModels.ObjectResolution{}).Error; err != nil {
				return fmt.Errorf("failed_to_delete_object_resolutions: %w", err)
			}
			if err := tx.Delete(&networkModels.Object{}, macID).Error; err != nil {
				return fmt.Errorf("failed_to_delete_object: %w", err)
			}
			return nil
		})
		if err != nil {
			appendJailDeleteWarning(
				result,
				plan.ctID,
				fmt.Sprintf("mac_cleanup_incomplete: object_id=%d", macID),
				err,
			)
		}
	}
}

func (s *Service) DeleteJail(ctx context.Context, ctID uint, deleteMacs bool, deleteRootFS bool) error {
	_, err := s.DeleteJailWithWarnings(ctx, ctID, deleteMacs, deleteRootFS)
	return err
}

func (s *Service) DeleteJailWithWarnings(
	ctx context.Context,
	ctID uint,
	deleteMacs bool,
	deleteRootFS bool,
) (jailServiceInterfaces.DeleteJailResult, error) {
	return s.deleteJailWithRuntime(
		ctx,
		ctID,
		deleteMacs,
		deleteRootFS,
		s.hostJailDeleteRuntime(),
	)
}

// RetireJailLocalMetadata is the narrow internal path used after migration or
// replication ownership has moved away from this node. Unlike a user delete,
// it may remove stale local metadata while the cluster policy still exists.
func (s *Service) RetireJailLocalMetadata(ctx context.Context, ctID uint, deleteMacs bool) error {
	_, err := s.deleteJailWithRuntimeOptions(
		ctx,
		ctID,
		deleteMacs,
		false,
		s.hostJailDeleteRuntime(),
		true,
	)
	return err
}

func (s *Service) deleteJailWithRuntime(
	ctx context.Context,
	ctID uint,
	deleteMacs bool,
	deleteRootFS bool,
	runtime jailDeleteRuntime,
) (jailServiceInterfaces.DeleteJailResult, error) {
	return s.deleteJailWithRuntimeOptions(
		ctx,
		ctID,
		deleteMacs,
		deleteRootFS,
		runtime,
		false,
	)
}

func (s *Service) deleteJailWithRuntimeOptions(
	ctx context.Context,
	ctID uint,
	deleteMacs bool,
	deleteRootFS bool,
	runtime jailDeleteRuntime,
	allowReplicationPolicy bool,
) (jailServiceInterfaces.DeleteJailResult, error) {
	result := jailServiceInterfaces.DeleteJailResult{
		Warnings:         make([]string, 0),
		RetainedDatasets: make([]string, 0),
	}
	if ctID == 0 {
		return result, fmt.Errorf("invalid_ct_id")
	}
	if ctx == nil {
		ctx = context.Background()
	}

	s.crudMutex.Lock()
	identityLocked := true
	defer func() {
		if identityLocked {
			s.crudMutex.Unlock()
		}
	}()

	if !allowReplicationPolicy {
		if err := requireJailDeletionDetachedDB(s.DB.WithContext(ctx), ctID); err != nil {
			return result, err
		}
	}

	plan, err := s.loadJailDeletePlan(ctx, ctID)
	if err != nil {
		return result, err
	}

	if err := ensureJailStoppedForDelete(ctx, ctID, runtime); err != nil {
		return result, err
	}
	if runtime.isRunning == nil || runtime.removeConfig == nil || runtime.removeDevfs == nil {
		return result, fmt.Errorf("jail_delete_runtime_not_initialized")
	}

	jailsPath, err := config.GetJailsPath()
	if err != nil {
		return result, fmt.Errorf("failed_to_get_jails_path: %w", err)
	}
	jailDir := filepath.Join(jailsPath, fmt.Sprintf("%d", ctID))

	if err := func() error {
		s.actionMutex.Lock()
		defer s.actionMutex.Unlock()

		running, err := runtime.isRunning(ctID)
		if err != nil {
			return fmt.Errorf("failed_to_revalidate_jail_runtime_before_delete: %w", err)
		}
		if running {
			return fmt.Errorf("jail_became_active_before_delete")
		}

		if err := runtime.removeConfig(jailDir); err != nil {
			return fmt.Errorf("failed_to_remove_jail_directory: %w", err)
		}
		if err := runtime.removeDevfs(ctID); err != nil {
			return fmt.Errorf("failed_to_remove_jail_devfs_rules: %w", err)
		}
		if err := s.deleteJailDatabaseGraph(ctx, plan, allowReplicationPolicy); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return result, err
	}
	s.crudMutex.Unlock()
	identityLocked = false

	if deleteRootFS {
		if len(plan.rootDatasets) == 0 {
			appendJailDeleteWarning(
				&result,
				ctID,
				fmt.Sprintf("storage_cleanup_incomplete: ctid=%d root_dataset_not_recorded", ctID),
				nil,
			)
		}
		for _, dataset := range plan.rootDatasets {
			if err := s.destroyStorageDatasetForDelete(ctx, dataset); err != nil {
				result.RetainedDatasets = append(result.RetainedDatasets, dataset)
				appendJailDeleteWarning(
					&result,
					ctID,
					fmt.Sprintf("storage_cleanup_incomplete: dataset=%s", dataset),
					err,
				)
			}
		}
	} else {
		result.RetainedDatasets = append(result.RetainedDatasets, plan.rootDatasets...)
	}

	if deleteMacs {
		s.cleanupDeletedJailMACObjects(ctx, plan, &result)
	}

	return result, nil
}

func (s *Service) UpdateDescription(id uint, description string) error {
	if id == 0 {
		return fmt.Errorf("invalid_jail_id")
	}

	if len(description) > 1024 {
		return fmt.Errorf("invalid_description")
	}

	var ctid uint
	if err := s.DB.Model(&jailModels.Jail{}).
		Select("ct_id").
		Where("id = ?", id).
		Take(&ctid).Error; err != nil {
		return fmt.Errorf("failed_to_fetch_jail_ctid: %w", err)
	}
	allowed, leaseErr := s.canMutateProtectedJail(ctid)
	if leaseErr != nil {
		return fmt.Errorf("replication_lease_check_failed: %w", leaseErr)
	}
	if !allowed {
		return fmt.Errorf("replication_lease_not_owned")
	}

	if err := s.DB.Model(&jailModels.Jail{}).
		Where("id = ?", id).
		Update("description", description).Error; err != nil {

		logger.L.Error().Err(err).
			Msg("update_jail_description: failed to update jail description")

		return fmt.Errorf("failed_to_update_jail_description: %w", err)
	}

	if ctid != 0 {
		_ = s.WriteJailJSON(ctid)
	}

	return nil
}

func (s *Service) UpdateName(id uint, name string) (uint, error) {
	if id == 0 {
		return 0, fmt.Errorf("invalid_jail_id")
	}

	name = strings.TrimSpace(name)
	if name == "" || !utils.IsValidVMName(name) {
		return 0, fmt.Errorf("invalid_vm_name")
	}

	var jail jailModels.Jail
	if err := s.DB.Select("id", "ct_id", "name").Where("id = ?", id).First(&jail).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return 0, fmt.Errorf("jail_not_found")
		}
		return 0, fmt.Errorf("failed_to_get_jail: %w", err)
	}

	ctid := jail.CTID
	allowed, leaseErr := s.canMutateProtectedJail(ctid)
	if leaseErr != nil {
		return 0, fmt.Errorf("replication_lease_check_failed: %w", leaseErr)
	}
	if !allowed {
		return 0, fmt.Errorf("replication_lease_not_owned")
	}

	var count int64
	if err := s.DB.Model(&jailModels.Jail{}).Where("name = ? AND id <> ?", name, id).Count(&count).Error; err != nil {
		return 0, fmt.Errorf("failed_to_check_jail_name_conflict: %w", err)
	}
	if count > 0 {
		return 0, fmt.Errorf("jail_name_already_in_use")
	}

	if strings.TrimSpace(jail.Name) == name {
		return ctid, nil
	}

	if err := s.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Model(&jailModels.Jail{}).Where("id = ?", id).Update("name", name).Error; err != nil {
			return fmt.Errorf("failed_to_update_jail_name: %w", err)
		}

		if err := tx.Model(&jailModels.JailTemplate{}).
			Where("source_jail_ctid = ?", ctid).
			Update("source_jail_name", name).Error; err != nil {
			return fmt.Errorf("failed_to_update_jail_template_source_name: %w", err)
		}

		return nil
	}); err != nil {
		return 0, err
	}

	if ctid != 0 {
		_ = s.WriteJailJSON(ctid)
	}

	s.emitLeftPanelRefresh(fmt.Sprintf("jail_rename_%d", ctid))

	return ctid, nil
}

func (s *Service) WriteJailJSON(ctId uint) error {
	if ctId == 0 {
		return fmt.Errorf("invalid_ct_id")
	}

	jail, err := s.GetJailByCTID(ctId)
	if err != nil {
		return err
	}

	var mountPoints []string
	for _, storage := range jail.Storages {
		if storage.IsBase {
			mountPoints = append(mountPoints, fmt.Sprintf("/%s/sylve/jails/%d", storage.Pool, ctId))
		}
	}

	for _, mountPoint := range mountPoints {
		sylveDir := filepath.Join(mountPoint, ".sylve")
		if err := os.MkdirAll(sylveDir, 0755); err != nil {
			return fmt.Errorf("failed_to_create_.sylve_directory: %w", err)
		}

		jailJsonPath := filepath.Join(sylveDir, "jail.json")
		jailJsonData, err := json.MarshalIndent(jail, "", "  ")
		if err != nil {
			return fmt.Errorf("failed_to_marshal_jail_to_json: %w", err)
		}

		if err := os.WriteFile(jailJsonPath, jailJsonData, 0644); err != nil {
			return fmt.Errorf("failed_to_write_jail_json_file: %w", err)
		}
	}

	return nil
}
